/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ti_msp430_usb_hiddemo_management_HidCommunicationManager */

#ifndef _Included_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
#define _Included_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_VENDOR
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_VENDOR 8263L
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_PRODUCT
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_PRODUCT 769L
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_TI_EXAMPLE_REPORT_ID
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_TI_EXAMPLE_REPORT_ID 63L
/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getNumberOfInterfaces
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getNumberOfInterfaces
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getSerialsForVidPid
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getSerialsForVidPid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getInterfacesForVidPid
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getInterfacesForVidPid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    connectDeviceNative
 * Signature: (IILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_connectDeviceNative
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    disconnectDeviceNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_disconnectDeviceNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    sendDataNative
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_sendDataNative
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    receiveDataNative
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_receiveDataNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
//Released_Version_5_20_06_02
