var jsonObjASM = [
	{"SourcePreview" : "fet410_1.asm",                "Description" : "Software Toggle P5.1"},
	{"SourcePreview" : "fet410_bt_01.asm",            "Description" : "Basic Timer, Toggle P5.1 Inside ISR, DCO SMCLK"},
	{"SourcePreview" : "fet410_bt_02.asm",            "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet410_clks_01.asm",          "Description" : "FLL+, Output MCLK, ACLK Using 32kHz XTAL and DCO"},
	{"SourcePreview" : "fet410_fll_01.asm",           "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "fet410_fll_02.asm",           "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "fet410_isp.asm",              "Description" : "Flash In-System Program Memory"},
	{"SourcePreview" : "fet410_lcd_01.asm",           "Description" : "LCD, Display \"6543210\" on STK/EVK LCD"},
	{"SourcePreview" : "fet410_lcd_02.asm",           "Description" : "LCD, Display Numbers on a Static LCD"},
	{"SourcePreview" : "fet410_lcd_03.asm",           "Description" : "LCD, Display Numbers on a 4-Mux LCD"},
	{"SourcePreview" : "fet410_LFxtal_nmi.asm",       "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "fet410_lpm3.asm",             "Description" : "FLL+, LPM3 Using Basic Timer ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet410_ta_01.asm",            "Description" : "Timer_A, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_02.asm",            "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_03.asm",            "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_04.asm",            "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet410_ta_05.asm",            "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet410_ta_16.asm",            "Description" : "Timer_A, PWM TA1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_17.asm",            "Description" : "Timer_A, PWM TA1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet410_ta_22.asm",            "Description" : "Timer_A, Output 40kHz Square Wave, Up Mode, SMCLK DCO"},
	{"SourcePreview" : "fet410_ta_25.asm",            "Description" : "Timer_A, Output DTMF, Cont. Mode, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_uart115k.asm",      "Description" : "Timer_A, UART 115200 Echo, DCO SMCLK"},
	{"SourcePreview" : "fet410_ta_uart2400.asm",      "Description" : "Timer_A, UART 2400 Ultra-low Power Echo, 32kHz ACLK"},
];

