<FMCG_COPYRIGHT>
<FMCG_DATE>

#ifndef MAIN_H_
#define MAIN_H_

<FMCG_MAIN_H_INCLUDE_DEFINES>
<FMCG_MAIN_H_INT_SERV_BIT_FIELDS>
<FMCG_MAIN_H_ESI_PORT_CONFIG>


//---- ESIOSC frequency setting based user selection for ACLK frequency
<FMCG_MAIN_H_ESI_ACLK_SET_VALUE>

#define ESIOSC_DEFAULT  4800000/ACLK_FREQUENCY_IN_HZ
#define ESIOSC_3MHz     3000000/ACLK_FREQUENCY_IN_HZ
#define ESIOSC_4MHz     4000000/ACLK_FREQUENCY_IN_HZ
#define ESIOSC_5MHz     5000000/ACLK_FREQUENCY_IN_HZ
#define ESIOSC_6MHz     6000000/ACLK_FREQUENCY_IN_HZ
#define ESIOSC_7MHz     7000000/ACLK_FREQUENCY_IN_HZ


<FMCG_MAIN_H_ESI_RECAL_DEFINES>


// LED 1 and LED2 PORT definition using driverlib definitions
<FMCG_MAIN_H_ESI_LED_DEFINES>


<FMCG_MAIN_H_ESI_TARGET_COMM_DEFINES>

#endif /* MAIN_H_ */
