var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F41x2",
		"Filter" : "MSP430F41\\d2"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x41x2_1.c",                                   "Description" : "Toggle P5.1 in software"},
	{"SourcePreview" : "MSP430x41x2_1_vlo.c",                               "Description" : "Software Toggle P5.1, MCLK = VLO/8"},
	{"SourcePreview" : "msp430x41x2_adc10_01.c",                            "Description" : "ADC10, Sample A0, AVcc Ref, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430x41x2_adc10_02.c",                            "Description" : "ADC10, Sample A0, 1.5V Ref, Set P1.0 if A0 > 0.2V    "},
	{"SourcePreview" : "msp430x41x2_adc10_03.c",                            "Description" : "ADC10, Sample A10 Temp, Set P1.0 if Temp ++ ~2C      "},
	{"SourcePreview" : "msp430x41x2_adc10_04.c",                            "Description" : "ADC10, Sample A0, Signed, Set P1.0 if A0 > 0.5*AVcc  "},
	{"SourcePreview" : "msp430x41x2_adc10_05.c",                            "Description" : "ADC10, Sample A11, Lo_Batt, Set P1.0 if AVcc < 2.3V  "},
	{"SourcePreview" : "msp430x41x2_adc10_06.c",                            "Description" : "ADC10, Output Internal Vref on P2.4 & ADCCLK on P1.0 "},
	{"SourcePreview" : "msp430x41x2_adc10_07.c",                            "Description" : "ADC10, DTC Sample A0 64x, AVcc, Repeat Single, DCO   "},
	{"SourcePreview" : "msp430x41x2_adc10_08.c",                            "Description" : "ADC10, DTC Sample A0 64x, 1.5V, Repeat Single, DCO   "},
	{"SourcePreview" : "msp430x41x2_adc10_09.c",                            "Description" : "ADC10, DTC Sample A10 64x, 1.5V, Repeat Single, DCO  "},
	{"SourcePreview" : "msp430x41x2_adc10_10.c",                            "Description" : "ADC10, DTC Sample A2-0, AVcc, Single Sequence, DCO   "},
	{"SourcePreview" : "msp430x41x2_adc10_11.c",                            "Description" : "ADC10, Sample A0, 1.5V, TA1 Trig, Set P1.0 if > 0.5V "},
	{"SourcePreview" : "msp430x41x2_adc10_12.c",                            "Description" : "ADC10, Sample A7, 1.5V, TA1 Trig, Ultra-Low Pwr      "},
	{"SourcePreview" : "msp430x41x2_adc10_13.c",                            "Description" : "ADC10, DTC Sample A1 32x, AVcc, TA0 Trig, DCO        "},
	{"SourcePreview" : "msp430x41x2_adc10_14.c",                            "Description" : "ADC10, DTC Sample A1-0 32x, AVcc, Repeat Seq, DCO    "},
	{"SourcePreview" : "msp430x41x2_adc10_15.c",                            "Description" : "ADC10, DTC Sample A10 32x to Flash, Int Ref, DCO     "},
	{"SourcePreview" : "msp430x41x2_adc10_16.c",                            "Description" : "ADC10, DTC Sample A0 -> TA1, AVcc, DCO               "},
	{"SourcePreview" : "msp430x41x2_adc10_21.c",                            "Description" : "ADC10, Sample A10 Temp and Convert to oC and oF      "},
	{"SourcePreview" : "msp430x41x2_bt_01.c",                               "Description" : "Basic Timer, Toggle P5.1 Inside ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_bt_02.c",                               "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430x41x2_clks.c",                                "Description" : "FLL+, Output 32kHz XTAL + Internal DCO"},
	{"SourcePreview" : "msp430x41x2_compA_01.c",                            "Description" : "Comparator A, Poll input CA0, result in P5.1"},
	{"SourcePreview" : "msp430x41x2_compA_02.c",                            "Description" : "Comparator A, Poll input CA0, CA exchange, result in P5.1 "},
	{"SourcePreview" : "msp430x41x2_compA_04.c",                            "Description" : "Comparator A, Poll input CA0, result in P5.1 "},
	{"SourcePreview" : "msp430x41x2_compA_05.c",                            "Description" : "Comparator A, Poll input CA0, interrupt triggered "},
	{"SourcePreview" : "msp430x41x2_flashwrite_01.c",                       "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x41x2_fll_01.c",                              "Description" : "FLL+, Runs Internal DCO at 2.5MHz"},
	{"SourcePreview" : "msp430x41x2_fll_02.c",                              "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "msp430x41x2_LFxtal_nmi.c",                          "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x41x2_lpm3_vlo.c",                            "Description" : "Basic Clock, LPM3 Using WDT ISR, VLO ACLK"},
	{"SourcePreview" : "msp430x41x2_P1_01.c",                               "Description" : "Software Poll P1.4, Set P5.1 if P1.4 = 1"},
	{"SourcePreview" : "msp430x41x2_P1_02.c",                               "Description" : "Software Port Interrupt on P1.4 from LPM4"},
	{"SourcePreview" : "msp430x41x2_svs_01.c",                              "Description" : "SVS, POR @ 2.5V Vcc"},
	{"SourcePreview" : "msp430x41x2_svs_03.c",                              "Description" : "SVS, Toggle port 5.1 on Vcc < 2.8V"},
	{"SourcePreview" : "msp430x41x2_ta_01.c",                               "Description" : "Timer_A, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_ta_02.c",                               "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_ta_03.c",                               "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_ta_04.c",                               "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x41x2_ta_05.c",                               "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x41x2_ta_16.c",                               "Description" : "Timer_A, Timer_A, PWM TA1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_ta_17.c",                               "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x41x2_uscia0_irda_01.c",                      "Description" : "USCI_A0 IrDA External Loopback Test, 4MHz SMCLK"},
	{"SourcePreview" : "msp430x41x2_uscia0_spi_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x41x2_uscia0_spi_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x41x2_uscia0_uart_115k.c",                    "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK                 "},
	{"SourcePreview" : "msp430x41x2_uscia0_uart_115k_lpm.c",                "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK, LPM3            "},
	{"SourcePreview" : "msp430x41x2_uscia0_uart_2400.c",                    "Description" : "USCI_A0, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK    "},
	{"SourcePreview" : "msp430x41x2_uscia0_uart_9600.c",                    "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x41x2_uscia0_uart_9600_02.c",                 "Description" : "Ultra-Low Pwr UART 9600 String, 32kHz ACLK             "},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_04.c",                       "Description" : "Master RX single bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_05.c",                       "Description" : "Slave TX single bytes to MSP430 Master  "},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_06.c",                       "Description" : "Master TX single bytes to MSP430 Slave  "},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_07.c",                       "Description" : "Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_08.c",                       "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_09.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x41x2_uscib0_i2c_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430x41x2_uscib0_spi_09.c",                       "Description" : "USCI_B0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x41x2_uscib0_spi_10.c",                       "Description" : "USCI_B0, SPI 3-Wire Slave Data Echo        "},
	{"SourcePreview" : "msp430x41x2_usci_i2c_standard_master.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430x41x2_usci_i2c_standard_slave.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430x41x2_usci_spi_standard_master.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430x41x2_usci_spi_standard_slave.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430x41x2_usci_uart_standard_transceiver.c",      "Description" : "USCI_A0, UART Echo received character"},
	{"SourcePreview" : "msp430x41x2_wdt_01.c",                              "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, DCO SMCLK "},
	{"SourcePreview" : "msp430x41x2_wdt_02.c",                              "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x41x2_wdt_04.c",                              "Description" : "WDT+ Failsafe Clock, DCO SMCLK"},
	{"SourcePreview" : "msp430x41x2_wdt_06.c",                              "Description" : "WDT+ Failsafe Clock, 32kHz ACLK"}
];

