var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F23x",
		"Filter" : "MSP430F23\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x24x_1.c",                                   "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430x24x_1_vlo.c",                               "Description" : "Software Toggle P1.0, MCLK = VLO/8"},
	{"SourcePreview" : "msp430x24x_adc12_01.c",                            "Description" : "ADC12, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430x24x_adc12_02.c",                            "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "msp430x24x_adc12_03.c",                            "Description" : "ADC12, Sample A10 Temp, Set P1.0 if Temp ++ ~2C"},
	{"SourcePreview" : "msp430x24x_adc12_04.c",                            "Description" : "ADC12, Extend Sampling Period with SHT Bits"},
	{"SourcePreview" : "msp430x24x_adc12_05.c",                            "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "msp430x24x_adc12_06.c",                            "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "msp430x24x_adc12_07.c",                            "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "msp430x24x_adc12_08.c",                            "Description" : "ADC12, Using 10 External Channels for Conversion"},
	{"SourcePreview" : "msp430x24x_adc12_09.c",                            "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "msp430x24x_adc12_10.c",                            "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "msp430x24x_clks.c",                                "Description" : "Basic Clock, Output Buffered SMCLK, ACLK, and MCLK"},
	{"SourcePreview" : "msp430x24x_compA_01.c",                            "Description" : "Comparator A, Poll input CA0, result in P1.0"},
	{"SourcePreview" : "msp430x24x_compA_02.c",                            "Description" : "Comparator A, Poll input CA0, CA exchange, result in P1.0"},
	{"SourcePreview" : "msp430x24x_compA_04.c",                            "Description" : "Comparator A, Poll input CA0, result in P1.0"},
	{"SourcePreview" : "msp430x24x_compA_05.c",                            "Description" : "Comparator A, Poll input CA0, interrupt triggered"},
	{"SourcePreview" : "msp430x24x_dco_flashcal.c",                        "Description" : "DCO Calibration Constants Programmer"},
	{"SourcePreview" : "msp430x24x_flashwrite_01.c",                       "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x24x_flashwrite_02.c",                       "Description" : "Flash In-System Programming w/ EEI, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x24x_flashwrite_03.c",                       "Description" : "Flash In-System Programming w/ EEI, Copy SegD to A/B/C"},
	{"SourcePreview" : "msp430x24x_fll_01.c",                              "Description" : "Basic Clock, Implement Auto RSEL SW FLL"},
	{"SourcePreview" : "msp430x24x_fll_02.c",                              "Description" : "Basic Clock, Implement Cont. SW FLL with Auto RSEL"},
	{"SourcePreview" : "msp430x24x_hfxt2.c",                               "Description" : "Basic Clock, MCLK Configured to Operate from XT2 HF XTAL"},
	{"SourcePreview" : "msp430x24x_hfxt2_nmi.c",                           "Description" : "Basic Clock, MCLK Sourced from HF XTAL XT2, NMI"},
	{"SourcePreview" : "msp430x24x_lpm3.c",                                "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_lpm3_vlo.c",                            "Description" : "Basic Clock, LPM3 Using WDT ISR, VLO ACLK"},
	{"SourcePreview" : "msp430x24x_nmi.c",                                 "Description" : "Configure RST/NMI as NMI"},
	{"SourcePreview" : "msp430x24x_OF_LFXT1.c",                            "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x24x_OF_XT2.c",                              "Description" : "XT2 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x24x_P1_01.c",                               "Description" : "Software Poll P1.3, Set P1.0 if P1.3 = 1"},
	{"SourcePreview" : "msp430x24x_P1_02.c",                               "Description" : "Software Port Interrupt Service on P1.3 from LPM4"},
	{"SourcePreview" : "msp430x24x_P1_05.c",                               "Description" : "Write a byte to Port 1"},
	{"SourcePreview" : "msp430x24x_rosc.c",                                "Description" : "DCOCLK Biased with External Resistor Rosc"},
	{"SourcePreview" : "msp430x24x_svs_01.c",                              "Description" : "SVS, POR @ 2.5V Vcc"},
	{"SourcePreview" : "msp430x24x_ta_01.c",                               "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_ta_02.c",                               "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_ta_03.c",                               "Description" : "Timer_A, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_ta_04.c",                               "Description" : "Timer_A, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_ta_05.c",                               "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_ta_11.c",                               "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_ta_13.c",                               "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_ta_17.c",                               "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_ta_19.c",                               "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_ta_20.c",                               "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_ta_24.c",                               "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz INCLK"},
	{"SourcePreview" : "msp430x24x_tb_01.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_tb_02.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_tb_03.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_tb_04.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_tb_05.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_tb_06.c",                               "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_tb_07.c",                               "Description" : "Timer_B, PWM TB1-6, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_tb_09.c",                               "Description" : "Timer_B, PWM TB1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_tb_10.c",                               "Description" : "Timer_B, PWM TB1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscia0_irda_01.c",                      "Description" : "USCI_A0 IrDA External Loopback Test, 8MHz SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_irda_02.c",                      "Description" : "USCI_A0 IrDA Monitor, 8MHz SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_irda_03.c",                      "Description" : "USCI_A0 IrDA Physical Layer Comm, 8MHz SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_spi_01.c",                       "Description" : "USCI_A0, SPI Interface to HC164 Shift Register"},
	{"SourcePreview" : "msp430x24x_uscia0_spi_02.c",                       "Description" : "USCI_A0, SPI Interface to HC165 Shift Register"},
	{"SourcePreview" : "msp430x24x_uscia0_spi_03.c",                       "Description" : "USCI_A0, SPI Interface to HC165/164 Shift Registers"},
	{"SourcePreview" : "msp430x24x_uscia0_spi_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x24x_uscia0_spi_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_01_115k.c",                 "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_01_115k_lpm.c",             "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK, LPM4"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_01_19200.c",                "Description" : "USCI_A0, 19200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_01_9600.c",                 "Description" : "USCI_A0, 9600 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_04_9600.c",                 "Description" : "USCI_A0, 9600 UART, SMCLK, LPM0, Echo with over-sampling"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_05_9600.c",                 "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_06_9600.c",                 "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 String, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_07_9600.c",                 "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 RX/TX, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscia0_uart_08_9600.c",                 "Description" : "USCI_A0, UART 9600 Full-Duplex Transceiver, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscia1_irda_01.c",                      "Description" : "USCI_A1 IrDA External Loopback Test, 8MHz SMCLK"},
	{"SourcePreview" : "msp430x24x_uscia1_spi_09.c",                       "Description" : "USCI_A1, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x24x_uscia1_spi_10.c",                       "Description" : "USCI_A1, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x24x_uscia1_uart_05_9600.c",                 "Description" : "USCI_A1, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_01.c",                       "Description" : "USCI_B0 I2C Master to TMP100, Set P1.0 if Temp > 28C"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_02.c",                       "Description" : "USCI_B0 I2C Master Interface to PCF8574, Read/Write"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_04.c",                       "Description" : "USCI_B0 I2C Master RX single bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_05.c",                       "Description" : "USCI_B0 I2C Slave TX single bytes to MSP430 Master"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_06.c",                       "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_07.c",                       "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_08.c",                       "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_09.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430x24x_uscib0_i2c_15.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master & USCI_A1 SPI Slave RX single bytes simultaneously."},
	{"SourcePreview" : "msp430x24x_uscib0_spi_01.c",                       "Description" : "USCI_B0, SPI Interface to TLC549 8-Bit ADC"},
	{"SourcePreview" : "msp430x24x_uscib0_spi_02.c",                       "Description" : "USCI_B0, SPI Interface to TLV1549 10-Bit ADC"},
	{"SourcePreview" : "msp430x24x_uscib0_spi_09.c",                       "Description" : "USCI_B0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x24x_uscib0_spi_10.c",                       "Description" : "USCI_B0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x24x_uscib1_i2c_06.c",                       "Description" : "USCI_B1 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x24x_uscib1_i2c_07.c",                       "Description" : "USCI_B1 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x24x_uscib1_spi_09.c",                       "Description" : "USCI_B1, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x24x_uscib1_spi_10.c",                       "Description" : "USCI_B1, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x24x_usci_i2c_standard_master.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430x24x_usci_i2c_standard_slave.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430x24x_usci_spi_standard_master.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430x24x_usci_spi_standard_slave.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430x24x_usci_uart_standard_transceiver.c",      "Description" : "USCI_A0, UART Echo received character"},
	{"SourcePreview" : "msp430x24x_wdt_01.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_wdt_02.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x24x_wdt_04.c",                              "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x24x_wdt_05.c",                              "Description" : "Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430x24x_wdt_06.c",                              "Description" : "WDT+ Failsafe Clock, 32kHz ACLK"}
];

