var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F674x(1)",
		"Filter" : "MSP430F674(\\d|\\d1)"
	}
];

var jsonObjC = [
	{"SourcePreview" : "MSP430F677x_ADC10_01.c",                            "Description" : "ADC10, Sample A0, AVcc Ref, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "MSP430F677x_ADC10_02.c",                            "Description" : "ADC10, Sample A0, 1.5V Shared Ref, Set P1.0 if A0 > 0.5V"},
	{"SourcePreview" : "MSP430F677x_ADC10_03.c",                            "Description" : "ADC10, Sample A10 Temp, TA0.1 Trigger, Set P1.0 if Temp++ ~2C"},
	{"SourcePreview" : "MSP430F677x_ADC10_04.c",                            "Description" : "ADC10, Sample A1, Signed, Set P1.0 if A1 > 0.5*AVcc"},
	{"SourcePreview" : "MSP430F677x_ADC10_05.c",                            "Description" : "ADC10, Sample A11, Lo_Batt, Clear P1.0 if AVcc < 2.3V"},
	{"SourcePreview" : "MSP430F677x_ADC10_06.c",                            "Description" : "ADC10, Internal Reference toggle"},
	{"SourcePreview" : "MSP430F677x_ADC10_07.c",                            "Description" : "ADC10, DMA Sample A1 64x, AVcc, Repeat Single, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_10.c",                            "Description" : "ADC10, DMA Sample A2-0, 8-bit Res, Single Sequence, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_11.c",                            "Description" : "ADC10, Sample A0, 1.5V Ref, TA0.1 Trig, Set P1.0 if A0>0.5V"},
	{"SourcePreview" : "MSP430F677x_ADC10_12.c",                            "Description" : "ADC10, Sample A5, 1.5V Ref, TA0.1 Trig, Ultra-Low Power"},
	{"SourcePreview" : "MSP430F677x_ADC10_13.c",                            "Description" : "ADC10, DMA Sample A1 32x, 2.5V Ref, TA3 Trig, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_14.c",                            "Description" : "ADC10, DMA Sample A1-0 32x, AVcc, Repeat Seq, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_15.c",                            "Description" : "ADC10, DMA Sample A11 32x to Flash, Int Ref, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_21.c",                            "Description" : "ADC10, Window Comparator, 2.5V ref, Timer trigger, DCO"},
	{"SourcePreview" : "MSP430F677x_ADC10_22.c",                            "Description" : "ADC10, Sample A3, AVcc Ref, SD24_B Trig, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "MSP430F677x_AUX_01.c",                              "Description" : "AUX, Software-Controlled Switching, AUXVCC1"},
	{"SourcePreview" : "MSP430F677x_AUX_02.c",                              "Description" : "AUX, Software-Controlled Switching, AUXVCC2"},
	{"SourcePreview" : "MSP430F677x_AUX_03.c",                              "Description" : "AUX, Hardware-Controlled Switching, AUXVCC1"},
	{"SourcePreview" : "MSP430F677x_AUX_04.c",                              "Description" : "AUX, Hardware-Controlled Switching, AUXVCC2"},
	{"SourcePreview" : "MSP430F677x_DMA_01.c",                              "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "MSP430F677x_DMA_04.c",                              "Description" : "DMA0, Single Transfer Using ADC10 Triggered by TimerA"},
	{"SourcePreview" : "MSP430F677x_FLASHWRITE_01.c",                       "Description" : "Flash In-System Programming, Single-Byte Copy SegC to SegD"},
	{"SourcePreview" : "MSP430F677x_FLASHWRITE_02.c",                       "Description" : "Flash In-System Programming, Long-Word Write at 0x1800"},
	{"SourcePreview" : "MSP430F677x_LCDC_01.c",                             "Description" : "LCD_C, Display a Single Character"},
	{"SourcePreview" : "MSP430F677x_LCDC_02.c",                             "Description" : "LCD_C, Alternates Between Two Strings"},
	{"SourcePreview" : "MSP430F677x_LCDC_03.c",                             "Description" : "LCD_C, Display 6 digit numbers"},
	{"SourcePreview" : "MSP430F677x_LPM3_01.c",                             "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, SVS disabled"},
	{"SourcePreview" : "MSP430F677x_LPM3_02.c",                             "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, SVS default state"},
	{"SourcePreview" : "MSP430F677x_LPM3_03.c",                             "Description" : "Enters LPM3 with ACLK =VLO;  LFXT1, REF0 disabled, SVS default state"},
	{"SourcePreview" : "MSP430F677x_LPM4.c",                                "Description" : "Enters LPM4;  LFXT1, REF0 disabled, SVS disabled"},
	{"SourcePreview" : "MSP430F677x_OF_LFXT1_NMI.c",                        "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "MSP430F677x_P1_01.c",                               "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "MSP430F677x_P1_02.c",                               "Description" : "Software Port Interrupt Service on P1.4 from LPM4 with Internal Pull-up Resistance Enabled"},
	{"SourcePreview" : "MSP430F677x_P1_05.c",                               "Description" : "Write a byte to Port 1"},
	{"SourcePreview" : "MSP430F677x_PORTMAP_01.c",                          "Description" : "Port Mapping, Port2; Single runtime configuration"},
	{"SourcePreview" : "MSP430F677x_PORTMAP_02.c",                          "Description" : "Port Mapping, Single function to multiple pins; Single runtime configuration."},
	{"SourcePreview" : "MSP430F677x_PORTMAP_03.c",                          "Description" : "Port Mapping, Port3; Single function to multiple pins; Multiple runtime configurations"},
	{"SourcePreview" : "MSP430F677x_RTC_01.c",                              "Description" : "RTC_C, Calendar Mode with Time Event and Alarm Interrupts"},
	{"SourcePreview" : "MSP430F677x_RTC_02.c",                              "Description" : "RTC_C, LPM3.5, & alarm"},
	{"SourcePreview" : "MSP430F677x_SD24B_01.c",                            "Description" : "SD24_B, Continuous Conversion on a Group of 3 Channels"},
	{"SourcePreview" : "MSP430F677x_SD24B_02.c",                            "Description" : "SD24_B, Single Conversion on a Group of 3 Channels"},
	{"SourcePreview" : "MSP430F677x_SD24B_03.c",                            "Description" : "SD24_B, Continuous Conversion on a Single Channel"},
	{"SourcePreview" : "MSP430F677x_SD24B_04.c",                            "Description" : "SD24_B, Single Conversion on Single Channel Polling IFG"},
	{"SourcePreview" : "MSP430F677x_SD24B_05.c",                            "Description" : "SD24_B, Single Conversion on a Single Channel Using ISR"},
	{"SourcePreview" : "MSP430F677x_SD24B_06.c",                            "Description" : "SD24_B, Single Conversion on a Single Channel Using ISR with 24 bit Result"},
	{"SourcePreview" : "MSP430F677x_SD24B_10.c",                            "Description" : "SD24_B, Continuous Conversion on a Group of 2 Channels"},
	{"SourcePreview" : "MSP430F677x_SD24B_11.c",                            "Description" : "SD24_B, Single Conversion on a Group of 2 Channels"},
	{"SourcePreview" : "MSP430F677x_TA0_02.c",                              "Description" : "Timer0_A0, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA0_04.c",                              "Description" : "Timer0_A0, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA0_16.c",                              "Description" : "Timer0_A0, PWM TA0.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA0_17.c",                              "Description" : "Timer0_A0, PWM TA0.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_01.c",                              "Description" : "Timer1_A1, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_02.c",                              "Description" : "Timer1_A1, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_03.c",                              "Description" : "Timer1_A1, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_04.c",                              "Description" : "Timer1_A1, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_05.c",                              "Description" : "Timer1_A1, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_11.c",                              "Description" : "Timer1_A1, Toggle P8.4/TA1.0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_13.c",                              "Description" : "Timer1_A1, Toggle P8.4/TA1.0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_14.c",                              "Description" : "Timer1_A1, Toggle P8.4/TA1.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_16.c",                              "Description" : "Timer1_A1, PWM TA1.1, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_17.c",                              "Description" : "Timer1_A1, PWM TA1.1, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA1_19.c",                              "Description" : "Timer1_A1, PWM TA1.1, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA1_20.c",                              "Description" : "Timer1_A1, PWM TA1.1, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA2_01.c",                              "Description" : "Timer2_A2, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA2_03.c",                              "Description" : "Timer2_A2, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_TA2_08.c",                              "Description" : "Timer2_A2, Toggle P1.0;P8.6-7, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA2_14.c",                              "Description" : "Timer2_A2, Toggle P8.6/TA2.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_TA2_19.c",                              "Description" : "Timer2_A2, PWM TA2.1, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_UCS_1.c",                               "Description" : "UCS, Software Toggle P1.0 at Default DCO"},
	{"SourcePreview" : "MSP430F677x_UCS_2.c",                               "Description" : "UCS, Software Toggle P1.0 with 8MHz DCO"},
	{"SourcePreview" : "MSP430F677x_UCS_4.c",                               "Description" : "UCS, Software Toggle P1.0 with 2.45MHz DCO, LFXT1 as Ref"},
	{"SourcePreview" : "MSP430F677x_UCS_5.c",                               "Description" : "UCS, VLO sources ACLK. Toggles P1.0"},
	{"SourcePreview" : "MSP430F677x_UCS_6.c",                               "Description" : "UCS, XT1 sources ACLK. Toggles P1.0"},
	{"SourcePreview" : "MSP430F677x_USCIA0_SPI_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "MSP430F677x_USCIA0_SPI_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "MSP430F677x_USCIA0_UART_03.c",                      "Description" : "USCI_A0, Ultra-Low Power UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_USCIB0_I2C_06.c",                       "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "MSP430F677x_USCIB0_I2C_07.c",                       "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "MSP430F677x_USCIB0_I2C_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "MSP430F677x_USCIB0_I2C_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "MSP430F677x_USCI_I2C_STANDARD_MASTER.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "MSP430F677x_USCI_I2C_STANDARD_SLAVE.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "MSP430F677x_USCI_SPI_STANDARD_MASTER.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "MSP430F677x_USCI_SPI_STANDARD_SLAVE.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "MSP430F677x_USCI_UART_STANDARD_TRANSCEIVER.c",      "Description" : "USCI_A0, UART Echo received character"},
	{"SourcePreview" : "MSP430F677x_WDT_01.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_WDT_02.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430F677x_WDT_04.c",                              "Description" : "WDT+, Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "MSP430F677x_WDT_05.c",                              "Description" : "WDT+, Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "MSP430F677x_WDT_06.c",                              "Description" : "WDT+, Failsafe Clock, 32kHz ACLK"}
];

