var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430FG461x",
		"Filter" : "MSP430FG461\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430xG46x_1.c",                                   "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430xG46x_adc12_01.c",                            "Description" : "ADC12, Sample A0, Set P5.1 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430xG46x_adc12_02.c",                            "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "msp430xG46x_adc12_03.c",                            "Description" : "ADC12, Sample A10 Temp, Set P5.1 if Temp ++ ~2C"},
	{"SourcePreview" : "msp430xG46x_adc12_04.c",                            "Description" : "ADC12, Extend Sampling Period with SHT Bits"},
	{"SourcePreview" : "msp430xG46x_adc12_05.c",                            "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "msp430xG46x_adc12_06.c",                            "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "msp430xG46x_adc12_07.c",                            "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "msp430xG46x_adc12_08.c",                            "Description" : "ADC12, Using 10 External Channels for Conversion"},
	{"SourcePreview" : "msp430xG46x_adc12_09.c",                            "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "msp430xG46x_adc12_10.c",                            "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "msp430xG46x_bt_01.c",                               "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_clks_02.c",                             "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430xG46x_compA_01.c",                            "Description" : "Comparator A, Poll input CA0, result in P5.1"},
	{"SourcePreview" : "msp430xG46x_compA_02.c",                            "Description" : "Comparator A, Poll input CA0, CA exchange, result in P5.1"},
	{"SourcePreview" : "msp430xG46x_compA_04.c",                            "Description" : "Comparator A, Poll input CA0, result in P5.1"},
	{"SourcePreview" : "msp430xG46x_compA_05.c",                            "Description" : "Comparator A, Poll input CA0, interrupt triggered"},
	{"SourcePreview" : "msp430xG46x_dac12_01.c",                            "Description" : "DAC12_0, Output 1.0V on DAC0"},
	{"SourcePreview" : "msp430xG46x_dac12_02.c",                            "Description" : "DAC12_1, Output 2.0V on DAC1"},
	{"SourcePreview" : "msp430xG46x_dac12_03.c",                            "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "msp430xG46x_fll_01.c",                              "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "msp430xG46x_fll_02.c",                              "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "msp430xG46x_hfxt2.c",                               "Description" : "FLL+, MCLK Configured to Operate from XT2 HF XTAL"},
	{"SourcePreview" : "msp430xG46x_lpm3.c",                                "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_oa_01.c",                               "Description" : "OA0, Comparator Mode"},
	{"SourcePreview" : "msp430xG46x_oa_02.c",                               "Description" : "OA0, Comparator in General-Purpose Mode"},
	{"SourcePreview" : "msp430xG46x_oa_03.c",                               "Description" : "OA0, General-Purpose Mode"},
	{"SourcePreview" : "msp430xG46x_oa_04.c",                               "Description" : "OA0, Inverting PGA Mode"},
	{"SourcePreview" : "msp430xG46x_oa_05.c",                               "Description" : "OA0, Non-Inverting PGA Mode"},
	{"SourcePreview" : "msp430xG46x_oa_06.c",                               "Description" : "OA0, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430xG46x_oa_07.c",                               "Description" : "OA1, Comparator Mode"},
	{"SourcePreview" : "msp430xG46x_oa_08.c",                               "Description" : "OA1, Comparator in General-Purpose Mode"},
	{"SourcePreview" : "msp430xG46x_oa_09.c",                               "Description" : "OA1, Inverting PGA Mode"},
	{"SourcePreview" : "msp430xG46x_oa_10.c",                               "Description" : "OA1, Non-Inverting PGA Mode"},
	{"SourcePreview" : "msp430xG46x_oa_11.c",                               "Description" : "OA1, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430xG46x_oa_12.c",                               "Description" : "3-Amp Differential Amplifier with OA0, OA1, and OA2"},
	{"SourcePreview" : "msp430xG46x_oa_13.c",                               "Description" : "3-Amp Differential Amplifier with OA1, OA2, and OA0"},
	{"SourcePreview" : "msp430xG46x_oa_14.c",                               "Description" : "3-Amp Differential Amplifier with OA2, OA0, and OA1"},
	{"SourcePreview" : "msp430xG46x_OF_LFXT1_nmi.c",                        "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430xG46x_OF_XT2.c",                              "Description" : "XT2 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430xG46x_P1_01.c",                               "Description" : "Software Poll P1.4, Set P5.1 if P1.4 = 1"},
	{"SourcePreview" : "msp430xG46x_P1_02.c",                               "Description" : "Software Port Interrupt on P1.4 from LPM4"},
	{"SourcePreview" : "msp430xG46x_P1_05.c",                               "Description" : "Write a byte to Port 1"},
	{"SourcePreview" : "msp430xG46x_P7_05.c",                               "Description" : "Write a byte to Port 7"},
	{"SourcePreview" : "msp430xG46x_P8_05.c",                               "Description" : "Write a byte to Port 8"},
	{"SourcePreview" : "msp430xG46x_PA_05.c",                               "Description" : "Write a word to Port A"},
	{"SourcePreview" : "msp430xG46x_PB_05.c",                               "Description" : "Write a word to Port B"},
	{"SourcePreview" : "msp430xG46x_rtc_01.c",                              "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_rtc_02.c",                              "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK;and send Time via UART"},
	{"SourcePreview" : "msp430xG46x_rtc_03.c",                              "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK;send Time via UART and preserve across RESET"},
	{"SourcePreview" : "msp430xG46x_ta_01.c",                               "Description" : "Timer_A, Toggle P5.1, TACCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_ta_02.c",                               "Description" : "Timer_A, Toggle P5.1, TACCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_ta_03.c",                               "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_ta_04.c",                               "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_ta_05.c",                               "Description" : "Timer_A, Toggle P5.1, TACCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_ta_08.c",                               "Description" : "Timer_A, Toggle P1.0,P1.2 & P2.0 Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_ta_11.c",                               "Description" : "Timer_A, Toggle P1.0/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_ta_13.c",                               "Description" : "Timer_A, Toggle P1.0/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_ta_17.c",                               "Description" : "Timer_A, PWM TA1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_ta_19.c",                               "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_tb_01.c",                               "Description" : "Timer_B, Toggle P5.1, TBCCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_tb_02.c",                               "Description" : "Timer_B, Toggle P5.1, TBCCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_tb_04.c",                               "Description" : "Timer_B, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_tb_05.c",                               "Description" : "Timer_B, Toggle P5.1, TBCCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_tb_10.c",                               "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_usart1_19200.c",                        "Description" : "USART1, Ultra-Low Pwr UART 19200 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_usart1_spi0_09.c",                      "Description" : "USART1, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430xG46x_usart1_spi0_10.c",                      "Description" : "USART1, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430xG46x_usart1_spi1_01.c",                      "Description" : "USART1, SPI Interface to TLC549 8-Bit ADC"},
	{"SourcePreview" : "msp430xG46x_usart1_uart_115k.c",                    "Description" : "USART1, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_usart1_uart_2400.c",                    "Description" : "USART1, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_usart1_uart_9600.c",                    "Description" : "USART1, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_uscia0b0_uart_spi_01.c",                "Description" : "USCI_A0 UART TX single byte and USCI_B0 SPI Master TX single byte to MSP430 Slave"},
	{"SourcePreview" : "msp430xG46x_uscia0b0_uart_spi_02.c",                "Description" : "USCI_A0 UART RX single byte and USCI_B0 SPI Slave RX single byte from MSP430 Master"},
	{"SourcePreview" : "msp430xG46x_uscia0_duplex_9600.c",                  "Description" : "USCI_A0, UART 9600 Full-Duplex Transceiver, 32K ACLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_irda_01.c",                      "Description" : "USCI_A0 IrDA External Loopback Test, 4MHz SMCLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_irda_02.c",                      "Description" : "USCI_A0 IrDA Monitor, 4MHz SMCLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_irda_03.c",                      "Description" : "USCI_A0 IrDA Physical Layer Comm, 4MHz SMCLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_spi_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430xG46x_uscia0_spi_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430xG46x_uscia0_uart_115k.c",                    "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_uart_115k_lpm.c",                "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK, LPM3"},
	{"SourcePreview" : "msp430xG46x_uscia0_uart_9600.c",                    "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430xG46x_uscia0_uart_uscia0b0_i2c_1.c",          "Description" : "USCI_A0 UART TX single byte and USCI_B0 I2C Master TX single byte to MSP430 Slave"},
	{"SourcePreview" : "msp430xG46x_uscia0_uart_uscia0b0_i2c_2.c",          "Description" : "USCI_A0 UART RX single byte and USCI_B0 I2C Slave RX single byte from MSP430 Master"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_02.c",                       "Description" : "USCI_B0 I2C Master Interface to PCF8574, Read/Write"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_03.c",                       "Description" : "USCI_B0 I2C Master Interface to DAC8571, Write"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_08.c",                       "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_09.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430xG46x_uscib0_i2c_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430xG46x_uscib0_spi_01.c",                       "Description" : "USCI_B0, SPI Interface to TLC549 8-Bit ADC"},
	{"SourcePreview" : "msp430xG46x_usci_i2c_standard_master.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430xG46x_usci_i2c_standard_slave.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430xG46x_usci_spi_standard_master.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430xG46x_usci_spi_standard_slave.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430xG46x_usci_uart_standard_transceiver.c",      "Description" : "USCI_A0, UART Echo received character"}
];

