var jsonObjASM = [
	{"SourcePreview" : "fet440_1.asm",                 "Description" : "Software Toggle P5.1"},
	{"SourcePreview" : "fet440_adc12_01.asm",          "Description" : "ADC12, Sample A0, Set P5.1 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "fet440_adc12_02.asm",          "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "fet440_adc12_03.asm",          "Description" : "ADC12, Sample A10 Temp, Set P5.1 if temp ++ ~2c"},
	{"SourcePreview" : "fet440_adc12_04.asm",          "Description" : "ADC12, Extend Sampling Period With SHT Bits"},
	{"SourcePreview" : "fet440_adc12_05.asm",          "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "fet440_adc12_06.asm",          "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "fet440_adc12_07.asm",          "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "fet440_adc12_08.asm",          "Description" : "ADC12, Using 10 External Channels of Conversion"},
	{"SourcePreview" : "fet440_adc12_09.asm",          "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "fet440_adc12_10.asm",          "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "fet440_bt_01.asm",             "Description" : "Basic Timer, Toggle P5.1 Inside ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_bt_02.asm",             "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_clks_01.asm",           "Description" : "FLL+, Output MCLK, SMCLK, ACLK Using 32kHz XTAL"},
	{"SourcePreview" : "fet440_clks_02.asm",           "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "fet440_fll_01.asm",            "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "fet440_fll_02.asm",            "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "fet440_hfxt2.asm",             "Description" : "FLL+, MCLK Configured to Operate from XT2 HF XTAL"},
	{"SourcePreview" : "fet440_isp.asm",               "Description" : "Flash In-System Program Memory"},
	{"SourcePreview" : "fet440_lcd_01.asm",            "Description" : "LCD, Display \"6543210\" on STK/EVK LCD"},
	{"SourcePreview" : "fet440_lcd_02.asm",            "Description" : "LCD, Display Numbers on a Static LCD"},
	{"SourcePreview" : "fet440_lcd_03.asm",            "Description" : "LCD, Display Numbers on a 4-Mux LCD"},
	{"SourcePreview" : "fet440_LFxtal_nmi.asm",        "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "fet440_lpm3.asm",              "Description" : "FLL+, LPM3 Using Basic Timer ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_spi0_016x.asm",         "Description" : "USART0, SPI Interface to HC165/164 Shift Registers"},
	{"SourcePreview" : "fet440_svs_01.asm",            "Description" : "SVS, POR @ 2.5V Vcc"},
	{"SourcePreview" : "fet440_ta_01.asm",             "Description" : "Timer_A, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_ta_02.asm",             "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_ta_03.asm",             "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_ta_04.asm",             "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_ta_05.asm",             "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_ta_16.asm",             "Description" : "Timer_A, PWM TA1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet440_ta_17.asm",             "Description" : "Timer_A, PWM TA1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet440_tb_01.asm",             "Description" : "Timer_B, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_tb_02.asm",             "Description" : "Timer_B, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_tb_03.asm",             "Description" : "Timer_B, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_tb_04.asm",             "Description" : "Timer_B, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_tb_05.asm",             "Description" : "Timer_B Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_tb_10.asm",             "Description" : "Timer_B, PWM TB1-6 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet440_tb_11.asm",             "Description" : "Timer_B, PWM TB1-6 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet440_uart01_0115k.asm",      "Description" : "USART0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_uart01_02400.asm",      "Description" : "USART0, 2400 UART Ultra-low Pwr Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet440_uart01_09600.asm",      "Description" : "USART0, 9600 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_uart01_19200.asm",      "Description" : "USART0, 19200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_uart02_19200.asm",      "Description" : "USART0, 19200 UART Ultra-low Pwr Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_uart11_19200.asm",      "Description" : "USART1, 19200 UART Echo ISR, DC0 SMCLK"},
	{"SourcePreview" : "fet440_uart11_38400.asm",      "Description" : "USART1, 38400 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_wdt_01.asm",            "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet440_wdt_02.asm",            "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, 32kHz ACLK"}
];

