var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F525x",
		"Filter" : "MSP430F525\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430f525x_1.c",                                   "Description" : "Toggle P1.0/LED"},
	{"SourcePreview" : "msp430f525x_adc10_01.c",                            "Description" : "ADC10, Sample A0, AVcc Ref, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430f525x_adc10_02.c",                            "Description" : "ADC10, Sample A0, 1.5V Shared Ref, Set P1.0 if A0 > 0.5V"},
	{"SourcePreview" : "msp430f525x_adc10_03.c",                            "Description" : "ADC10, Sample A10 Temp, TA0.1 Trigger, Set P1.0 if Temp++ ~2C"},
	{"SourcePreview" : "msp430f525x_adc10_04.c",                            "Description" : "ADC10, Sample A1, Signed, Set P1.0 if A1 > 0.5*AVcc"},
	{"SourcePreview" : "msp430f525x_adc10_05.c",                            "Description" : "ADC10, Sample A11, Lo_Batt, Clear P1.0 if AVcc < 2.3V"},
	{"SourcePreview" : "msp430f525x_adc10_06.c",                            "Description" : "ADC10, Internal Reference toggle"},
	{"SourcePreview" : "msp430f525x_adc10_07.c",                            "Description" : "ADC10, DMA Sample A1 64x, AVcc, Repeat Single, DCO"},
	{"SourcePreview" : "msp430f525x_adc10_10.c",                            "Description" : "ADC10, DMA Sample A2-0, 8-bit Res, Single Sequence, DCO"},
	{"SourcePreview" : "msp430f525x_adc10_11.c",                            "Description" : "ADC10, Sample A0, 1.5V Ref, TA0.1 Trig, Set P1.0 if A0>0.5V"},
	{"SourcePreview" : "msp430f525x_adc10_12.c",                            "Description" : "ADC10, Sample A5, 1.5V Ref, TA0.0 Trig, Ultra-Low Pwr"},
	{"SourcePreview" : "msp430f525x_adc10_13.c",                            "Description" : "ADC10, DMA Sample A1 32x, 2.5V Ref, TB0 Trig, DCO"},
	{"SourcePreview" : "msp430f525x_adc10_14.c",                            "Description" : "ADC10, DMA Sample A1-0 32x, AVcc, Repeat Seq, DCO"},
	{"SourcePreview" : "msp430f525x_adc10_15.c",                            "Description" : "ADC10, DMA Sample A11 32x to Flash, Int Ref, DCO"},
	{"SourcePreview" : "msp430f525x_adc10_21.c",                            "Description" : "ADC10, Window Comparator, 2.5V ref, Timer trigger, DCO"},
	{"SourcePreview" : "msp430f525x_compb_01.c",                            "Description" : "COMPB output Toggle in LPM4; "},
	{"SourcePreview" : "msp430f525x_compb_02.c",                            "Description" : "COMPB output Toggle from LPM4; input channel CB1; "},
	{"SourcePreview" : "msp430f525x_compb_03.c",                            "Description" : "COMPB interrupt capability; "},
	{"SourcePreview" : "msp430f525x_compb_04.c",                            "Description" : "COMPB Toggle from LPM4; Ultra low power mode; "},
	{"SourcePreview" : "msp430f525x_compb_05.c",                            "Description" : "COMPB Hysteresis, CBOUT Toggle in LPM4; High speed mode"},
	{"SourcePreview" : "msp430f525x_compb_06.c",                            "Description" : "COMPB and TIMERAx interaction (TA0.1, TA1.1)"},
	{"SourcePreview" : "msp430f525x_dma_01.c",                              "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "msp430f525x_dma_02.c",                              "Description" : "DMA0, Repeated Block UCA1UART 9600, TACCR2, ACLK"},
	{"SourcePreview" : "msp430f525x_dma_03.c",                              "Description" : "SPI TX & RX using DMA0 & DMA1 Single Transfer in Fixed Address Mode"},
	{"SourcePreview" : "msp430f525x_flashwrite_01.c",                       "Description" : "Single-Byte Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430f525x_flashwrite_02.c",                       "Description" : "Flash In-System Programming w/ Long-Word write at 0x1800"},
	{"SourcePreview" : "msp430f525x_lpm3_01.c",                             "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, VUSB LDO and SLDO disabled, SVS disabled"},
	{"SourcePreview" : "msp430f525x_lpm3_02.c",                             "Description" : "Enters LPM3 (ACLK = VLO)"},
	{"SourcePreview" : "msp430f525x_of_lfxt1_nmi.c",                        "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430f525x_p1_01.c",                               "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "msp430f525x_p1_02.c",                               "Description" : "Software Port Interrupt Service on P1.4 from LPM4 with Internal Pull-up Resistance Enabled"},
	{"SourcePreview" : "msp430f525x_p1_03.c",                               "Description" : "Software Port Interrupt Service on P1.4 from LPM4"},
	{"SourcePreview" : "msp430f525x_pa_05.c",                               "Description" : "Write a Word to Port A (Port1+Port2)  "},
	{"SourcePreview" : "msp430f525x_pb_05.c",                               "Description" : "Write a Word to Port B (Port3+Port4)"},
	{"SourcePreview" : "msp430f525x_portmap_01.c",                          "Description" : "Port Mapping Port4; Single runtime configuration"},
	{"SourcePreview" : "msp430f525x_portmap_02.c",                          "Description" : "Port Mapping single function to multiple pins; Single runtime configuration."},
	{"SourcePreview" : "msp430f525x_portmap_03.c",                          "Description" : "Port Map single function to multiple pins; Multiple runtime configurations"},
	{"SourcePreview" : "msp430f525x_ta0_02.c",                              "Description" : "Timer0_A5, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta0_04.c",                              "Description" : "Timer0_A5, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta0_16.c",                              "Description" : "Timer0_A5, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta0_17.c",                              "Description" : "Timer0_A5, PWM TA1.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_01.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK   "},
	{"SourcePreview" : "msp430f525x_ta1_02.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta1_03.c",                              "Description" : "Timer1_A3, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta1_04.c",                              "Description" : "Timer1_A3, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_05.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_11.c",                              "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_13.c",                              "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta1_14.c",                              "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_16.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta1_17.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta1_19.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_ta1_20.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ta2_01.c",                              "Description" : "Timer2_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK   "},
	{"SourcePreview" : "msp430f525x_ta2_03.c",                              "Description" : "Timer2_A3, Toggle P1.0, Overflow ISR, DCO SMCLK   "},
	{"SourcePreview" : "msp430f525x_ta2_08.c",                              "Description" : "Timer2_A3, Toggle P1.0;P2.3-5, Cont. Mode ISR, 32kHz ACLK    "},
	{"SourcePreview" : "msp430f525x_ta2_14.c",                              "Description" : "Timer2_A3, Toggle P2.3/TA2.0, Up/Down Mode, 32kHz ACLK   "},
	{"SourcePreview" : "msp430f525x_ta2_19.c",                              "Description" : "Timer2_A3, PWM TA1.1-2, Up/Down Mode, DCO SMCLK  "},
	{"SourcePreview" : "msp430f525x_tb_01.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_tb_02.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_tb_03.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_tb_04.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_tb_05.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_ucs_01.c",                              "Description" : "Software Toggle P1.1 at Default DCO "},
	{"SourcePreview" : "msp430f525x_ucs_02.c",                              "Description" : "Software Toggle P1.1 with 8MHz DCO"},
	{"SourcePreview" : "msp430f525x_ucs_03.c",                              "Description" : "Software Toggle P1.1 with 12MHz DCO"},
	{"SourcePreview" : "msp430f525x_ucs_04.c",                              "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "msp430f525x_ucs_05.c",                              "Description" : "VLO sources ACLK"},
	{"SourcePreview" : "msp430f525x_ucs_06.c",                              "Description" : "XT1 sources ACLK"},
	{"SourcePreview" : "msp430f525x_ucs_07.c",                              "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430f525x_ucs_08.c",                              "Description" : "XT2 sources MCLK & SMCLK"},
	{"SourcePreview" : "msp430f525x_ucs_10.c",                              "Description" : "Software Toggle P1.1 with 25MHz DCO"},
	{"SourcePreview" : "msp430f525x_uscia0_spi_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430f525x_uscia0_spi_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430f525x_uscia0_uart_01.c",                      "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_uscia0_uart_02.c",                      "Description" : "USCI_A0, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_uscia0_uart_03.c",                      "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_uscia0_uart_04.c",                      "Description" : "USCI_A0, 9600 UART, SMCLK, LPM0, Echo with over-sampling"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_04.c",                       "Description" : "USCI_B0 I2C Master RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_05.c",                       "Description" : "USCI_B0 I2C Slave TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_06.c",                       "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_07.c",                       "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_08.c",                       "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_09.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430f525x_uscib0_i2c_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430f525x_usci_i2c_standard_master.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430f525x_usci_i2c_standard_slave.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430f525x_usci_spi_standard_master.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430f525x_usci_spi_standard_slave.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430f525x_usci_uart_standard_transceiver.c",      "Description" : "USCI_A0, UART Echo received character"},
	{"SourcePreview" : "msp430f525x_wdt_01.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_wdt_02.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f525x_wdt_04.c",                              "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f525x_wdt_05.c",                              "Description" : "Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430f525x_wdt_06.c",                              "Description" : " WDT+ Failsafe Clock, 32kHz ACLK"}
];

