var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F12x2",
		"Filter" : "MSP430F12\\d2"
	}
];

var jsonObjC = [
	{"SourcePreview" : "fet120_1.c",                 "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "fet120_adc10_01.c",          "Description" : "ADC10, Sample A0, AVcc Ref, Set P1.0 if > 0.5*AVcc"},
	{"SourcePreview" : "fet120_adc10_02.c",          "Description" : "ADC10, Sample A0, 1.5V Ref, Set P1.0 if > 0.2V"},
	{"SourcePreview" : "fet120_adc10_03.c",          "Description" : "ADC10, Sample A10 Temp, Set P1.0 if Temp ++ ~2C"},
	{"SourcePreview" : "fet120_adc10_04.c",          "Description" : "ADC10, Sample A0, Signed, Set P1.0 if > 0.5*AVcc"},
	{"SourcePreview" : "fet120_adc10_05.c",          "Description" : "ADC10, Sample A11, Lo_Batt, Set P1.0 if < 2.3V"},
	{"SourcePreview" : "fet120_adc10_06.c",          "Description" : "ADC10, Output Internal Vref on P2.4 & ADCCLK on P1.0"},
	{"SourcePreview" : "fet120_adc10_07.c",          "Description" : "ADC10, DTC Sample A0 64x, AVcc, Repeat Single, DCO"},
	{"SourcePreview" : "fet120_adc10_08.c",          "Description" : "ADC10, DTC Sample A0 64x, 1.5V, Repeat Single, DCO"},
	{"SourcePreview" : "fet120_adc10_09.c",          "Description" : "ADC10, DTC Sample A10 64x, 1.5V, Repeat Single, DCO"},
	{"SourcePreview" : "fet120_adc10_10.c",          "Description" : "ADC10, DTC Sample A2-0, AVcc, Single Sequence, DCO"},
	{"SourcePreview" : "fet120_adc10_11.c",          "Description" : "ADC10, Sample A0, 1.5V, TA1 Trig, Set P1.0 if > 0.5V"},
	{"SourcePreview" : "fet120_adc10_12.c",          "Description" : "ADC10, Sample A7, 1.5V, TA1 Trig, Ultra-Low Pwr"},
	{"SourcePreview" : "fet120_adc10_13.c",          "Description" : "ADC10, DTC Sample A1 32x, AVcc, TA0 Trig, DCO"},
	{"SourcePreview" : "fet120_adc10_14.c",          "Description" : "ADC10, DTC Sample A1-0 32x, AVcc, Repeat Seq, DCO"},
	{"SourcePreview" : "fet120_adc10_15.c",          "Description" : "ADC10, DTC Sample A10 32x to Flash, Int Ref, DCO"},
	{"SourcePreview" : "fet120_adc10_temp.c",        "Description" : "ADC10, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "fet120_clks.c",              "Description" : "Basic Clock, Output Buffered SMCLK, ACLK and MCLK/10"},
	{"SourcePreview" : "fet120_flash_write.c",       "Description" : "Flash In-System Programming, Copy SegA to SegB"},
	{"SourcePreview" : "fet120_fll_01.c",            "Description" : "Basic Clock, Implement Auto RSEL SW FLL"},
	{"SourcePreview" : "fet120_fll_02.c",            "Description" : "Basic Clock, Implement Cont. SW FLL with Auto RSEL"},
	{"SourcePreview" : "fet120_hfxtal.c",            "Description" : "Basic Clock, MCLK Sourced from HF XTAL"},
	{"SourcePreview" : "fet120_lpm3.c",              "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_nmi.c",               "Description" : "Basic Clock, Configure RST/NMI as NMI"},
	{"SourcePreview" : "fet120_rosc.c",              "Description" : "DCOCLK Biased with External Resistor Rosc"},
	{"SourcePreview" : "fet120_spi0_016x.c",         "Description" : "USART0, SPI Interface with HC165/164 Shift Registers"},
	{"SourcePreview" : "fet120_spi0_mstr.c",         "Description" : "USART0, SPI 3-Wire Master"},
	{"SourcePreview" : "fet120_spi0_slav.c",         "Description" : "USART0, SPI 3-Wire Slave"},
	{"SourcePreview" : "fet120_ta_01.c",             "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_02.c",             "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_03.c",             "Description" : "Timer_A, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_04.c",             "Description" : "Timer_A, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_05.c",             "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_06.c",             "Description" : "Timer_A, Toggle P1.0, CCR1 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_07.c",             "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_08.c",             "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_09.c",             "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_ta_10.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_11.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_12.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_ta_13.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_14.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_15.c",             "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_ta_16.c",             "Description" : "Timer_A, PWM TA1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_17.c",             "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_18.c",             "Description" : "Timer_A, PWM TA1-2, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_ta_19.c",             "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "fet120_ta_20.c",             "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet120_ta_21.c",             "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_uart01_0115k.c",      "Description" : "USART0, UART 115200 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_uart01_02400.c",      "Description" : "USART0, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_uart01_09600.c",      "Description" : "USART0, UART 9600 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_uart01_19200.c",      "Description" : "USART0, UART 19200 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet120_uart02_09600.c",      "Description" : "USART0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_uart02_19200.c",      "Description" : "USART0, Ultra-Low Pwr UART 19200 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_uart03_09600.c",      "Description" : "USART0, UART 9600 Echo ISR, 32kHz ACLK + DCO"},
	{"SourcePreview" : "fet120_uart03_19200.c",      "Description" : "USART0, UART 19200 Echo ISR, 32kHz ACLK + DCO"},
	{"SourcePreview" : "fet120_uart04_09600.c",      "Description" : "USART0, UART 9600 Echo ISR, No XTAL, Rosc DCO Only"},
	{"SourcePreview" : "fet120_uart04_19200.c",      "Description" : "USART0, UART 19200 Echo ISR, No XTAL, Rosc DCO Only"},
	{"SourcePreview" : "fet120_uart05_09600.c",      "Description" : "USART0, Ultra-Low Pwr 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_uart06_09600.c",      "Description" : "USART0, Ultra-Low Pwr UART 9600 String, 32kHz ACLK"},
	{"SourcePreview" : "fet120_wdt_01.c",            "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet120_wdt_02.c",            "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet120_wdt_03.c",            "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, HF XTAL ACLK"}
];

