var jsonObjASM = [
	{"SourcePreview" : "msp430x47x_1.asm",                         "Description" : "Toggle P4.6 in software"},
	{"SourcePreview" : "msp430x47x_bt_01.asm",                     "Description" : "Basic Timer, Toggle P4.6 Inside ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_bt_02.asm",                     "Description" : "Basic Timer, Toggle P4.6 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_clks_03.asm",                   "Description" : "FLL+, Output 32kHz XTAL + HF XTAL + Internal DCO"},
	{"SourcePreview" : "msp430x47x_compA_01.asm",                  "Description" : "Comparator_A, Poll input CA0, result in P4.6"},
	{"SourcePreview" : "msp430x47x_compA_02.asm",                  "Description" : "Comparator_A, Poll input CA0, CA exchange, result in P4.6"},
	{"SourcePreview" : "msp430x47x_compA_04.asm",                  "Description" : "Comparator_A, Poll input CA0, result in P4.6"},
	{"SourcePreview" : "msp430x47x_compA_05.asm",                  "Description" : "Comparator_A, Poll input CA0, interrupt triggered"},
	{"SourcePreview" : "msp430x47x_dac12_01.asm",                  "Description" : "DAC12_0, Output 1V on DAC0"},
	{"SourcePreview" : "msp430x47x_dac12_02.asm",                  "Description" : "DAC12_0, Output 2V on DAC1"},
	{"SourcePreview" : "msp430x47x_dac12_03.asm",                  "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "msp430x47x_dac12_05.asm",                  "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "msp430x47x_flashwrite_01.asm",             "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x47x_flashwrite_03.asm",             "Description" : "Flash In-System Programming w/ EEI, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x47x_flashwrite_04.asm",             "Description" : "Flash In-System Programming w/ EEI, Copy SegD to A/B/C"},
	{"SourcePreview" : "msp430x47x_fll_01.asm",                    "Description" : "FLL+, Runs Internal DCO at 2.5MHz"},
	{"SourcePreview" : "msp430x47x_fll_02.asm",                    "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "msp430x47x_LFxtal_nmi.asm",                "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x47x_lpm3.asm",                      "Description" : "FLL+, LPM3 Using Basic Timer ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_oa_02.asm",                     "Description" : "OA0,Comparator in General-Purpose Mode"},
	{"SourcePreview" : "msp430x47x_oa_03.asm",                     "Description" : "OA0,General-Purpose Mode"},
	{"SourcePreview" : "msp430x47x_oa_06.asm",                     "Description" : "OA0,Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430x47x_oa_11.asm",                     "Description" : "OA1,Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430x47x_sd16a_03.asm",                  "Description" : "SD16_A, Continuous Conversion on a Single Channel"},
	{"SourcePreview" : "msp430x47x_sd16a_04.asm",                  "Description" : "SD16_A, Single Conversion on Single Channel Polling IFG"},
	{"SourcePreview" : "msp430x47x_sd16a_05.asm",                  "Description" : "SD16_A, Single Conversion on a Single Channel Using ISR"},
	{"SourcePreview" : "msp430x47x_sd16a_07.asm",                  "Description" : "SD16, Single Conversion on a Single Channel Using ISR"},
	{"SourcePreview" : "msp430x47x_sd16a_08.asm",                  "Description" : "SD16_A, Single Conversion on a Channel using buffered input"},
	{"SourcePreview" : "msp430x47x_sd16a_09.asm",                  "Description" : "SD16_A, Single Conversion on a Single Channel Using ISR"},
	{"SourcePreview" : "msp430x47x_sd16a_10.asm",                  "Description" : "SD16_A, Single Conversion on a Single Channel Using ISR 1024 Extended Oversampling Rate"},
	{"SourcePreview" : "msp430x47x_sd16a_11.asm",                  "Description" : "SD16_A, Single Conversion on a Single Channel Using ISR ACLK input to SD16_A"},
	{"SourcePreview" : "msp430x47x_sd16a_12.asm",                  "Description" : "SD16_A, Single Conversion on a Single Channel Using ISR SMCLK input is divided by 32"},
	{"SourcePreview" : "msp430x47x_svs_01.asm",                    "Description" : "SVS, POR @ 2.5V Vcc"},
	{"SourcePreview" : "msp430x47x_svs_03.asm",                    "Description" : "SVM, Toggle port 4.6 on Vcc < 2.8V"},
	{"SourcePreview" : "msp430x47x_ta_01.asm",                     "Description" : "Timer_A, Toggle P4.6, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_ta_02.asm",                     "Description" : "Timer_A, Toggle P4.6, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_ta_03.asm",                     "Description" : "Timer_A, Toggle P4.6, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_ta_04.asm",                     "Description" : "Timer_A, Toggle P4.6, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_ta_05.asm",                     "Description" : "Timer_A, Toggle P4.6, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_ta_16.asm",                     "Description" : "Timer_A, Timer_A, PWM TA1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_ta_17.asm",                     "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_tb_01.asm",                     "Description" : "Timer_B, Toggle P4.6, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_tb_02.asm",                     "Description" : "Timer_B, Toggle P4.6, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_tb_03.asm",                     "Description" : "Timer_B, Toggle P4.6, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_tb_04.asm",                     "Description" : "Timer_B, Toggle P4.6, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_tb_05.asm",                     "Description" : "Timer_B, Toggle P4.6, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_tb_10.asm",                     "Description" : "Timer_B, PWM TB1 -2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_tb_11.asm",                     "Description" : "Timer_B, PWM TB1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_uscia0_duplex_9600.asm",        "Description" : "USCI_A0, UART 9600 Full-Duplex Transceiver, 32K ACLK"},
	{"SourcePreview" : "msp430x47x_uscia0_irda_01.asm",            "Description" : "USCI_A0 IrDA External Loopback Test, 4MHz SMCLK"},
	{"SourcePreview" : "msp430x47x_uscia0_spi_09.asm",             "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x47x_uscia0_spi_10.asm",             "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x47x_uscia0_uart_115k.asm",          "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x47x_uscia0_uart_115k_lpm.asm",      "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK, LPM3"},
	{"SourcePreview" : "msp430x47x_uscia0_uart_9600.asm",          "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x47x_uscib0_i2c_02.asm",             "Description" : "USCI_B0 I2C Master Interface to PCF8574, Read/Write"},
	{"SourcePreview" : "msp430x47x_uscib0_i2c_08.asm",             "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x47x_uscib0_i2c_09.asm",             "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x47x_uscib0_i2c_10.asm",             "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x47x_uscib0_i2c_11.asm",             "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "",                                         "Description" : ""},
	{"SourcePreview" : "",                                         "Description" : ""}
];

