var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430FG43x",
		"Filter" : "MSP430FG43\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "fet430_1.c",                 "Description" : "Software Toggle P5.1"},
	{"SourcePreview" : "fet430_adc12_01.c",          "Description" : "ADC12, Sample A0, Set P5.1 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "fet430_adc12_02.c",          "Description" : "ADC12, Single Conversion on Single Channel"},
	{"SourcePreview" : "fet430_adc12_03.c",          "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "fet430_adc12_04.c",          "Description" : "ADC12, Extend Sampling period with SHT Bits"},
	{"SourcePreview" : "fet430_adc12_05.c",          "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "fet430_adc12_06.c",          "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "fet430_adc12_07.c",          "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "fet430_adc12_08.c",          "Description" : "ADC12, Using 10 External Channels for Conversion"},
	{"SourcePreview" : "fet430_adc12_09.c",          "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "fet430_adc12_10.c",          "Description" : "ADC12, Using the Temperature Sensor"},
	{"SourcePreview" : "fet430_adc12_11.c",          "Description" : "ADC12, Single Conversion on Channel A12"},
	{"SourcePreview" : "fet430_adc12_12.c",          "Description" : "ADC12, Single Conversion on Channel A13"},
	{"SourcePreview" : "fet430_adc12_13.c",          "Description" : "ADC12, Single Conversion on Channel A14"},
	{"SourcePreview" : "fet430_adc12_14.c",          "Description" : "ADC12, Single Conversion on Channel A15"},
	{"SourcePreview" : "fet430_bt_01.c",             "Description" : "Basic Timer, Toggle P5.1 Inside ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_bt_02.c",             "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_clks_02.c",           "Description" : "FLL+, Output 32kHz XTAL + HF XTAL + Internal DCO"},
	{"SourcePreview" : "fet430_dac12_01.c",          "Description" : "DAC12_0, Output 1V on DAC0"},
	{"SourcePreview" : "fet430_dac12_02.c",          "Description" : "DAC12_1, Output 2V on DAC1"},
	{"SourcePreview" : "fet430_dac12_03.c",          "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "fet430_dac12_04.c",          "Description" : "DAC12_0, Output Voltage Ramp on VeREF+"},
	{"SourcePreview" : "fet430_dac12_05.c",          "Description" : "DAC0 Output Voltage Ramp, DAC1 Constant, DAC ISR"},
	{"SourcePreview" : "fet430_dma_01.c",            "Description" : "DMA0, Repeated Burst to-from RAM, Software Trigger"},
	{"SourcePreview" : "fet430_dma_02.c",            "Description" : "DMA0, Repeated Block To P5OUT, TACCR2, DCO"},
	{"SourcePreview" : "fet430_dma_03.c",            "Description" : "DMA0, Repeat Single to UART 19200, TACCR2, DCO"},
	{"SourcePreview" : "fet430_dma_04.c",            "Description" : "DMA0, Repeated Block to DAC0 Sine Output, TACCR1, DCO"},
	{"SourcePreview" : "fet430_dma_05.c",            "Description" : "DMA0, Rpt'd Blk to DAC1 8-bit Sine Output, TBCCR2, DCO"},
	{"SourcePreview" : "fet430_dma_06.c",            "Description" : "DMA0, ADC12 A10 Block Xfer to RAM, Timer_B, SMCLK"},
	{"SourcePreview" : "fet430_dma_07.c",            "Description" : "DMA0, ADC12 A10 Block Xfer to Flash, Timer_B, SMCLK"},
	{"SourcePreview" : "fet430_fll_01.c",            "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "fet430_fll_02.c",            "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "fet430_lcd_01.c",            "Description" : "LCD, Display \"0123456\" on SBLCDA4 LCD"},
	{"SourcePreview" : "fet430_lcd_02.c",            "Description" : "LCD, Display \"430\" on Varitronix VI-322 LCD"},
	{"SourcePreview" : "fet430_lpm3.c",              "Description" : "FLL+, LPM3 Using Basic Timer ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_oa_01.c",             "Description" : "OA0, Comparator Mode"},
	{"SourcePreview" : "fet430_oa_02.c",             "Description" : "OA0, Comparator in General-Purpose Mode"},
	{"SourcePreview" : "fet430_oa_03.c",             "Description" : "OA0, General-Purpose Mode"},
	{"SourcePreview" : "fet430_oa_04.c",             "Description" : "OA0, Inverting PGA Mode"},
	{"SourcePreview" : "fet430_oa_05.c",             "Description" : "OA0, Non-Inverting PGA Mode"},
	{"SourcePreview" : "fet430_oa_06.c",             "Description" : "OA0, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "fet430_oa_07.c",             "Description" : "OA1, Comparator Mode"},
	{"SourcePreview" : "fet430_oa_08.c",             "Description" : "OA1, Comparator in General-Purpose Mode"},
	{"SourcePreview" : "fet430_oa_09.c",             "Description" : "OA1, Inverting PGA Mode"},
	{"SourcePreview" : "fet430_oa_10.c",             "Description" : "OA1, Non-Inverting PGA Mode"},
	{"SourcePreview" : "fet430_oa_11.c",             "Description" : "OA1, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "fet430_spi0_016x.c",         "Description" : "USART0, SPI Interface to HC165/164 Shift Registers"},
	{"SourcePreview" : "fet430_ta_01.c",             "Description" : "Timer_A, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_ta_02.c",             "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_ta_03.c",             "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_ta_04.c",             "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_ta_05.c",             "Description" : "Timer_A, Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_ta_16.c",             "Description" : "Timer_A, PWM TA1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet430_ta_17.c",             "Description" : "Timer_A, PWM TA1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet430_tb_01.c",             "Description" : "Timer_B, Toggle P5.1, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_tb_02.c",             "Description" : "Timer_B, Toggle P5.1, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_tb_03.c",             "Description" : "Timer_B, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_tb_04.c",             "Description" : "Timer_B, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_tb_05.c",             "Description" : "Timer_B, Toggle P5.1, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_tb_10.c",             "Description" : "Timer_B, PWM TB1-2 Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet430_tb_11.c",             "Description" : "Timer_B, PWM TB1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet430_uart01_0115k.c",      "Description" : "USART0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_uart01_02400.c",      "Description" : "USART0, 2400 UART Ultra-low Pwr Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_uart01_09600.c",      "Description" : "USART0, 9600 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_uart01_19200.c",      "Description" : "USART0, 19200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_uart02_19200.c",      "Description" : "USART0, 19200 UART Ultra-low Pwr Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet430_wdt_01.c",            "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet430_wdt_02.c",            "Description" : "WDT, Toggle P5.1, Interval Overflow ISR, 32kHz ACLK"}
];

