var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F161x",
		"Filter" : "MSP430F161\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "fet140_1.c",                     "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "fet140_adc12_01.c",              "Description" : "ADC12, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "fet140_adc12_02.c",              "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "fet140_adc12_03.c",              "Description" : "ADC12, Sample A10 Temp, Set P1.0 if Temp ++ ~2C"},
	{"SourcePreview" : "fet140_adc12_04.c",              "Description" : "ADC12, Extend Sampling Period with SHT Bits"},
	{"SourcePreview" : "fet140_adc12_05.c",              "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "fet140_adc12_06.c",              "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "fet140_adc12_07.c",              "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "fet140_adc12_08.c",              "Description" : "ADC12, Using 10 External Channels for Conversion"},
	{"SourcePreview" : "fet140_adc12_09.c",              "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "fet140_adc12_10.c",              "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "fet140_adc12_11.c",              "Description" : "ADC12, Single Channel Rpt Mode, TA1 as Sample Trigger"},
	{"SourcePreview" : "fet140_clks.c",                  "Description" : "Basic Clock, Output Buffered SMCLK, ACLK and MCLK"},
	{"SourcePreview" : "fet140_dac12_01.c",              "Description" : "DAC12_0, Output 1.0V on DAC0"},
	{"SourcePreview" : "fet140_dac12_02.c",              "Description" : "DAC12_1, Output 2.0V on DAC1"},
	{"SourcePreview" : "fet140_dac12_03.c",              "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "fet140_dma_01.c",                "Description" : "DMA0, Repeated Burst to-from RAM, Software Trigger"},
	{"SourcePreview" : "fet140_dma_02.c",                "Description" : "DMA0, Repeated Block To P1OUT, TACCR2, DCO"},
	{"SourcePreview" : "fet140_dma_03.c",                "Description" : "DMA0, Repeated Block UART1 9600, TACCR2, ACLK"},
	{"SourcePreview" : "fet140_dma_04.c",                "Description" : "DMA0, Block Mode UART1 9600, 32kHz ACLK"},
	{"SourcePreview" : "fet140_dma_05.c",                "Description" : "DMA0, Rpt'd Blk to DAC0, Sine Output, TACCR1, DCO"},
	{"SourcePreview" : "fet140_dma_06.c",                "Description" : "DMA2, Rpt'd Blk to DAC1, 8-Bit Sine, TBCCR2, DCO"},
	{"SourcePreview" : "fet140_dma_07.c",                "Description" : "DMA0/1, Rpt'd Blk to DAC0/1, Sin/Cos, TACCR1, XT2"},
	{"SourcePreview" : "fet140_dma_08.c",                "Description" : "DMA0, Rpt'd Blk, I2C Master Interface to DAC8571"},
	{"SourcePreview" : "fet140_dma_09.c",                "Description" : "DMA0, ADC12 A10 Block Xfer to RAM, TBCCR1, DCO"},
	{"SourcePreview" : "fet140_dma_10.c",                "Description" : "DMA0, ADC12 A10 Block Xfer to Flash, TBCCR1, DCO"},
	{"SourcePreview" : "fet140_dma_11.c",                "Description" : "DMA0/1, ADC12 A10 Block Xfer to MPY/RAM, TBCCR1, DCO"},
	{"SourcePreview" : "fet140_dma_12.c",                "Description" : "DMA1/0, Blk Mode UART1 9600 Auto RX/TX String, ACLK"},
	{"SourcePreview" : "fet140_dma_13.c",                "Description" : "DMA0/1/2, USART0 UART 9600 Full-Duplex Transcvr, ACLK"},
	{"SourcePreview" : "fet140_dma_14.c",                "Description" : "DMA0/1/2, USART0 SPI 3-Wire SPI Master P1.x Exchange"},
	{"SourcePreview" : "fet140_dma_15.c",                "Description" : "DMA0/1/2, USART0 SPI 3-Wire SPI Slave P1.x Exchange"},
	{"SourcePreview" : "fet140_dma_16.c",                "Description" : "DMA0/1/2, USART1 SPI 3-Wire Master P1.x Exchange"},
	{"SourcePreview" : "fet140_flashwrite_01.c",         "Description" : "Flash In-System Programming, Copy SegA to SegB"},
	{"SourcePreview" : "fet140_fll_01.c",                "Description" : "Basic Clock, Implement Auto RSEL SW FLL"},
	{"SourcePreview" : "fet140_fll_02.c",                "Description" : "Basic Clock, Implement Cont. SW FLL with Auto RSEL"},
	{"SourcePreview" : "fet140_hfxt2.c",                 "Description" : "Basic Clock, MCLK Sourced from HF XTAL XT2"},
	{"SourcePreview" : "fet140_hfxtal.c",                "Description" : "Basic Clock, MCLK Sourced from HF XTAL"},
	{"SourcePreview" : "fet140_i2c_01.c",                "Description" : "I2C, Master Intf. to TMP100, Set P1.0 if Temp > 28C"},
	{"SourcePreview" : "fet140_i2c_02.c",                "Description" : "I2C, Master Interface to PCF8574, Read/Write"},
	{"SourcePreview" : "fet140_i2c_03.c",                "Description" : "I2C, Master Interface to DAC8571 in Repeat Mode"},
	{"SourcePreview" : "fet140_i2c_04.c",                "Description" : "I2C, Master Reads from MSP430 Slave"},
	{"SourcePreview" : "fet140_i2c_05.c",                "Description" : "I2C, Slave Transmits to MSP430 Master"},
	{"SourcePreview" : "fet140_i2c_06.c",                "Description" : "I2C, Master Transmits to MSP430 Slave RX"},
	{"SourcePreview" : "fet140_i2c_07.c",                "Description" : "I2C, Slave Reads from MSP430 Master"},
	{"SourcePreview" : "fet140_i2c_08.c",                "Description" : "I2C, Master Writes Multiple Bytes to MSP430 Slave"},
	{"SourcePreview" : "fet140_i2c_09.c",                "Description" : "I2C, Master Reads from MSP430 Slave in Repeat Mode"},
	{"SourcePreview" : "fet140_i2c_10.c",                "Description" : "I2C, Slave Writes to MSP430 Master RX in Repeat Mode"},
	{"SourcePreview" : "fet140_i2c_12.c",                "Description" : "I2C, Master Interface to DAC8571, Write"},
	{"SourcePreview" : "fet140_i2c_13.c",                "Description" : "I2C, Master Interface to DAC8571, Read/Write"},
	{"SourcePreview" : "fet140_i2c_14.c",                "Description" : "Switch Between UART0 & Master I2C Transmitter"},
	{"SourcePreview" : "fet140_i2c_15.c",                "Description" : "I2C, Slave TMP100 Emulation II"},
	{"SourcePreview" : "fet140_i2c_16.c",                "Description" : "I2C, Master Writes/Reads with Slave, Rptd Start"},
	{"SourcePreview" : "fet140_i2c_17.c",                "Description" : "I2C, Slave Reads/Writes with Master, Rptd Start"},
	{"SourcePreview" : "fet140_lpm3.c",                  "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_nmi.c",                   "Description" : "Basic Clock, Configure RST/NMI as NMI"},
	{"SourcePreview" : "fet140_rosc.c",                  "Description" : "DCOCLK Biased with External Resistor Rosc"},
	{"SourcePreview" : "fet140_spi0_03.c",               "Description" : "USART0, SPI Interface to HC165/164 Shift Registers"},
	{"SourcePreview" : "fet140_spi0_04.c",               "Description" : "USART0, SPI Interface to TLV5616 DAC"},
	{"SourcePreview" : "fet140_spi0_05.c",               "Description" : "USART0, SPI 3-Wire Master"},
	{"SourcePreview" : "fet140_spi0_06.c",               "Description" : "USART0, SPI 3-Wire Slave"},
	{"SourcePreview" : "fet140_spi0_07.c",               "Description" : "USART0, SPI Full-Duplex 3-Wire Master P1.x Exchange"},
	{"SourcePreview" : "fet140_spi0_08.c",               "Description" : "USART0, SPI Full-Duplex 3-Wire Slave P1.x Exchange"},
	{"SourcePreview" : "fet140_spi1_03.c",               "Description" : "USART1, SPI Interface to TLV5616 DAC"},
	{"SourcePreview" : "fet140_spi1_04.c",               "Description" : "USART1, SPI Full-Duplex 3-Wire Master P1.x Exchange"},
	{"SourcePreview" : "fet140_svs_01.c",                "Description" : "SVS, POR @ 2.5V Vcc"},
	{"SourcePreview" : "fet140_ta0_ta1_uart2400.c",      "Description" : "Timer_A software UART 2400 Echo using CCR0 and CCR1, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_01.c",                 "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_02.c",                 "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_03.c",                 "Description" : "Timer_A, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_04.c",                 "Description" : "Timer_A, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_05.c",                 "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_06.c",                 "Description" : "Timer_A, Toggle P1.0, CCR1 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_07.c",                 "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_08.c",                 "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_09.c",                 "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_10.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_11.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_12.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_13.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_14.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_15.c",                 "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_16.c",                 "Description" : "Timer_A, PWM TA1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_17.c",                 "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_18.c",                 "Description" : "Timer_A, PWM TA1-2, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_19.c",                 "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_ta_20.c",                 "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_ta_21.c",                 "Description" : "Timer_A, PWM TA1-2, Up/Down mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_22.c",                 "Description" : "Timer_A0, Capture of ACLK/8 using SMCLK"},
	{"SourcePreview" : "fet140_ta_23.c",                 "Description" : "Timer_A, Toggle P1.0, Overflow ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_ta_24.c",                 "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz INCLK"},
	{"SourcePreview" : "fet140_tb_01.c",                 "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_tb_02.c",                 "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_tb_03.c",                 "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_tb_04.c",                 "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_tb_05.c",                 "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_tb_06.c",                 "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_tb_07.c",                 "Description" : "Timer_B, PWM TB1-6, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_tb_08.c",                 "Description" : "Timer_B, PWM TB1-2, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_tb_09.c",                 "Description" : "Timer_B, PWM TB1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "fet140_tb_10.c",                 "Description" : "Timer_B, PWM TB1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "fet140_tb_11.c",                 "Description" : "Timer_B, PWM TB1-2, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart01_0115k.c",          "Description" : "USART0, UART 115200 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart01_0115k_2.c",        "Description" : "USART0, UART 115200 Echo ISR, XT2 HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart01_02400.c",          "Description" : "USART0, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart01_09600.c",          "Description" : "USART0, UART 9600 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart01_09600_2.c",        "Description" : "USART0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart01_19200.c",          "Description" : "USART0, UART 19200 Echo ISR, HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart01_19200_2.c",        "Description" : "USART0, UART 19200 Echo ISR, XT2 HF XTAL ACLK"},
	{"SourcePreview" : "fet140_uart02_09600.c",          "Description" : "USART0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart02_19200.c",          "Description" : "USART0, Ultra-Low Pwr UART 19200 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart03_09600.c",          "Description" : "USART0, UART 9600 Echo ISR, 32kHz ACLK + DCO"},
	{"SourcePreview" : "fet140_uart03_19200.c",          "Description" : "USART0, UART 19200 Echo ISR, 32kHz ACLK + DCO"},
	{"SourcePreview" : "fet140_uart04_09600.c",          "Description" : "USART0, UART 9600 Echo ISR, No XTAL, Rosc DCO Only"},
	{"SourcePreview" : "fet140_uart04_19200.c",          "Description" : "USART0, UART 19200 Echo ISR, No XTAL, Rosc DCO Only"},
	{"SourcePreview" : "fet140_uart05_09600.c",          "Description" : "USART0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart06_09600.c",          "Description" : "USART0, Ultra-Low Pwr UART 9600 String, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart07_09600.c",          "Description" : "USART0, Ultra-Low Pwr UART 9600 RX/TX, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart08_09600.c",          "Description" : "USART0, UART 9600 Full-Duplex Transceiver, 32K ACLK"},
	{"SourcePreview" : "fet140_uart09_2400.c",           "Description" : "USART0, SPI/UART 2400 alternating transmission, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart11_0115k_2.c",        "Description" : "USART1, UART 115200 Echo ISR, XT2 HF XTAL SMCLK"},
	{"SourcePreview" : "fet140_uart11_02400.c",          "Description" : "USART1, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_uart11_19200_2.c",        "Description" : "USART1, UART 19200 Echo ISR, XT2 HF XTAL SMCLK"},
	{"SourcePreview" : "fet140_uart15_09600.c",          "Description" : "USART1, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_wdt_01.c",                "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "fet140_wdt_02.c",                "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "fet140_wdt_03.c",                "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, HF XTAL ACLK"}
];

