var jsonObjASM = [
	{"SourcePreview" : "msp430tch5e_1.asm",                  "Description" : "Comp_A, Output Reference Voltages on P1.1"},
	{"SourcePreview" : "msp430tch5e_1_vlo.asm",              "Description" : "Comp_A, Detect Threshold, Set P1.0 if P1.1 > 0.25*Vcc"},
	{"SourcePreview" : "msp430tch5e_adc10_01.asm",           "Description" : "Comp_A, Simple 2.2V Low Battery Detect"},
	{"SourcePreview" : "msp430tch5e_adc10_02.asm",           "Description" : "ADC10, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430tch5e_adc10_03.asm",           "Description" : "ADC10, Sample A1, 1.5V Ref, Set P1.0 if A1 > 0.2V"},
	{"SourcePreview" : "msp430tch5e_adc10_04.asm",           "Description" : "ADC10, ADC10, Sample A10 Temp, Set P1.0 if Temp ++ ~2C"},
	{"SourcePreview" : "msp430tch5e_adc10_05.asm",           "Description" : "ADC10, ADC10, Sample A1, Signed, Set P1.0 if A1 > 0.5*AVcc"},
	{"SourcePreview" : "msp430tch5e_adc10_06.asm",           "Description" : "ADC10, ADC10, Sample A11, Lo_Batt, Set P1.0 if AVcc < 2.3V"},
	{"SourcePreview" : "msp430tch5e_adc10_07.asm",           "Description" : "ADC10, ADC10, Output Internal Vref on P1.4 & ADCCLK on P1.3"},
	{"SourcePreview" : "msp430tch5e_adc10_08.asm",           "Description" : "ADC10, DTC Sample A1 32x, AVcc, Repeat Single, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_09.asm",           "Description" : "ADC10, ADC10, DTC Sample A1 32x, 1.5V, Repeat Single, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_10.asm",           "Description" : "ADC10, ADC10, DTC Sample A10 32x, 1.5V, Repeat Single, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_11.asm",           "Description" : "ADC10, ADC10, DTC Sample A3-01, AVcc, Single Sequence, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_12.asm",           "Description" : "ADC10, ADC10, Sample A1, 1.5V, TA1 Trig, Set P1.0 if > 0.5V"},
	{"SourcePreview" : "msp430tch5e_adc10_13.asm",           "Description" : "ADC10, Sample A7, 1.5V, TA1 Trig, Ultra-Low Pwr"},
	{"SourcePreview" : "msp430tch5e_adc10_14.asm",           "Description" : "ADC10, DTC Sample A1 32x, AVcc, TA0 Trig, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_16.asm",           "Description" : "ADC10, DTC Sample A1-0 16x, AVcc, Repeat Seq, DCO"},
	{"SourcePreview" : "msp430tch5e_adc10_temp.asm",         "Description" : "ADC10, ADC10, DTC Sample A0 -> TA1, AVcc, DCO"},
	{"SourcePreview" : "msp430tch5e_ca_01.asm",              "Description" : "ADC10, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "msp430tch5e_ca_02.asm",              "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430tch5e_ca_03.asm",              "Description" : "Software Toggle P1.0, MCLK = VLO/8"},
	{"SourcePreview" : "msp430tch5e_clks.asm",               "Description" : "Basic Clock, Output Buffered SMCLK, ACLK and MCLK/10"},
	{"SourcePreview" : "msp430tch5e_dco_flashcal.asm",       "Description" : "DCO Calibration Constants Programmer"},
	{"SourcePreview" : "msp430tch5e_flashwrite_01.asm",      "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430tch5e_lfxtal_nmi.asm",         "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430tch5e_lpm3.asm",               "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_lpm3_vlo.asm",           "Description" : "Basic Clock, LPM3 Using WDT ISR, VLO ACLK"},
	{"SourcePreview" : "msp430tch5e_nmi.asm",                "Description" : "Basic Clock, Configure RST/NMI as NMI"},
	{"SourcePreview" : "msp430tch5e_p1_01.asm",              "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "msp430tch5e_p1_02.asm",              "Description" : "Software Port Interrupt on P1.4 from LPM4"},
	{"SourcePreview" : "msp430tch5e_p1_03.asm",              "Description" : "Poll P1 With Software with Internal Pull-up"},
	{"SourcePreview" : "msp430tch5e_p1_04.asm",              "Description" : "P1 Interrupt from LPM4 with Internal Pull-up"},
	{"SourcePreview" : "msp430tch5e_ta_01.asm",              "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_02.asm",              "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_03.asm",              "Description" : "Timer_A, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_04.asm",              "Description" : "Timer_A, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_05.asm",              "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_06.asm",              "Description" : "Timer_A, Toggle P1.0, CCR1 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_07.asm",              "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_08.asm",              "Description" : "Timer_A, Toggle P1.0-2, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_10.asm",              "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_11.asm",              "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_13.asm",              "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_14.asm",              "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_16.asm",              "Description" : "Timer_A, PWM TA1, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_17.asm",              "Description" : "Timer_A, PWM TA1, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_19.asm",              "Description" : "Timer_A, PWM TA1, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_ta_20.asm",              "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_ta_uart2400.asm",        "Description" : "Timer_A, Ultra-Low Pwr UART 2400 Echo, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_wdt_01.asm",             "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_wdt_02.asm",             "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430tch5e_wdt_04.asm",             "Description" : "WDT+ Failsafe Clock, DCO SMCLK"},
	{"SourcePreview" : "msp430tch5e_wdt_05.asm",             "Description" : "Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430tch5e_wdt_06.asm",             "Description" : "WDT+ Failsafe Clock, 32kHz ACLK"}
];

