var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430FG662x",
		"Filter" : "MSP430FG662\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430fg662x_1.c",                                   "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430fg662x_compb_01.c",                            "Description" : "COMPB output Toggle in LPM4; Vcompare is compared against the internal 2.0V reference"},
	{"SourcePreview" : "msp430fg662x_compb_02.c",                            "Description" : "COMPB Toggle from LPM4; input channel CB1; Vcompare is compared against the internal reference 2.0V"},
	{"SourcePreview" : "msp430fg662x_compb_03.c",                            "Description" : "COMPB interrupt capability; Vcompare is compared against internal 1.5V reference"},
	{"SourcePreview" : "msp430fg662x_compb_04.c",                            "Description" : "COMPB Toggle from LPM4; CompB in ultra low power mode; Vcompare is compared against the Vcc*1/2"},
	{"SourcePreview" : "msp430fg662x_compb_05.c",                            "Description" : "COMPB Hysteresis, CBOUT Toggle in LPM4; High speed mode"},
	{"SourcePreview" : "msp430fg662x_crc16_01.c",                            "Description" : "CRC16, Compare CRC output with software-based algorithm"},
	{"SourcePreview" : "msp430fg662x_crc16_02.c",                            "Description" : "CRC16, fed by DMA, compare w/ software algorithm"},
	{"SourcePreview" : "msp430fg662x_ctsd16_03.c",                           "Description" : "CTSD16, Continuous Rail-to-Rail Conversion, Single Channel"},
	{"SourcePreview" : "msp430fg662x_ctsd16_04.c",                           "Description" : "CTSD16, Single Conversion on a Single Channel, Poll IFG"},
	{"SourcePreview" : "msp430fg662x_ctsd16_05.c",                           "Description" : "CTSD16, Single Conversion on a Single Channel, Use ISR"},
	{"SourcePreview" : "msp430fg662x_ctsd16_06.c",                           "Description" : "CTSD16, Using the Integrated Temperature Sensor, Ext. Res."},
	{"SourcePreview" : "msp430fg662x_ctsd16_07.c",                           "Description" : "CTSD16, Single Conversion of 3 Input Channels"},
	{"SourcePreview" : "msp430fg662x_dac12_1.c",                             "Description" : "DAC12_0, Output 1.5V on DAC0"},
	{"SourcePreview" : "msp430fg662x_dac12_2.c",                             "Description" : "DAC12_1, Output 0.75V on DAC1"},
	{"SourcePreview" : "msp430fg662x_dac12_3.c",                             "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "msp430fg662x_dma_01.c",                              "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "msp430fg662x_dma_02.c",                              "Description" : "DMA0, Repeated Block UCA1UART 9600, TACCR2, ACLK"},
	{"SourcePreview" : "msp430fg662x_flashwrite_01.c",                       "Description" : "Single-Byte Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430fg662x_flashwrite_02.c",                       "Description" : "Flash In-System Programming w/ Long-Word write at 0x1800"},
	{"SourcePreview" : "msp430fg662x_lpm0_01.c",                             "Description" : "Enters LPM0 with ACLK = LFXT1, REF0 disabled, VUSB LDO and SLDO disabled, SVS disabled"},
	{"SourcePreview" : "msp430fg662x_lpm35_rtc.c",                           "Description" : "RTC_B, LPM3.5, & alarm"},
	{"SourcePreview" : "msp430fg662x_lpm3_01.c",                             "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, VUSB LDO and SLDO disabled, SVS disabled"},
	{"SourcePreview" : "msp430fg662x_lpm3_02.c",                             "Description" : "Enters LPM3 with ACLK =REFO;  LFXT1 disabled, VUSB LDO and SLDO disabled"},
	{"SourcePreview" : "msp430fg662x_lpm3_03.c",                             "Description" : "Enters LPM3 with ACLK =VLO;  REFO,LFXT1 disabled, VUSB LDO and SLDO disabled"},
	{"SourcePreview" : "msp430fg662x_lpm4.c",                                "Description" : "Enters LPM4;  LFXT1, REF0 disabled, VUSB LDO and SLDO disabled, SVS disabled"},
	{"SourcePreview" : "msp430fg662x_lpm45_bakmem.c",                        "Description" : "LPM4.5, Backup RAM"},
	{"SourcePreview" : "msp430fg662x_mpy_01.c",                              "Description" : "16x16 Unsigned Multiply"},
	{"SourcePreview" : "msp430fg662x_mpy_10.c",                              "Description" : "32x32 Signed Multiply"},
	{"SourcePreview" : "msp430fg662x_mpy_11.c",                              "Description" : "32x32 Signed Multiply Accumalate"},
	{"SourcePreview" : "msp430fg662x_oa_02.c",                               "Description" : "OA0, Comparator in General-Purpose Mode"},
	{"SourcePreview" : "msp430fg662x_oa_03.c",                               "Description" : "OA0, General-Purpose Mode"},
	{"SourcePreview" : "msp430fg662x_oa_06.c",                               "Description" : "OA0, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430fg662x_oa_11.c",                               "Description" : "OA1, Unity-Gain Buffer Mode"},
	{"SourcePreview" : "msp430fg662x_portmap_01.c",                          "Description" : "Port Mapping Port2; Single runtime configuration"},
	{"SourcePreview" : "msp430fg662x_portmap_02.c",                          "Description" : "Port Mapping single function to multiple pins; Single runtime configuration. "},
	{"SourcePreview" : "msp430fg662x_portmap_03.c",                          "Description" : "Port Map single function to multiple pins; Multiple runtime configurations"},
	{"SourcePreview" : "msp430fg662x_rtc_01.c",                              "Description" : "RTC_B in real time clock mode"},
	{"SourcePreview" : "msp430fg662x_ta0_02.c",                              "Description" : "Timer0_A5, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta0_04.c",                              "Description" : "Timer0_A5, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta0_16.c",                              "Description" : "Timer0_A5, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta0_17.c",                              "Description" : "Timer0_A5, PWM TA1.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_01.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_02.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_03.c",                              "Description" : "Timer1_A3, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_04.c",                              "Description" : "Timer1_A3, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_05.c",                              "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_11.c",                              "Description" : "Timer1_A3, Toggle P3.1/TA1.0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_13.c",                              "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_14.c",                              "Description" : "Timer1_A3, Toggle P3.1/TA1.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_16.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_17.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta1_19.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta1_20.c",                              "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta2_01.c",                              "Description" : "Timer2_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta2_03.c",                              "Description" : "Timer2_A3, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ta2_08.c",                              "Description" : "Timer2_A3, Toggle P1.0;P2.3-5, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta2_14.c",                              "Description" : "Timer2_A3, Toggle P3.5/TA2.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_ta2_19.c",                              "Description" : "Timer2_A3, PWM TA2.1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_tb_01.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_tb_02.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_tb_03.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_tb_04.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_tb_05.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_tb_10.c",                               "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_ucs_03.c",                              "Description" : "Software Toggle P1.1 with 12MHz DCO"},
	{"SourcePreview" : "msp430fg662x_ucs_04.c",                              "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "msp430fg662x_ucs_05.c",                              "Description" : "VLO sources ACLK"},
	{"SourcePreview" : "msp430fg662x_ucs_06.c",                              "Description" : "XT1 sources ACLK"},
	{"SourcePreview" : "msp430fg662x_ucs_07.c",                              "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430fg662x_ucs_08.c",                              "Description" : "XT2 sources SMCLK"},
	{"SourcePreview" : "msp430fg662x_uscia0_spi_09.c",                       "Description" : "eUSCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fg662x_uscia0_spi_10.c",                       "Description" : "eUSCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fg662x_uscia0_uart_03.c",                      "Description" : "eUSCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_uscia0_uart_04.c",                      "Description" : "eUSCI_A0, 9600 UART, SMCLK, LPM0, Echo with over-sampling"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_06.c",                       "Description" : "eUSCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_07.c",                       "Description" : "eUSCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_08.c",                       "Description" : "eUSCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_09.c",                       "Description" : "eUSCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_10.c",                       "Description" : "eUSCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430fg662x_uscib0_i2c_11.c",                       "Description" : "eUSCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430fg662x_usci_i2c_standard_master.c",            "Description" : "eUSCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430fg662x_usci_i2c_standard_slave.c",             "Description" : "eUSCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430fg662x_usci_spi_standard_master.c",            "Description" : "eUSCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430fg662x_usci_spi_standard_slave.c",             "Description" : "eUSCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430fg662x_usci_uart_standard_transceiver.c",      "Description" : "eUSCI_A0, UART Echo received character"},
	{"SourcePreview" : "msp430fg662x_wdt_01.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_wdt_02.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fg662x_wdt_04.c",                              "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fg662x_wdt_05.c",                              "Description" : "Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430fg662x_wdt_06.c",                              "Description" : "WDT+ Failsafe Clock, 32kHz ACLK"}
];

