var jsonObjASM = [
	{"SourcePreview" : "msp430fr69xx_1.asm",                                  "Description" : "Blink LED"},
	{"SourcePreview" : "msp430fr69xx_active_01.asm",                          "Description" : "Active mode test"},
	{"SourcePreview" : "msp430fr69xx_adc12_01.asm",                           "Description" : "ADC12, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430fr69xx_adc12_03.asm",                           "Description" : "Sample A2-A3 Differential,Set P1.0 if i/p> 1V"},
	{"SourcePreview" : "msp430fr69xx_adc12_05.asm",                           "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "msp430fr69xx_adc12_21.asm",                           "Description" : "ADC12, Window Comparator, 2.5V ref"},
	{"SourcePreview" : "msp430fr69xx_compe_01.asm",                           "Description" : "COMPE output Toggle in LPM4; input channel CE1"},
	{"SourcePreview" : "msp430fr69xx_compe_05.asm",                           "Description" : "COMPE Hysteresis, COUT Toggle in LPM4; High speed mode"},
	{"SourcePreview" : "msp430fr69xx_crc.asm",                                "Description" : "Calculate CRC and compare"},
	{"SourcePreview" : "msp430fr69xx_cs_01.asm",                              "Description" : "Configure MCLK for 8MHz operation"},
	{"SourcePreview" : "msp430fr69xx_cs_03.asm",                              "Description" : "Output 32768Hz crystal on XT1 and observe failsafe"},
	{"SourcePreview" : "msp430fr69xx_dma_01.asm",                             "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "msp430fr69xx_euscia0_spi_09.asm",                     "Description" : "eUSCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr69xx_euscia0_spi_10.asm",                     "Description" : "eUSCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr69xx_euscia0_spi_11.asm",                     "Description" : "eUSCI_A0, SPI 4-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr69xx_euscia0_spi_12.asm",                     "Description" : "eUSCI_A0, SPI 4-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr69xx_euscia0_uart_01.asm",                    "Description" : "eUSCI_A0 UART echo at 9600 baud using BRCLK = 8MHz"},
	{"SourcePreview" : "msp430fr69xx_euscia0_uart_03.asm",                    "Description" : "USCI_A0 External Loopback test @ 115200 baud"},
	{"SourcePreview" : "msp430fr69xx_euscib0_i2c_10.asm",                     "Description" : "eUSCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430fr69xx_euscib0_i2c_11.asm",                     "Description" : "eUSCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430fr69xx_euscib0_i2c_master_multislave.asm",      "Description" : "eUSCI_B0 I2C Master TX bytes to Multiple Slaves"},
	{"SourcePreview" : "msp430fr69xx_euscib0_i2c_multislave.asm",             "Description" : "eUSCI_B0 I2C 4 Hardware I2C slaves"},
	{"SourcePreview" : "msp430fr69xx_framwrite.asm",                          "Description" : "Long word writes to FRAM"},
	{"SourcePreview" : "msp430fr69xx_lpm0.asm",                               "Description" : "Enters LPM0 with ACLK = LFXT, MCLK = 1MHz"},
	{"SourcePreview" : "msp430fr69xx_lpm3-5_01.asm",                          "Description" : "RTC_B, LPM3.5, & alarm"},
	{"SourcePreview" : "msp430fr69xx_lpm3_02.asm",                            "Description" : "Enters LPM3 with ACLK = VLO"},
	{"SourcePreview" : "msp430fr69xx_lpm4.asm",                               "Description" : "Enters LPM4"},
	{"SourcePreview" : "msp430fr69xx_mpu_01.asm",                             "Description" : "MPU write protection violation - interrupt"},
	{"SourcePreview" : "msp430fr69xx_p1_01.asm",                              "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "msp430fr69xx_ta0_01.asm",                             "Description" : "Timer0_A3, Toggle P1.0, CCR0 Cont Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_ta0_16.asm",                             "Description" : "Timer0_A3, PWM TA0.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_ta0_capture.asm",                        "Description" : "Timer0_A3 Capture of VLO Period using DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_ta1_05.asm",                             "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont Mode ISR, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr69xx_tb0_02.asm",                             "Description" : "TimerB, Toggle P1.0, CCR0 UP Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_wdt_01.asm",                             "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_wdt_04.asm",                             "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr69xx_wdt_05.asm",                             "Description" : "Reset on Invalid Address fetch, Toggle P1.0"}
];

