var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F541xA",
		"Filter" : "MSP430F541\\dA"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x54xA_1.c",                                   "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430x54xA_adc12_01.c",                            "Description" : "ADC12, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430x54xA_adc12_02.c",                            "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "msp430x54xA_adc12_05.c",                            "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "msp430x54xA_adc12_06.c",                            "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "msp430x54xA_adc12_07.c",                            "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "msp430x54xA_adc12_09.c",                            "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "msp430x54xA_adc12_10.c",                            "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "msp430x54xA_dma_01.c",                              "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "msp430x54xA_dma_02.c",                              "Description" : "DMA0, Single Transfer in Block Mode UART1 9600, ACLK"},
	{"SourcePreview" : "msp430x54xA_dma_03.c",                              "Description" : "SPI TX & RX using DMA0 & DMA1 Single Transfer in Fixed Address Mode"},
	{"SourcePreview" : "msp430x54xA_dma_04.c",                              "Description" : "DMA0, Single transfer using ADC12 triggered by TimerB"},
	{"SourcePreview" : "msp430x54xA_flashwrite_01.c",                       "Description" : "Single-Byte Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x54xA_flashwrite_02.c",                       "Description" : "Flash In-System Programming w/ Long-Word write at 0x1800"},
	{"SourcePreview" : "msp430x54xA_LPM3_1.c",                              "Description" : "Enters LPM3 (ACLK = LFXT1)"},
	{"SourcePreview" : "msp430x54xA_LPM3_2.c",                              "Description" : "Enters LPM3 (ACLK = VLO)"},
	{"SourcePreview" : "msp430x54xA_LPM4.c",                                "Description" : "Enters LPM4;  LFXT1, REF0 disabled, SVS disabled"},
	{"SourcePreview" : "msp430x54xA_OF_LFXT1_nmi.c",                        "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x54xA_P1_01.c",                               "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "msp430x54xA_P1_02.c",                               "Description" : "Software Port Interrupt Service on P1.4 from LPM4 with Internal Pull-up Resistance Enabled"},
	{"SourcePreview" : "msp430x54xA_P1_05.c",                               "Description" : "Write a byte to Port 1"},
	{"SourcePreview" : "msp430x54xA_PA_05.c",                               "Description" : "Write a Word to Port A (Port1+Port2)"},
	{"SourcePreview" : "msp430x54xA_RTC_01.c",                              "Description" : "RTC in Counter Mode toggles P1.0 every 1s"},
	{"SourcePreview" : "msp430x54xA_RTC_02.c",                              "Description" : "RTC_A in real time clock mode"},
	{"SourcePreview" : "msp430x54xA_ta3_01.c",                              "Description" : "Timer_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_02.c",                              "Description" : "Timer_A3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_03.c",                              "Description" : "Timer_A3, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_04.c",                              "Description" : "Timer_A3, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_05.c",                              "Description" : "Timer_A3, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_08.c",                              "Description" : "Timer_A3, Toggle P1.0;P2.1-3, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_11.c",                              "Description" : "Timer_A3, Toggle P2.1/TA1.0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_13.c",                              "Description" : "Timer_A3, Toggle P2.1/TA1.0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_14.c",                              "Description" : "Timer_A3, Toggle P2.1/TA1.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_16.c",                              "Description" : "Timer_A3, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_17.c",                              "Description" : "Timer_A3, PWM TA1.1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_ta3_19.c",                              "Description" : "Timer_A3, PWM TA1.1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_ta3_20.c",                              "Description" : "Timer_A3, PWM TA1.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_tb_01.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_tb_02.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_tb_03.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_tb_04.c",                               "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_tb_05.c",                               "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_tb_10.c",                               "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_UCS_1.c",                               "Description" : "Software Toggle P1.0 at Default DCO"},
	{"SourcePreview" : "msp430x54xA_UCS_2.c",                               "Description" : "Software Toggle P1.0 with 8MHz DCO"},
	{"SourcePreview" : "msp430x54xA_UCS_3.c",                               "Description" : "Software Toggle P1.0 with 12MHz DCO"},
	{"SourcePreview" : "msp430x54xA_UCS_4.c",                               "Description" : "FLL+, Runs Internal DCO at 2.45MHz with LFXT1 as Ref"},
	{"SourcePreview" : "msp430x54xA_UCS_5.c",                               "Description" : "VLO sources ACLK"},
	{"SourcePreview" : "msp430x54xA_UCS_6.c",                               "Description" : "XT1 sources ACLK. Toggles P1.0"},
	{"SourcePreview" : "msp430x54xA_UCS_7.c",                               "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430x54xA_UCS_8.c",                               "Description" : "XT2 sources MCLK & SMCLK"},
	{"SourcePreview" : "msp430x54xA_UCS_9.c",                               "Description" : "LFXT1 HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430x54xA_uscia0_duplex_9600.c",                  "Description" : "USCI_A0, UART 9600 Full-Duplex Transceiver, 32K ACLK"},
	{"SourcePreview" : "msp430x54xA_uscia0_spi_09.c",                       "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x54xA_uscia0_spi_10.c",                       "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x54xA_uscia0_uart_01.c",                      "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_uscia0_uart_02.c",                      "Description" : "USCI_A0, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_uscia0_uart_03.c",                      "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_uscia0_uart_04.c",                      "Description" : "USCI_A0, 9600 UART, SMCLK, LPM0, Echo with over-sampling"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_04.c",                       "Description" : "USCI_B0 I2C Master RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_05.c",                       "Description" : "USCI_B0 I2C Slave TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_06.c",                       "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_07.c",                       "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_08.c",                       "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_09.c",                       "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_10.c",                       "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_11.c",                       "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_12.c",                       "Description" : "USCI B0 I2C Master TX/RX multiple bytes to/from MSP430 Slave Repeated Start"},
	{"SourcePreview" : "msp430x54xA_uscib0_i2c_13.c",                       "Description" : "USCI B0 I2C Slave RX/TX multiple bytes from/to MSP430 Master Repeated Start"},
	{"SourcePreview" : "msp430x54xA_usci_i2c_standard_master.c",            "Description" : "USCI_B0, I2C Master multiple byte TX/RX"},
	{"SourcePreview" : "msp430x54xA_usci_i2c_standard_slave.c",             "Description" : "USCI_B0, I2C Slave multiple byte TX/RX"},
	{"SourcePreview" : "msp430x54xA_usci_spi_standard_master.c",            "Description" : "USCI_A0, SPI 3-Wire Master multiple byte RX/TX"},
	{"SourcePreview" : "msp430x54xA_usci_spi_standard_slave.c",             "Description" : "USCI_A0, SPI 3-Wire Slave multiple byte RX/TX"},
	{"SourcePreview" : "msp430x54xA_usci_uart_standard_transceiver.c",      "Description" : "USCI_A0, UART Echo received character"},
	{"SourcePreview" : "msp430x54xA_wdt_01.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_wdt_02.c",                              "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x54xA_wdt_04.c",                              "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x54xA_wdt_05.c",                              "Description" : "Reset on Invalid Address fetch, Toggle P1.0"}
];

