/* --COPYRIGHT--,BSD
 * Copyright (c) 2016, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * --/COPYRIGHT--*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ti_msp430_usb_hiddemo_management_HidCommunicationManager */

#ifndef _Included_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
#define _Included_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_VENDOR
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_VENDOR 8263L
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_PRODUCT
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_USB_PRODUCT 769L
#undef com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_TI_EXAMPLE_REPORT_ID
#define com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_TI_EXAMPLE_REPORT_ID 63L
/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getNumberOfInterfaces
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getNumberOfInterfaces
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getSerialsForVidPid
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getSerialsForVidPid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    getInterfacesForVidPid
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_getInterfacesForVidPid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    connectDeviceNative
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_connectDeviceNative
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    disconnectDeviceNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_disconnectDeviceNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    sendDataNative
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_sendDataNative
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_ti_msp430_usb_hiddemo_management_HidCommunicationManager
 * Method:    receiveDataNative
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ti_msp430_usb_hiddemo_management_HidCommunicationManager_receiveDataNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
//Released_Version_5_20_06_02
