@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


"C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.0_0\common\bin\cspybat" "C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.0_0\430\bin\430proc.dll" "C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.0_0\430\bin\430fet.dll"  %1 --plugin "C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.0_0\430\bin\430bat.dll" --backend -B "--hardware_multiplier" "32" "--hwmult_type" "8" "-p" "C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.0_0\430\config\debugger\MSP430FR5969.ddf" "--core=430Xv2" "--data_model=small" "--iv_base" "0xFF90" "--energytrace" "-d" "fet" "--erase_main" "--derivative" "MSP430FR5969" "--protocol" "automatic" "--eem" "EMEX_SMALL_5XX" "--port" "Automatic" "--connection" "ti_usb" "--use_emulated_breakpoints" "--settlingtime=0" "--msp430_dll" "msp430.dll" "--vccDefault" "3.3" "--jstatebit" "31" "FRAM" "--jstatebit" "30" "MPY" "--jstatebit" "29" "WDT" "--jstatebit" "28" "RTC" "--jstatebit" "27" "ADC" "--jstatebit" "26" "REF" "--jstatebit" "25" "COMP" "--jstatebit" "24" "AES" "--jstatebit" "23" "eUSCI_A0" "--jstatebit" "22" "eUSCI_A1" "--jstatebit" "21" "eUSCI_B0" "--jstatebit" "20" "TB0" "--jstatebit" "19" "TA0" "--jstatebit" "18" "TA1" "--jstatebit" "17" "TA2" "--jstatebit" "16" "TA3" "--jstatebit" "8" "DMA" "--jtag_speed" "medium" "--memtype" "FR_MPU2" 


