var jsonObjASM = [
	{"SourcePreview" : "MSP430FR57xx_active_01.asm",                         "Description" : "Stay in active mode with MCLK = 8MHz (uses while loop)"},
	{"SourcePreview" : "MSP430FR57xx_active_02.asm",                         "Description" : "Stay in active mode with MCLK = 8MHz (uses active mode test)"},
	{"SourcePreview" : "MSP430FR57xx_adc10_01.asm",                          "Description" : "ADC10, Sample A1, AVcc Ref, Set P1.0 if A1 > 0.5*Avcc"},
	{"SourcePreview" : "MSP430FR57xx_adc10_02.asm",                          "Description" : "ADC10, Sample A1, 1.5V Shared Ref, Set P1.0 if A1 > 0.5V"},
	{"SourcePreview" : "MSP430FR57xx_adc10_21.asm",                          "Description" : "ADC10, Window Comparator, 2.5V ref, Timer trigger, DCO"},
	{"SourcePreview" : "MSP430FR57xx_CS_01.asm",                             "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "MSP430FR57xx_CS_02.asm",                             "Description" : "FRAM In-System Programming w/ Long-Word write "},
	{"SourcePreview" : "MSP430FR57xx_CS_03.asm",                             "Description" : "Enters LPM3 with ACLK = LFXT1"},
	{"SourcePreview" : "MSP430FR57xx_dma_01.asm",                            "Description" : "Enters LPM3 with ACLK = VLO "},
	{"SourcePreview" : "MSP430FR57xx_FRAMWrite.asm",                         "Description" : "Enters LPM4"},
	{"SourcePreview" : "MSP430FR57xx_LPM3_01.asm",                           "Description" : "MPU write protection violation - PUC"},
	{"SourcePreview" : "MSP430FR57xx_LPM3_02.asm",                           "Description" : "16x16 Unsigned Multiply"},
	{"SourcePreview" : "MSP430FR57xx_LPM4.asm",                              "Description" : "Software Port Interrupt Service on P1.4 from LPM4"},
	{"SourcePreview" : "MSP430FR57xx_MPU_02.asm",                            "Description" : "Timer0_A3, PWM TA0.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "MSP430FR57xx_MPY_01.asm",                            "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont Mode ISR, 32KHz ACLK "},
	{"SourcePreview" : "MSP430FR57xx_P1_03.asm",                             "Description" : "Timer1_A3, Toggle P1.0, CCR0 UP Mode ISR, 32KHz ACLK "},
	{"SourcePreview" : "MSP430FR57xx_ta0_17.asm",                            "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "MSP430FR57xx_ta1_05.asm",                            "Description" : "TimerB, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "MSP430FR57xx_ta1_06.asm",                            "Description" : "TimerB, Toggle P1.0, CCR0 UP Mode ISR, 32KHz ACLK "},
	{"SourcePreview" : "MSP430FR57xx_ta1_17.asm",                            "Description" : "TimerB, PWM TB0.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "MSP430FR57xx_tb0_04.asm",                            "Description" : "Configure MCLK for 8MHz operation"},
	{"SourcePreview" : "MSP430FR57xx_tb0_06.asm",                            "Description" : "Configure MCLK for 24MHz operation"},
	{"SourcePreview" : "MSP430FR57xx_tb0_17.asm",                            "Description" : "Output 32768Hz crystal on XT1 and observe failsafe"},
	{"SourcePreview" : "MSP430FR57xx_uscia0_spi_09.asm",                     "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "MSP430FR57xx_uscia0_spi_10.asm",                     "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "MSP430FR57xx_uscia0_uart04.asm",                     "Description" : "USCI_A0, 9600 UART external loopback"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_04.asm",                     "Description" : "USCI_B0 I2C Master RX single bytes to MSP430 Slave"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_05.asm",                     "Description" : "USCI_B0 I2C Slave TX single bytes from MSP430 Master"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_06.asm",                     "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_07.asm",                     "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_11.asm",                     "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_Master_MultiSlave.asm",      "Description" : "USCI_B0 Master TX to 4 unique slave addresses"},
	{"SourcePreview" : "MSP430FR57xx_uscib0_i2c_MultiSlave.asm",             "Description" : "USCI_B0 configured as 4 unique slave receviers."}
];

