Graphics_Display Struct Reference
Graphics_Display Struct Reference
Primitives_api
This structure defines the characteristics of a display driver.
#include <grlib.h>
Data Fields
int32_t size
The size of this structure.
void * displayData
A pointer to display driver-specific data.
uint16_t width
The width of this display.
uint16_t heigth
The height of this display.
void(* callPixelDraw)(void *displayData, int16_t x, int16_t y, uint16_t value)
A pointer to the function to draw a pixel on this display.
void(* callPixelDrawMultiple)(void *displayData, int16_t x, int16_t y, int16_t x0, int16_t count, int16_t bPP, const uint8_t *data, const uint32_t *pucPalette)
A pointer to the function to draw multiple pixels on this display.
void(* callLineDrawH)(void *displayData, int16_t x1, int16_t x2, int16_t y, uint16_t value)
A pointer to the function to draw a horizontal line on this display.
void(* callLineDrawV)(void *displayData, int16_t x, int16_t y1, int16_t y2, uint16_t value)
A pointer to the function to draw a vertical line on this display.
void(* callRectFill)(void *displayData, const Graphics_Rectangle *rect, uint16_t value)
A pointer to the function to draw a filled rectangle on this display.
uint32_t(* callColorTranslate)(void *displayData, uint32_t value)
A pointer to the function to translate 24-bit RGB colors to display-specific colors.
void(* callFlush)(void *displayData)
A pointer to the function to flush any cached drawing operations on this display.
void(* callClearDisplay)(void *displayData, uint16_t value)
A pointer to the function to clears Display. Contents of display buffer unmodified.
Detailed Description
This structure defines the characteristics of a display driver.
Field Documentation
int32_t Graphics_Display::size
The size of this structure.
void* Graphics_Display::displayData
A pointer to display driver-specific data.
Referenced by Graphics_clearDisplayOnDisplay(), Graphics_drawHorizontalLineOnDisplay(), Graphics_drawMultiplePixelsOnDisplay(), Graphics_drawPixelOnDisplay(), Graphics_drawVerticalLineOnDisplay(), Graphics_fillRectangleOnDisplay(), and Graphics_flushOnDisplay().
uint16_t Graphics_Display::width
The width of this display.
Referenced by Graphics_getDisplayWidth(), Graphics_getWidthOfDisplay(), and Graphics_initContext().
uint16_t Graphics_Display::heigth
The height of this display.
Referenced by Graphics_getDisplayHeight(), Graphics_getHeightOfDisplay(), and Graphics_initContext().
void(* Graphics_Display::callPixelDraw)(void *displayData, int16_t x, int16_t y, uint16_t value)
A pointer to the function to draw a pixel on this display.
Referenced by Graphics_drawPixelOnDisplay().
void(* Graphics_Display::callPixelDrawMultiple)(void *displayData, int16_t x, int16_t y, int16_t x0, int16_t count, int16_t bPP, const uint8_t *data, const uint32_t *pucPalette)
A pointer to the function to draw multiple pixels on this display.
Referenced by Graphics_drawMultiplePixelsOnDisplay().
void(* Graphics_Display::callLineDrawH)(void *displayData, int16_t x1, int16_t x2, int16_t y, uint16_t value)
A pointer to the function to draw a horizontal line on this display.
Referenced by Graphics_drawHorizontalLineOnDisplay().
void(* Graphics_Display::callLineDrawV)(void *displayData, int16_t x, int16_t y1, int16_t y2, uint16_t value)
A pointer to the function to draw a vertical line on this display.
Referenced by Graphics_drawVerticalLineOnDisplay().
void(* Graphics_Display::callRectFill)(void *displayData, const Graphics_Rectangle *rect, uint16_t value)
A pointer to the function to draw a filled rectangle on this display.
Referenced by Graphics_fillRectangleOnDisplay().
uint32_t(* Graphics_Display::callColorTranslate)(void *displayData, uint32_t value)
A pointer to the function to translate 24-bit RGB colors to display-specific colors.
Referenced by Graphics_translateColorOnDisplay().
void(* Graphics_Display::callFlush)(void *displayData)
A pointer to the function to flush any cached drawing operations on this display.
Referenced by Graphics_flushOnDisplay().
void(* Graphics_Display::callClearDisplay)(void *displayData, uint16_t value)
A pointer to the function to clears Display. Contents of display buffer unmodified.
Referenced by Graphics_clearDisplayOnDisplay().
The documentation for this struct was generated from the following file:
grlib.h
Copyright 2016, Texas Instruments Incorporated