/* --COPYRIGHT--,FRAM-Utilities
 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * This source code is part of FRAM Utilities for MSP430 FRAM Microcontrollers.
 * Visit http://www.ti.com/tool/msp-fram-utilities for software information and
 * download.
 * --/COPYRIGHT--*/
//******************************************************************************
//  rng_ex2_generate_csv - Generate random data to CSV file.
//
//  This example demonstrates how to generate random data and write it to a CSV
//  (comma-separated values) file. The generated CSV file can be used to analyze
//  the randomness of generated bytes. For example the data can be read and
//  plotted to a histogram in MATLAB with the following code:
// 
//  data = csvread('rng_data.csv',1,1);
//  hist(data);
// 
//  This example generates 2^14 random data bytes and takes approximately 4
//  minutes to write all values to the CSV file due to the limitations of file
//  IO on MSP devices (using the debug stack and breakpoints to read/write data
//  streams).
//
//  Brent Peterson, Caleb Overbay
//  Texas Instruments Inc.
//  November 2016
//******************************************************************************
#include <msp430.h>

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "rng.h"

// Length of random data to generate and write to CSV file
#define LENGTH              (1024L*RNG_KEYLEN)

#if defined (__TI_COMPILER_VERSION__)
#define CSV_PATH            "../rng_data.csv"
#else
#define CSV_PATH            "rng_data.csv"
#endif

// Storage for generated random data
uint8_t data[RNG_KEYLEN];

int main(void)
{
    FILE *fp;
    uint32_t i;
    uint32_t j;
    uint16_t len;

    // Stop watchdog timer
    WDTCTL = WDTPW | WDTHOLD;

    // Configure MPU with INFO memory as RW
    MPUCTL0 = MPUPW;
    MPUSAM |= MPUSEGIRE | MPUSEGIWE;
    MPUCTL0 = MPUPW | MPUENA;

    // Open CSV file and write header
    fp = fopen(CSV_PATH, "w");
    fprintf(fp, "count,data\n");

    // Generate random bytes in multiples of RNG_KEYLEN
    for (i = 0; i < LENGTH; i += RNG_KEYLEN) {
        // Generate random bytes
        len = rng_generateBytes(data, RNG_KEYLEN);
        if (len != RNG_KEYLEN) {
            break;
        }

        // Write bytes to CSV file
        for (j = 0; j < RNG_KEYLEN; j++) {
            fprintf(fp, "%ld,%d\n", i+j, data[j]);
        }
    }
    
    // Close CSV file
    fclose(fp);

    return(0);
}
