var jsonObjASM = [
	{"SourcePreview" : "msp430g2210_ca_02.asm",              "Description" : "Comp_A, Detect Threshold, Set P1.5 if P1.2/CA2 > 0.25*Vcc"},
	{"SourcePreview" : "msp430g2210_ca_03.asm",              "Description" : "Comp_A, Simple 2.2V Low Battery Detect"},
	{"SourcePreview" : "msp430g2210_ca_04.asm",              "Description" : "Comp_A, Detect Threshold, Set P1.2 if P1.5/CA5 > 0.25*Vcc"},
	{"SourcePreview" : "msp430g22x0_1.asm",                  "Description" : "Software Toggle P1.2"},
	{"SourcePreview" : "msp430g22x0_1_vlo.asm",              "Description" : "Software Toggle P1.2, MCLK = VLO/8"},
	{"SourcePreview" : "msp430g22x0_clks.asm",               "Description" : "Basic Clock, Output Buffered MCLK/10"},
	{"SourcePreview" : "msp430g22x0_dco_calib.asm",          "Description" : "Basic Clock, Output Buffered clocks with preloaded DCO calibration constants for BCSCTL1 and DCOCTL."},
	{"SourcePreview" : "msp430g22x0_flashwrite_01.asm",      "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430g22x0_lpm3_vlo.asm",           "Description" : "Basic Clock, LPM3 Using WDT ISR, VLO ACLK"},
	{"SourcePreview" : "msp430g22x0_nmi.asm",                "Description" : "Basic Clock, Configure RST/NMI as NMI"},
	{"SourcePreview" : "msp430g22x0_P1_01.asm",              "Description" : "Software Poll P1.5, Set P1.2 if P1.5 = 1"},
	{"SourcePreview" : "msp430g22x0_P1_02.asm",              "Description" : "Software Port Interrupt Service on P1.5 from LPM4"},
	{"SourcePreview" : "msp430g22x0_P1_03.asm",              "Description" : "Poll P1 With Software with Internal Pull-up"},
	{"SourcePreview" : "msp430g22x0_P1_04.asm",              "Description" : "P1 Interrupt from LPM4 with Internal Pull-up"},
	{"SourcePreview" : "msp430g22x0_ta_01.asm",              "Description" : "Timer_A, Toggle P1.2, TA0CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_02.asm",              "Description" : "Timer_A, Toggle P1.2, TA0CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_03.asm",              "Description" : "Timer_A, Toggle P1.2, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_06.asm",              "Description" : "Timer_A, Toggle P1.2, TA0CCR1 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_07.asm",              "Description" : "Timer_A, Toggle P1.5-6, Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_10.asm",              "Description" : "Timer_A, Toggle P1.5/TA0, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_13.asm",              "Description" : "Timer_A, Toggle P1.5/TA0_0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_16.asm",              "Description" : "Timer_A, PWM TA0_1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_ta_19.asm",              "Description" : "Timer_A, PWM TA0_1, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_wdt_01.asm",             "Description" : "WDT, Toggle P1.2, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_wdt_04.asm",             "Description" : "WDT+ Failsafe Clock, DCO SMCLK"},
	{"SourcePreview" : "msp430g22x0_wdt_05.asm",             "Description" : "Reset on Invalid Address fetch, Toggle P1.2"},
	{"SourcePreview" : "msp430g22x0_wdt_07.asm",             "Description" : "WDT+ periodic reset"}
];

