var jsonObjASM = [
	{"SourcePreview" : "msp430fr235x_1.asm",                    "Description" : "Toggle P1.0 using software"},
	{"SourcePreview" : "msp430fr235x_ADC12_01.asm",             "Description" : "ADC, Sample A1, AVcc Ref, Set P1.0 if A1 > 0.5*AVcc"},
	{"SourcePreview" : "msp430fr235x_ADC12_02.asm",             "Description" : "ADC, Sample A1, 1.5V Shared Ref, Set P1.0 if A1 > 0.5V"},
	{"SourcePreview" : "msp430fr235x_ADC12_10.asm",             "Description" : "ADC, Sample A2/A1/A0, internal 2V Ref"},
	{"SourcePreview" : "msp430fr235x_ADC12_11.asm",             "Description" : "ADC, Sample A1, 1.5V Ref, TB0.1 Trig, Set P1.0 if A1>0.5V"},
	{"SourcePreview" : "msp430fr235x_ADC12_21.asm",             "Description" : "ADC, Window Comparator, 2.5V ref, Timer trigger, DCO"},
	{"SourcePreview" : "msp430fr235x_CRC.asm",                  "Description" : "CRC16, Compare CRC output with software-based algorithm"},
	{"SourcePreview" : "msp430fr235x_CS_01.asm",                "Description" : "Configure MCLK for 8MHz sourced from DCO"},
	{"SourcePreview" : "msp430fr235x_CS_02.asm",                "Description" : "Configure MCLK for 8MHz and XT1 sourcing ACLK and FLLREF"},
	{"SourcePreview" : "msp430fr235x_CS_03.asm",                "Description" : "Configure MCLK for 16MHz operation, and REFO sourcing FLLREF and ACLK"},
	{"SourcePreview" : "msp430fr235x_CS_05.asm",                "Description" : "Configure MCLK for 16MHz operation, and XT1 sourcing FLLREF and ACLK"},
	{"SourcePreview" : "msp430fr235x_CS_06.asm",                "Description" : "Configure MCLK for 4MHz and XT1HF sourcing MCLK"},
	{"SourcePreview" : "msp430fr235x_CS_07.asm",                "Description" : "Configure MCLK for 1MHz operation, and REFO sourcing FLLREF and ACLK. Use DCO software trim to lock FLL."},
	{"SourcePreview" : "msp430fr235x_CS_08.asm",                "Description" : "Configure MCLK for 1MHz operation, low power REFO(LPREFO) sourcing FLLREF and ACLK. Use DCO software trim to lock FLL."},
	{"SourcePreview" : "msp430fr235x_CS_10.asm",                "Description" : "Configure MCLK for 24MHz operation, and XT1 sourcing FLLREF and ACLK"},
	{"SourcePreview" : "msp430fr235x_eCOMP_01.asm",             "Description" : "eCOMP Toggle from LPM3; eCOMP in ultra low power mode, Vcompare is compared against internal VREF."},
	{"SourcePreview" : "msp430fr235x_euscia0_spi_09.asm",       "Description" : "eUSCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr235x_euscia0_spi_10.asm",       "Description" : "eUSCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr235x_euscia0_spi_11.asm",       "Description" : "eUSCI_A0, SPI 4-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr235x_euscia0_spi_12.asm",       "Description" : "eUSCI_A0, SPI 4-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr235x_euscia0_uart_01.asm",      "Description" : "eUSCI_A0 UART echo at 9600 baud using BRCLK = 8MHz"},
	{"SourcePreview" : "msp430fr235x_euscia0_uart_03.asm",      "Description" : "eUSCI_A0 External Loopback test @ 115200 baud"},
	{"SourcePreview" : "msp430fr235x_euscia0_uart_05.asm",      "Description" : "eUSCI_A0 UART echo at 4800 baud using BRCLK = 32768Hz"},
	{"SourcePreview" : "msp430fr235x_framwrite.asm",            "Description" : "Long word writes to FRAM"},
	{"SourcePreview" : "msp430fr235x_LPM3_01.asm",              "Description" : "Enters LPM3 with ACLK = XT1CLK = 32768Hz"},
	{"SourcePreview" : "msp430fr235x_LPM3_03.asm",              "Description" : "Enters LPM3 with ACLK = VLO"},
	{"SourcePreview" : "msp430fr235x_P1_01.asm",                "Description" : "Software Poll P1.3, Set P1.0 if P1.3 = 1"},
	{"SourcePreview" : "msp430fr235x_P1_03.asm",                "Description" : "Software Port Interrupt Service on P1.3 from LPM3"},
	{"SourcePreview" : "msp430fr235x_tb0_01.asm",               "Description" : "Timer0_B3, Toggle P1.0, CCR0 Count Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_tb0_02.asm",               "Description" : "Timer0_B3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_tb0_04.asm",               "Description" : "Timer0_B3, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr235x_tb0_16.asm",               "Description" : "Timer0_B3, PWM TB0.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_tb0_17.asm",               "Description" : "Timer0_B3, PWM TB0.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr235x_tb0_20.asm",               "Description" : "Timer0_B3, PWM TB0.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr235x_tb0_22.asm",               "Description" : "Timer0_B3, Ultra-Low Power Pulse Accumulator"},
	{"SourcePreview" : "msp430fr235x_tb0_capture.asm",          "Description" : "Timer0_B3 Capture of ACLK"},
	{"SourcePreview" : "msp430fr235x_tb1_05.asm",               "Description" : "Timer1_B3, Toggle P1.0, CCR0 Cont Mode ISR, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr235x_tb1_06.asm",               "Description" : "Timer0_B3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_tb1_16.asm",               "Description" : "Timer1_B3, PWM TB1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_tb1_17.asm",               "Description" : "Timer1_B3, PWM TB1.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr235x_WDT_01.asm",               "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_WDT_02.asm",               "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr235x_WDT_04.asm",               "Description" : "WDT,  Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr235x_WDT_05.asm",               "Description" : "WDT,  Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430fr235x_WDT_06.asm",               "Description" : "WDT,  Failsafe Clock, WDT mode, 32kHz ACLK"}
];

