var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F21x1",
		"Filter" : "MSP430F21\\d1"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x11x1_1.c",                      "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430x11x1_549.c",                    "Description" : "Software SPI Interface TLC549, Set P1.0 if > 0.5*Vcc"},
	{"SourcePreview" : "msp430x11x1_ca_01.c",                  "Description" : "Comp_A, Output Reference Voltages on P2.3"},
	{"SourcePreview" : "msp430x11x1_ca_02.c",                  "Description" : "Comp_A, Detect Threshold, Set P1.0 if P2.3 > 0.25*Vcc"},
	{"SourcePreview" : "msp430x11x1_ca_03.c",                  "Description" : "Comp_A, Simple 2.2V Low Battery Detect"},
	{"SourcePreview" : "msp430x11x1_ca_04.c",                  "Description" : "Comp_A, Slope ADC to Detect Temp Lvl, Set P1.0 > 25C"},
	{"SourcePreview" : "msp430x11x1_clks.c",                   "Description" : "Basic Clock, Output Buffered SMCLK, ACLK and MCLK/10"},
	{"SourcePreview" : "msp430x11x1_flashwrite_01.c",          "Description" : "Flash In-System Programming, Copy SegA to SegB"},
	{"SourcePreview" : "msp430x11x1_fll_01.c",                 "Description" : "Basic Clock, Implement Auto RSEL SW FLL"},
	{"SourcePreview" : "msp430x11x1_fll_02.c",                 "Description" : "Basic Clock, Implement Cont. SW FLL with Auto RSEL"},
	{"SourcePreview" : "msp430x11x1_hfxtal.c",                 "Description" : "Basic Clock, MCLK Sourced from HF XTAL"},
	{"SourcePreview" : "msp430x11x1_lpm3.c",                   "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_nmi.c",                    "Description" : "Basic Clock, Configure RST/NMI as NMI"},
	{"SourcePreview" : "msp430x11x1_P2_int.c",                 "Description" : "Software Port Interrupt Service on P2.0 from LPM4"},
	{"SourcePreview" : "msp430x11x1_P2_poll.c",                "Description" : "Software Poll P2.0, Set P1.0 if P2.0 = 1"},
	{"SourcePreview" : "msp430x11x1_ta_01.c",                  "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_02.c",                  "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_03.c",                  "Description" : "Timer_A, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_04.c",                  "Description" : "Timer_A, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_05.c",                  "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_06.c",                  "Description" : "Timer_A, Toggle P1.0, CCR1 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_07.c",                  "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_08.c",                  "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_09.c",                  "Description" : "Timer_A, Toggle P1.0-3, Cont. Mode ISR, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_10.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_11.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_12.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_13.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_14.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_15.c",                  "Description" : "Timer_A, Toggle P1.1/TA0, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_16.c",                  "Description" : "Timer_A, PWM TA1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_17.c",                  "Description" : "Timer_A, PWM TA1-2, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_18.c",                  "Description" : "Timer_A, PWM TA1-2, Up Mode, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_19.c",                  "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_ta_20.c",                  "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_21.c",                  "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart115k.c",            "Description" : "Timer_A, UART 115200 Echo, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart19200_01.c",        "Description" : "Timer_A, UART 19200 Echo, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart2400.c",            "Description" : "Timer_A, Ultra-Low Pwr UART 2400 Echo, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart9600_01.c",         "Description" : "Timer_A, UART 9600 Echo, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart9600_02.c",         "Description" : "Timer_A, Ultra-Low Pwr UART 9600 Echo, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart9600_03.c",         "Description" : "Timer_A, UART 9600 Echo, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_ta_uart9600_05.c",         "Description" : "Timer_A, Ultra-Low Pwr UART 9600 String, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_wdt_01.c",                 "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x11x1_wdt_02.c",                 "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x11x1_wdt_03.c",                 "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, HF XTAL ACLK"},
	{"SourcePreview" : "msp430x21x1_2.c",                      "Description" : "Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430x21x1_ca_05.c",                  "Description" : "Comp_A, Millivolt Meter"},
	{"SourcePreview" : "msp430x21x1_ca_06.c",                  "Description" : "Comp_A, Slope ADC to measure temperature"},
	{"SourcePreview" : "msp430x21x1_ca_CASHORT.c",             "Description" : "Comp_A, Simple 2.2V Low Battery Detect using CASHORT"},
	{"SourcePreview" : "msp430x21x1_flashwrite_03.c",          "Description" : "Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x21x1_flashwrite_04.c",          "Description" : "Flash In-System Programming w/ EEI, Copy SegC to SegD"},
	{"SourcePreview" : "msp430x21x1_fll_03.c",                 "Description" : "Basic Clock, Implement Auto RSEL SW FLL"},
	{"SourcePreview" : "msp430x21x1_hfxtal.c",                 "Description" : "Basic Clock, MCLK Sourced from HF XTAL"},
	{"SourcePreview" : "msp430x21x1_HF_ExtACLK.c",             "Description" : "Basic Clock, MCLK Sourced from HF Digital source"},
	{"SourcePreview" : "msp430x21x1_LF_ExtACLK.c",             "Description" : "LF Mode Ext Digital Clk source"},
	{"SourcePreview" : "msp430x21x1_LF_OFIFG_extclk.c",        "Description" : "OFIFG ISR for LF Failsafe Operation on Ext Clk"},
	{"SourcePreview" : "msp430x21x1_LF_OFIFG_XTAL.c",          "Description" : "OFIFG ISR for LF Failsafe Operation"},
	{"SourcePreview" : "msp430x21x1_Pull-up.c",                "Description" : "21x1 Pull-up resistors demo"},
	{"SourcePreview" : "msp430x21x1_ta_uart115k_12MHz.c",      "Description" : "Timer_A UART 115k, 12MHz DCO SMCLK"},
	{"SourcePreview" : "msp430x21x1_ta_uart115k_16MHz.c",      "Description" : "Timer_A UART 115k, 16MHz DCO SMCLK"},
	{"SourcePreview" : "msp430x21x1_ta_uart115k_8MHz.c",       "Description" : "Timer_A UART 115k, 8MHz DCO SMCLK"},
	{"SourcePreview" : "msp430x21x1_ta_uart19200_1MHz.c",      "Description" : "Timer_A UART 19200 TX, 1MHz DCO"},
	{"SourcePreview" : "msp430x21x1_ta_uart9600_1MHz.c",       "Description" : "Timer_A UART 9600, 1MHz DCO SMCLK"},
	{"SourcePreview" : "msp430x21x1_wdt_04.c",                 "Description" : "WDT+ Failsafe Clock, DCO SMCLK"}
];

