var jsonObjASM = [
	{"SourcePreview" : "msp430f673xA_adc10_01.asm",           "Description" : "ADC10, Sample A0, AVcc Ref, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430f673xA_dma_01.asm",             "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "msp430f673xA_flashwrite_02.asm",      "Description" : "Flash In-System Programming, Long-Word write at 0x1800"},
	{"SourcePreview" : "msp430f673xA_lpm3_01.asm",            "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, SVS disabled"},
	{"SourcePreview" : "msp430f673xA_lpm3_03.asm",            "Description" : "Enters LPM3 with ACLK = VLO;  LFXT1, REF0 disabled, SVS default state"},
	{"SourcePreview" : "msp430f673xA_mpy_1.asm",              "Description" : "MPY32, 16x16 Unsigned Multiply"},
	{"SourcePreview" : "msp430f673xA_mpy_10.asm",             "Description" : "MPY32, 32x32 Signed Multiply"},
	{"SourcePreview" : "msp430f673xA_mpy_15.asm",             "Description" : "MPY32, Fractional mode, Q15 multiplication"},
	{"SourcePreview" : "msp430f673xA_mpy_8.asm",              "Description" : "MPY32, 8x8 Signed Multiply Accumulate"},
	{"SourcePreview" : "msp430f673xA_of_lfxt1_nmi.asm",       "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430f673xA_p1_01.asm",              "Description" : "Software Poll P1.4, Set P1.0 if P1.4 = 1"},
	{"SourcePreview" : "msp430f673xA_p1_02.asm",              "Description" : "Software Port Interrupt Service on P1.4 from LPM4 with Internal Pull-up Resistance Enabled"},
	{"SourcePreview" : "msp430f673xA_pa_05.asm",              "Description" : "Write a Word to Port A (Port1+Port2)"},
	{"SourcePreview" : "msp430f673xA_rtc_01.asm",             "Description" : "RTC_C, Calendar Mode with Time Event and Alarm Interrupts"},
	{"SourcePreview" : "msp430f673xA_rtc_02.asm",             "Description" : "RTC_C, LPM3.5, & alarm"},
	{"SourcePreview" : "msp430f673xA_ta0_01.asm",             "Description" : "Timer0_A0, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f673xA_ta1_11.asm",             "Description" : "Timer1_A1, Toggle P8.4/TA1.0, Up Mode, ACLK = REFO"},
	{"SourcePreview" : "msp430f673xA_ta2_16.asm",             "Description" : "Timer2_A2, PWM TA2.1, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430f673xA_ucs_2.asm",              "Description" : "Software Toggle P1.0 with 8MHz DCO"},
	{"SourcePreview" : "msp430f673xA_ucs_4.asm",              "Description" : "FLL+, Runs Internal DCO at 2.45MHz with LFXT1 as Ref"},
	{"SourcePreview" : "msp430f673xA_uscib0_i2c_06.asm",      "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430f673xA_uscib0_i2c_07.asm",      "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430f673xA_wdt_01.asm",             "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430f673xA_wdt_02.asm",             "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430f673xA_wdt_04.asm",             "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"}
];

