MSP430UltrasonicLibrary: USS_Lib_HAL.c File Reference
USS_Lib_HAL.c File Reference
#include "USS_Lib_HAL.h"
#include "common/USSGenericRegDef.h"
Functions
__interrupt void USSLIB_HAL_TIMER_INT (void)
__interrupt void USSLIB_HAL_TIMER_INT_CCRn (void)
__interrupt void ISR_SDHS (void)
__interrupt void ISR_UUPS (void)
__interrupt void ISR_SAPH (void)
__interrupt void ISR_HSPLL (void)
__interrupt void DMA_HSPLL (void)
__bic_SR_register_on_exit (LPM0_bits)
Variables
void(* USSSWLIB_SAPH_DATAERR_callback)(void)=0
Contains function callback pointer for USS SAPH DATAERR.
void(* USSSWLIB_SAPH_TMFTO_callback)(void)=0
Contains function callback pointer for USS SAPH TMFTO.
void(* USSSWLIB_SAPH_SEQDN_callback)(void)=0
Contains function callback pointer for USS SAPH SEQDN.
void(* USSSWLIB_SAPH_PNGDN_callback)(void)=0
Contains function callback pointer for USS SAPH PNGDN.
void(* USSSWLIB_UUPS_PREQIG_callback)(void)=0
Contains function callback pointer for USS UUPS PREQIG.
void(* USSSWLIB_UUPS_PTMOUT_callback)(void)=0
Contains function callback pointer for USS UUPS_PTMOUT.
void(* USSSWLIB_UUPS_STPBYDB_callback)(void)=0
Contains function callback pointer for USS UUPS_STPBYDB.
void(* USSSWLIB_HSPLL_PLLunlock_callback)(void)=0
Contains function callback pointer for USS HSPLL_UNLOCK.
void(* USSSWLIB_SDHS_OVF_callback)(void)=0
Contains function callback pointer for USS_SDHS_OVF.
void(* USSSWLIB_SDHS_ACQDONE_callback)(void)=0
Contains function callback pointer for USS_SDHS_OVINLVL.
void(* USSSWLIB_SDHS_SSTRG_callback)(void)=0
Contains function callback pointer for USS_SDHS_SSTRG.
void(* USSSWLIB_SDHS_DTRDY_callback)(void)=0
Contains function callback pointer for USS_SDHS_DTRDY.
void(* USSSWLIB_SDHS_WINHI_callback)(void)=0
Contains function callback pointer for USS_SDHS_WINHI.
void(* USSSWLIB_SDHS_WINLO_callback)(void)=0
Contains function callback pointer for USS_SDHS_WINLO.
LEAIFG = flags
USS_LEA_IFG = flags
Function Documentation
USSLIB_HAL_TIMER_INT()
__interrupt void USSLIB_HAL_TIMER_INT (void)
References HARDWAREWREG16, USS_TIMER_EXPIRED_INTERRUPT, USSSWLIB_TIMER_BASE_ADDRESS, and USSSWLIB_USS_interrupt_status.
USSLIB_HAL_TIMER_INT_CCRn()
__interrupt void USSLIB_HAL_TIMER_INT_CCRn (void)
References HARDWAREWREG16, USS_TIMER_EXPIRED_EVENT1_INTERRUPT, USSSWLIB_TIMER_BASE_ADDRESS, and USSSWLIB_USS_interrupt_status.
ISR_SDHS()
__interrupt void ISR_SDHS (void)
References USS_SDHS_ACQDONE_INTERRUPT, USS_SDHS_DTRDY_INTERRUPT, USS_SDHS_OVF_INTERRUPT, USS_SDHS_SSTRG_INTERRUPT, USS_SDHS_WINHI_INTERRUPT, USS_SDHS_WINLO_INTERRUPT, USSSWLIB_SDHS_ACQDONE_callback, USSSWLIB_SDHS_DTRDY_callback, USSSWLIB_SDHS_OVF_callback, USSSWLIB_SDHS_SSTRG_callback, USSSWLIB_SDHS_WINHI_callback, USSSWLIB_SDHS_WINLO_callback, and USSSWLIB_USS_interrupt_status.
ISR_UUPS()
__interrupt void ISR_UUPS (void)
References USS_UUPS_PWR_REQ_IGN_INTERRUPT, USS_UUPS_PWR_UP_TM_OUT_INTERRUPT, USS_UUPS_STOPPED_BY_DEBUGGER, USSSWLIB_USS_interrupt_status, USSSWLIB_UUPS_PREQIG_callback, USSSWLIB_UUPS_PTMOUT_callback, and USSSWLIB_UUPS_STPBYDB_callback.
ISR_SAPH()
__interrupt void ISR_SAPH (void)
References USS_SAPH_DATA_ERR_ABORT_INTERRUPT, USS_SAPH_PING_DN_INTERRUPT, USS_SAPH_SEQ_ACQ_DN_INTERRUPT, USS_SAPH_TMF_TM_OUT_INTERRUPT, USSSWLIB_SAPH_DATAERR_callback, USSSWLIB_SAPH_PNGDN_callback, USSSWLIB_SAPH_SEQDN_callback, USSSWLIB_SAPH_TMFTO_callback, and USSSWLIB_USS_interrupt_status.
ISR_HSPLL()
__interrupt void ISR_HSPLL (void)
References USS_HSPLL_PLL_UNLOCK_INTERRUPT, USSSWLIB_HSPLL_PLLunlock_callback, and USSSWLIB_USS_interrupt_status.
DMA_HSPLL()
__interrupt void DMA_HSPLL (void)
References LEAIFG.
__bic_SR_register_on_exit()
__bic_SR_register_on_exit (LPM0_bits)
Variable Documentation
USSSWLIB_SAPH_DATAERR_callback
void(* USSSWLIB_SAPH_DATAERR_callback) (void)=0
Contains function callback pointer for USS SAPH DATAERR.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_TMFTO_callback
void(* USSSWLIB_SAPH_TMFTO_callback) (void)=0
Contains function callback pointer for USS SAPH TMFTO.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_SEQDN_callback
void(* USSSWLIB_SAPH_SEQDN_callback) (void)=0
Contains function callback pointer for USS SAPH SEQDN.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_PNGDN_callback
void(* USSSWLIB_SAPH_PNGDN_callback) (void)=0
Contains function callback pointer for USS SAPH PNGDN.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_UUPS_PREQIG_callback
void(* USSSWLIB_UUPS_PREQIG_callback) (void)=0
Contains function callback pointer for USS UUPS PREQIG.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_UUPS_PTMOUT_callback
void(* USSSWLIB_UUPS_PTMOUT_callback) (void)=0
Contains function callback pointer for USS UUPS_PTMOUT.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_UUPS_STPBYDB_callback
void(* USSSWLIB_UUPS_STPBYDB_callback) (void)=0
Contains function callback pointer for USS UUPS_STPBYDB.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_HSPLL_PLLunlock_callback
void(* USSSWLIB_HSPLL_PLLunlock_callback) (void)=0
Contains function callback pointer for USS HSPLL_UNLOCK.
Referenced by ISR_HSPLL(), USS_registerHSPLLInterruptCallback(), and USS_unregisterHSPLLInterruptCallback().
USSSWLIB_SDHS_OVF_callback
void(* USSSWLIB_SDHS_OVF_callback) (void)=0
Contains function callback pointer for USS_SDHS_OVF.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_ACQDONE_callback
void(* USSSWLIB_SDHS_ACQDONE_callback) (void)=0
Contains function callback pointer for USS_SDHS_OVINLVL.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_SSTRG_callback
void(* USSSWLIB_SDHS_SSTRG_callback) (void)=0
Contains function callback pointer for USS_SDHS_SSTRG.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_DTRDY_callback
void(* USSSWLIB_SDHS_DTRDY_callback) (void)=0
Contains function callback pointer for USS_SDHS_DTRDY.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_WINHI_callback
void(* USSSWLIB_SDHS_WINHI_callback) (void)=0
Contains function callback pointer for USS_SDHS_WINHI.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_WINLO_callback
void(* USSSWLIB_SDHS_WINLO_callback) (void)=0
Contains function callback pointer for USS_SDHS_WINLO.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
LEAIFG
LEAIFG = flags
Referenced by DMA_HSPLL().
USS_LEA_IFG
USS_LEA_IFG = flags
© Copyright 1995-2019, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale