MSP430UltrasonicLibrary: USS_Lib_HAL.h File Reference
USS_Lib_HAL.h File Reference
#include <msp430.h>
#include "ussSwLib.h"
Macros
#define USSSWLIB_ENABLE_EXTERNAL_CIRCUITRY_CONTROL false
#define ENABLE_USS_LIB_BENCHMARK false
#define USSSWLIB_TIMER_BASE_ADDRESS (TIMER_A2_BASE)
#define USSLIB_HAL_TIMER_RXEN_CCR0_VECTOR (TIMER0_A0_VECTOR)
#define USSLIB_HAL_TIMER_RXEN_CCR1_VECTOR (TIMER0_A1_VECTOR)
#define USSLIB_HAL_TIMER_CCR0_VECTOR (TIMER0_A0_VECTOR)
#define USSLIB_HAL_TIMER_CCR1_VECTOR (TIMER0_A1_VECTOR)
#define USS_HAL_LEA_DATA(var, align)
Typedefs
typedef enum _USSLIB_HAL_capture_mode_ USSLIB_HAL_capture_mode
Selects the desired power mode while USS capture is done, API will remain in this mode until capture is done.
Enumerations
enum _USSLIB_HAL_capture_mode_ { USSLIB_HAL_capture_mode_ups = 0, USSLIB_HAL_capture_mode_dns }
Selects the desired power mode while USS capture is done, API will remain in this mode until capture is done.
Functions
void USSLIB_HAL_initGPIO (void)
function to initialize GPIOs used by USS Library
void USSLIB_HAL_configGPIOForCapture (USSLIB_HAL_capture_mode mode)
function to configure capture gpios
void USSLIB_HAL_configureRxEnTimer (uint16_t ASQTimerCounts, uint16_t RxEnTimerCounts)
function to configure Timer used to control RxEn AFE pin state
void USSLIB_HAL_startRxEnTimer (void)
function to start Timer used to control RxEn AFE pin state
void USSLIB_HAL_configGPIOAfterCapture (void)
function to configure GPIOs after acquisition
Variables
volatile uint16_t USS_LEA_IFG
void(* USSSWLIB_SAPH_DATAERR_callback)(void)
Contains function callback pointer for USS SAPH DATAERR.
void(* USSSWLIB_SAPH_TMFTO_callback)(void)
Contains function callback pointer for USS SAPH TMFTO.
void(* USSSWLIB_SAPH_SEQDN_callback)(void)
Contains function callback pointer for USS SAPH SEQDN.
void(* USSSWLIB_SAPH_PNGDN_callback)(void)
Contains function callback pointer for USS SAPH PNGDN.
void(* USSSWLIB_UUPS_PREQIG_callback)(void)
Contains function callback pointer for USS UUPS PREQIG.
void(* USSSWLIB_UUPS_PTMOUT_callback)(void)
Contains function callback pointer for USS UUPS_PTMOUT.
void(* USSSWLIB_UUPS_STPBYDB_callback)(void)
Contains function callback pointer for USS UUPS_STPBYDB.
void(* USSSWLIB_HSPLL_PLLunlock_callback)(void)
Contains function callback pointer for USS HSPLL_UNLOCK.
void(* USSSWLIB_SDHS_OVF_callback)(void)
Contains function callback pointer for USS_SDHS_OVF.
void(* USSSWLIB_SDHS_ACQDONE_callback)(void)
Contains function callback pointer for USS_SDHS_OVINLVL.
void(* USSSWLIB_SDHS_SSTRG_callback)(void)
Contains function callback pointer for USS_SDHS_SSTRG.
void(* USSSWLIB_SDHS_DTRDY_callback)(void)
Contains function callback pointer for USS_SDHS_DTRDY.
void(* USSSWLIB_SDHS_WINHI_callback)(void)
Contains function callback pointer for USS_SDHS_WINHI.
void(* USSSWLIB_SDHS_WINLO_callback)(void)
Contains function callback pointer for USS_SDHS_WINLO.
Macro Definition Documentation
USSSWLIB_ENABLE_EXTERNAL_CIRCUITRY_CONTROL
#define USSSWLIB_ENABLE_EXTERNAL_CIRCUITRY_CONTROL false
ENABLE_USS_LIB_BENCHMARK
#define ENABLE_USS_LIB_BENCHMARK false
USSSWLIB_TIMER_BASE_ADDRESS
#define USSSWLIB_TIMER_BASE_ADDRESS (TIMER_A2_BASE)
Referenced by USSLIB_HAL_TIMER_INT(), and USSLIB_HAL_TIMER_INT_CCRn().
USSLIB_HAL_TIMER_RXEN_CCR0_VECTOR
#define USSLIB_HAL_TIMER_RXEN_CCR0_VECTOR (TIMER0_A0_VECTOR)
USSLIB_HAL_TIMER_RXEN_CCR1_VECTOR
#define USSLIB_HAL_TIMER_RXEN_CCR1_VECTOR (TIMER0_A1_VECTOR)
USSLIB_HAL_TIMER_CCR0_VECTOR
#define USSLIB_HAL_TIMER_CCR0_VECTOR (TIMER0_A0_VECTOR)
USSLIB_HAL_TIMER_CCR1_VECTOR
#define USSLIB_HAL_TIMER_CCR1_VECTOR (TIMER0_A1_VECTOR)
USS_HAL_LEA_DATA
#define USS_HAL_LEA_DATA (var, align)
Typedef Documentation
USSLIB_HAL_capture_mode
typedef enum _USSLIB_HAL_capture_mode_ USSLIB_HAL_capture_mode
Selects the desired power mode while USS capture is done, API will remain in this mode until capture is done.
Enumeration Type Documentation
_USSLIB_HAL_capture_mode_
enum _USSLIB_HAL_capture_mode_
Selects the desired power mode while USS capture is done, API will remain in this mode until capture is done.
Enumerator
USSLIB_HAL_capture_mode_ups
USSLIB_HAL_capture_mode_dns
Function Documentation
USSLIB_HAL_initGPIO()
void USSLIB_HAL_initGPIO (void)
function to initialize GPIOs used by USS Library
Referenced by USS_configureUltrasonicMeasurement().
USSLIB_HAL_configGPIOForCapture()
void USSLIB_HAL_configGPIOForCapture (USSLIB_HAL_capture_mode mode)
function to configure capture gpios
Referenced by USS_commonTriggerSingleCapture().
USSLIB_HAL_configureRxEnTimer()
void USSLIB_HAL_configureRxEnTimer (uint16_t ASQTimerCounts, uint16_t RxEnTimerCounts)
function to configure Timer used to control RxEn AFE pin state
Referenced by USS_configureUltrasonicMeasurement().
USSLIB_HAL_startRxEnTimer()
void USSLIB_HAL_startRxEnTimer (void)
function to start Timer used to control RxEn AFE pin state
Referenced by USS_commonTriggerSingleCapture().
USSLIB_HAL_configGPIOAfterCapture()
void USSLIB_HAL_configGPIOAfterCapture (void)
function to configure GPIOs after acquisition
Referenced by USS_commonTriggerSingleCapture().
Variable Documentation
USS_LEA_IFG
volatile uint16_t USS_LEA_IFG
USSSWLIB_SAPH_DATAERR_callback
void(* USSSWLIB_SAPH_DATAERR_callback) (void)
Contains function callback pointer for USS SAPH DATAERR.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_TMFTO_callback
void(* USSSWLIB_SAPH_TMFTO_callback) (void)
Contains function callback pointer for USS SAPH TMFTO.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_SEQDN_callback
void(* USSSWLIB_SAPH_SEQDN_callback) (void)
Contains function callback pointer for USS SAPH SEQDN.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_SAPH_PNGDN_callback
void(* USSSWLIB_SAPH_PNGDN_callback) (void)
Contains function callback pointer for USS SAPH PNGDN.
Referenced by ISR_SAPH(), USS_registerSAPHInterruptCallback(), and USS_unregisterSAPHInterruptCallback().
USSSWLIB_UUPS_PREQIG_callback
void(* USSSWLIB_UUPS_PREQIG_callback) (void)
Contains function callback pointer for USS UUPS PREQIG.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_UUPS_PTMOUT_callback
void(* USSSWLIB_UUPS_PTMOUT_callback) (void)
Contains function callback pointer for USS UUPS_PTMOUT.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_UUPS_STPBYDB_callback
void(* USSSWLIB_UUPS_STPBYDB_callback) (void)
Contains function callback pointer for USS UUPS_STPBYDB.
Referenced by ISR_UUPS(), USS_registerUUPSInterruptCallback(), and USS_unregisterUUPSInterruptCallback().
USSSWLIB_HSPLL_PLLunlock_callback
void(* USSSWLIB_HSPLL_PLLunlock_callback) (void)
Contains function callback pointer for USS HSPLL_UNLOCK.
Referenced by ISR_HSPLL(), USS_registerHSPLLInterruptCallback(), and USS_unregisterHSPLLInterruptCallback().
USSSWLIB_SDHS_OVF_callback
void(* USSSWLIB_SDHS_OVF_callback) (void)
Contains function callback pointer for USS_SDHS_OVF.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_ACQDONE_callback
void(* USSSWLIB_SDHS_ACQDONE_callback) (void)
Contains function callback pointer for USS_SDHS_OVINLVL.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_SSTRG_callback
void(* USSSWLIB_SDHS_SSTRG_callback) (void)
Contains function callback pointer for USS_SDHS_SSTRG.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_DTRDY_callback
void(* USSSWLIB_SDHS_DTRDY_callback) (void)
Contains function callback pointer for USS_SDHS_DTRDY.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_WINHI_callback
void(* USSSWLIB_SDHS_WINHI_callback) (void)
Contains function callback pointer for USS_SDHS_WINHI.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
USSSWLIB_SDHS_WINLO_callback
void(* USSSWLIB_SDHS_WINLO_callback) (void)
Contains function callback pointer for USS_SDHS_WINLO.
Referenced by ISR_SDHS(), USS_registerSDHSInterruptCallback(), and USS_unregisterSDHSInterruptCallback().
© Copyright 1995-2019, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale