MSP430UltrasonicLibrary: UssSwLib
UssSwLib
Macros
#define USS_SAPH_MAX_MULTITONE_UPDATE_FREQ_IN_HZ (420000)
#define USS_SAPH_MAX_STOP_PULSES (16)
#define LEA_START_ADDRESS (0x2C00)
#define USS_ALGORITHMS_NUM_OF_SAMPLE_PADDING (ALG_MAX_FILTER_LENGTH)
#define RESONATOR_CALIB_ITERATION_COUNT 2
#define RESONATOR_CALIB_MONITORING_ACLK 550
#define AGC_LOOP_MAX_ITERATIONS 5
#define AGC_LOOP_SETTLING 3
#define ADC_MINIMUM_GAIN_SETTING USS_Capture_Gain_Range_minus_6_5
#define AGC_GAIN_TABLE_SIZE (47*2)
#define AGC_INDEX_OFFSET 17
#define AGC_MIN_DIFFERENCE 1.0
#define RESONATOR_CALIB_MONITORING_ACLK_MIN_COUNT 4
#define PLL_68_MHZ_TEMP_CONST
#define PLL_69_MHZ_TEMP_CONST
#define PLL_70_MHZ_TEMP_CONST
#define PLL_71_MHZ_TEMP_CONST
#define PLL_72_MHZ_TEMP_CONST
#define PLL_73_MHZ_TEMP_CONST
#define PLL_74_MHZ_TEMP_CONST
#define PLL_75_MHZ_TEMP_CONST
#define PLL_76_MHZ_TEMP_CONST
#define PLL_77_MHZ_TEMP_CONST
#define PLL_78_MHZ_TEMP_CONST
#define PLL_79_MHZ_TEMP_CONST
#define PLL_80_MHZ_TEMP_CONST
#define ABSTOF_DTOF_MAX_ITERATIONS 64999
Typedefs
typedef enum _USS_silicon_version_ USS_silicon_version
Used to specify the silicon version of FR6047 or FR6043 devices.
typedef enum _USS_silicon_variant_ USS_silicon_variant
Used to identify FR6047 or FR6043 devices.
Enumerations
enum _USS_silicon_version_ { USS_silicon_version_A, USS_silicon_version_B, USS_silicon_version_not_supported }
Used to specify the silicon version of FR6047 or FR6043 devices.
enum _USS_silicon_variant_ { USS_silicon_version_variant_FR6047, USS_silicon_version_variant_FR6043, USS_silicon_version_variant_not_supported }
Used to identify FR6047 or FR6043 devices.
Functions
USS_message_code commonValidateHSPLLconfiguration (USS_SW_Library_configuration *config)
void commonStabilizeOscillator (USS_SW_Library_configuration *config)
uint32_t commonGetHSPLLFreqInHz (USS_SW_Library_configuration *config)
void commonTurnOffHSPLLXTAL (void)
void commonEnableCaptureInterrupts (USS_SW_Library_configuration *config)
void commonDisableCaptureInterrupts (USS_SW_Library_configuration *config)
void commonClearUSSInterrupts (void)
void commonEnableManualSDHSTriggerInterrupts (USS_SW_Library_configuration *config)
USS_message_code commonConfigurePPGDutyCyle (USS_SW_Library_configuration *config, USS_measurement_pulse_generation_mode mode)
USS_message_code commonConfigurePPGForManualMode (USS_SW_Library_configuration *config, USS_test_channel pPGChannel)
USS_message_code commonValidateSAPHconfigruation (USS_SW_Library_configuration *config)
USS_message_code commonValidateSDHSconfigruation (USS_SW_Library_configuration *config)
void commonSDHSRestoreSDHSDTCA (USS_SW_Library_configuration *config)
void commonSDHSConfigModOpt (USS_SW_Library_configuration *config)
void commonTimerGenerateLowPowerDelay (USS_SW_Library_configuration *config, uint16_t delay, USS_low_power_mode_option lpmMode)
void commonClearCCFlagStart (USS_SW_Library_configuration *config)
void commonTimerConfigureDelay (USS_SW_Library_configuration *config, uint16_t delay)
void commonTimerStart (USS_SW_Library_configuration *config)
void commonTimerStop (USS_SW_Library_configuration *config)
void commonTimerEnableInterrupt (USS_SW_Library_configuration *config)
void commonTimerDisableInterrupt (USS_SW_Library_configuration *config)
bool commonTimerPollInterruptFlag (USS_SW_Library_configuration *config)
void commonTimerClear (USS_SW_Library_configuration *config)
bool commonTimerConfigureTimer (USS_SW_Library_configuration *config)
void commonTimerConfigurePeriodMeasurement (USS_SW_Library_configuration *config, uint16_t delay1, uint16_t delay2)
void commonTimerPeriodMeasurementClear (USS_SW_Library_configuration *config)
void commonTimerPeriodMeasurementEnableInterrupts (USS_SW_Library_configuration *config)
void commonTimerPeriodMeasurementDisableInterrupts (USS_SW_Library_configuration *config)
void commonTimerPeriodMeasurementStart (USS_SW_Library_configuration *config)
void commonTimerPeriodMeasurementWaitEvent1 (USS_SW_Library_configuration *config, USS_low_power_mode_option lpmMode)
void commonTimerPeriodMeasurementWaitEvent2 (USS_SW_Library_configuration *config, USS_low_power_mode_option lpmMode)
USS_message_code commonPowerUpUSS (USS_SW_Library_configuration *config)
USS_message_code commonPowerDownUSS (USS_SW_Library_configuration *config)
USS_message_code commonIsconversionSuccessfull (USS_SW_Library_configuration *config)
uint16_t commonDecodeSDHSDTCDAoffset (USS_SW_Library_configuration *config)
void commonWaitForconversion (USS_capture_power_mode_option mode)
USS_message_code commonPrepareForUSSPowerUp (USS_SW_Library_configuration *config)
USS_message_code commonUpdateUSSULPbiasDelay (USS_SW_Library_configuration *config)
USS_silicon_version commonDetermineSiliconVersion (void)
USS_silicon_variant commonDetermineVariant (void)
Variables
const float gUSSGainLookUp [AGC_GAIN_TABLE_SIZE]
Detailed Description
Macro Definition Documentation
USS_SAPH_MAX_MULTITONE_UPDATE_FREQ_IN_HZ
#define USS_SAPH_MAX_MULTITONE_UPDATE_FREQ_IN_HZ (420000)
USS_SAPH_MAX_STOP_PULSES
#define USS_SAPH_MAX_STOP_PULSES (16)
Referenced by commonValidateSAPHconfigruation().
LEA_START_ADDRESS
#define LEA_START_ADDRESS (0x2C00)
USS_ALGORITHMS_NUM_OF_SAMPLE_PADDING
#define USS_ALGORITHMS_NUM_OF_SAMPLE_PADDING (ALG_MAX_FILTER_LENGTH)
RESONATOR_CALIB_ITERATION_COUNT
#define RESONATOR_CALIB_ITERATION_COUNT 2
Referenced by USS_verifyHSPLLFrequency().
RESONATOR_CALIB_MONITORING_ACLK
#define RESONATOR_CALIB_MONITORING_ACLK 550
Referenced by USS_verifyHSPLLFrequency().
AGC_LOOP_MAX_ITERATIONS
#define AGC_LOOP_MAX_ITERATIONS 5
Referenced by USS_calibrateSignalGain().
AGC_LOOP_SETTLING
#define AGC_LOOP_SETTLING 3
Referenced by USS_calibrateSignalGain().
ADC_MINIMUM_GAIN_SETTING
#define ADC_MINIMUM_GAIN_SETTING USS_Capture_Gain_Range_minus_6_5
Referenced by USS_calibrateSignalGain().
AGC_GAIN_TABLE_SIZE
#define AGC_GAIN_TABLE_SIZE (47*2)
AGC_INDEX_OFFSET
#define AGC_INDEX_OFFSET 17
Referenced by USS_calibrateSignalGain().
AGC_MIN_DIFFERENCE
#define AGC_MIN_DIFFERENCE 1.0
Referenced by USS_findAGCIndex().
RESONATOR_CALIB_MONITORING_ACLK_MIN_COUNT
#define RESONATOR_CALIB_MONITORING_ACLK_MIN_COUNT 4
Referenced by USS_verifyHSPLLFrequency().
PLL_68_MHZ_TEMP_CONST
#define PLL_68_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)68000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_69_MHZ_TEMP_CONST
#define PLL_69_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)69000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_70_MHZ_TEMP_CONST
#define PLL_70_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)70000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_71_MHZ_TEMP_CONST
#define PLL_71_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)71000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_72_MHZ_TEMP_CONST
#define PLL_72_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)72000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_73_MHZ_TEMP_CONST
#define PLL_73_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)73000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_74_MHZ_TEMP_CONST
#define PLL_74_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)74000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_75_MHZ_TEMP_CONST
#define PLL_75_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)75000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_76_MHZ_TEMP_CONST
#define PLL_76_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)76000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_77_MHZ_TEMP_CONST
#define PLL_77_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)77000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_78_MHZ_TEMP_CONST
#define PLL_78_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)78000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_79_MHZ_TEMP_CONST
#define PLL_79_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)79000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
PLL_80_MHZ_TEMP_CONST
#define PLL_80_MHZ_TEMP_CONST
Value:
(uint64_t)((uint64_t)80000000* \
                                   (uint64_t)RESONATOR_CALIB_MONITORING_ACLK)
Referenced by USS_verifyHSPLLFrequency().
ABSTOF_DTOF_MAX_ITERATIONS
#define ABSTOF_DTOF_MAX_ITERATIONS 64999
Referenced by USS_calculateOffsets().
Typedef Documentation
USS_silicon_version
typedef enum _USS_silicon_version_ USS_silicon_version
Used to specify the silicon version of FR6047 or FR6043 devices.
USS_silicon_variant
typedef enum _USS_silicon_variant_ USS_silicon_variant
Used to identify FR6047 or FR6043 devices.
Enumeration Type Documentation
_USS_silicon_version_
enum _USS_silicon_version_
Used to specify the silicon version of FR6047 or FR6043 devices.
Enumerator
USS_silicon_version_A
USS_silicon_version_B
USS_silicon_version_not_supported
_USS_silicon_variant_
enum _USS_silicon_variant_
Used to identify FR6047 or FR6043 devices.
Enumerator
USS_silicon_version_variant_FR6047
USS_silicon_version_variant_FR6043
USS_silicon_version_variant_not_supported
Function Documentation
commonValidateHSPLLconfiguration()
USS_message_code commonValidateHSPLLconfiguration (USS_SW_Library_configuration * config)
References _USS_SW_Library_configuration_::pllConfiguration, _USS_HSPLL_Configuration_::pllOutputFreq, USS_HSPLL_input_clock_freq_4_MHz, USS_HSPLL_input_clock_freq_8_MHz, USS_HSPLL_output_clk_freq_68_MHz, USS_message_code_HSPLL_invalid_settling_count_error, USS_message_code_HSPLL_pllOutputFreq_inHz_error, USS_message_code_HSPLL_pllXtalFreq_inHz_error, USS_message_code_no_error, _USS_HSPLL_Configuration_::ussXtalFreq, and _USS_HSPLL_Configuration_::ussXTALsettlingCount.
Referenced by USS_updateHSPLLConfiguration().
commonStabilizeOscillator()
void commonStabilizeOscillator (USS_SW_Library_configuration * config)
References commonTimerGenerateLowPowerDelay(), _USS_SW_Library_configuration_::pllConfiguration, USS_low_power_mode_option_low_power_mode_3, and _USS_HSPLL_Configuration_::ussXTALsettlingCount.
Referenced by commonPrepareForUSSPowerUp().
commonGetHSPLLFreqInHz()
uint32_t commonGetHSPLLFreqInHz (USS_SW_Library_configuration * config)
References _USS_SW_Library_configuration_::pllConfiguration, _USS_HSPLL_Configuration_::pllOutputFreq, USS_HSPLL_output_clk_freq_68_MHz, USS_HSPLL_output_clk_freq_69_MHz, USS_HSPLL_output_clk_freq_70_MHz, USS_HSPLL_output_clk_freq_71_MHz, USS_HSPLL_output_clk_freq_72_MHz, USS_HSPLL_output_clk_freq_73_MHz, USS_HSPLL_output_clk_freq_74_MHz, USS_HSPLL_output_clk_freq_75_MHz, USS_HSPLL_output_clk_freq_76_MHz, USS_HSPLL_output_clk_freq_77_MHz, USS_HSPLL_output_clk_freq_78_MHz, USS_HSPLL_output_clk_freq_79_MHz, and USS_HSPLL_output_clk_freq_80_MHz.
Referenced by commonConfigurePPGDutyCyle(), and commonValidateSAPHconfigruation().
commonTurnOffHSPLLXTAL()
void commonTurnOffHSPLLXTAL (void)
Referenced by USS_stopPPGToneGeneration(), and USS_testPPGconfiguration().
commonEnableCaptureInterrupts()
void commonEnableCaptureInterrupts (USS_SW_Library_configuration * config)
Referenced by USS_commonTriggerSingleCapture(), USS_startUltrasonicMeasurement(), and USS_stopUltrasonicMeasurement().
commonDisableCaptureInterrupts()
void commonDisableCaptureInterrupts (USS_SW_Library_configuration * config)
References _USS_SW_Library_configuration_::captureConfig, _USS_Capture_Configuration_::enableWindowHiComp, _USS_Capture_Configuration_::enableWindowLoComp, and GENERIC_SAPH_IMSC.
Referenced by commonIsconversionSuccessfull().
commonClearUSSInterrupts()
void commonClearUSSInterrupts (void)
References GENERIC_SAPH_ICR, USS_HSPLL_PLL_UNLOCK_INTERRUPT, USS_SAPH_DATA_ERR_ABORT_INTERRUPT, USS_SAPH_DMA_ACK_VIOLATION, USS_SAPH_PING_DN_INTERRUPT, USS_SAPH_SEQ_ACQ_DN_INTERRUPT, USS_SAPH_SEQUENCE_STOPPED, USS_SAPH_TMF_TM_OUT_INTERRUPT, USS_SDHS_ACQDONE_INTERRUPT, USS_SDHS_DTRDY_INTERRUPT, USS_SDHS_OVF_INTERRUPT, USS_SDHS_SSTRG_INTERRUPT, USS_SDHS_WINHI_INTERRUPT, USS_SDHS_WINLO_INTERRUPT, USS_UUPS_PWR_REQ_IGN_INTERRUPT, USS_UUPS_PWR_UP_TM_OUT_INTERRUPT, USS_UUPS_STOPPED_BY_DEBUGGER, and USSSWLIB_USS_interrupt_status.
Referenced by USS_startUltrasonicMeasurement(), and USS_testSDHSconversion().
commonEnableManualSDHSTriggerInterrupts()
void commonEnableManualSDHSTriggerInterrupts (USS_SW_Library_configuration * config)
Referenced by USS_testSDHSconversion().
commonConfigurePPGDutyCyle()
USS_message_code commonConfigurePPGDutyCyle (USS_SW_Library_configuration * config, USS_measurement_pulse_generation_mode mode)
References commonGetHSPLLFreqInHz(), _USS_Pulse_Single_Dual_Tone_Configuration_::F1DutyCycle, _USS_Pulse_Configuration_::F1Frequency, _USS_Pulse_Single_Dual_Tone_Configuration_::F2DutyCycle, _USS_Pulse_Configuration_::F2Frequency, GENERIC_SAPH_HP_E_PULS, GENERIC_SAPH_LP_E_PULS, GENERIC_SAPH_PGC, _USS_SW_Library_configuration_::measurementConfig, _USS_Pulse_Single_Dual_Tone_Configuration_::numOfF1Cycles, _USS_Pulse_Single_Dual_Tone_Configuration_::numOfF2Cycles, _USS_Pulse_Configuration_::numOfStopPulses, _USS_Pulse_Configuration_::pToneConfig, _USS_Measurement_Configuration_::pulseConfig, USS_measurement_pulse_generation_mode_dual_tone, USS_measurement_pulse_generation_mode_single_tone, USS_message_code_no_error, and USS_message_code_SAPH_invalid_pulse_configuration_error.
Referenced by USS_startPPGToneGeneration(), and USS_updateSAPHConfiguration().
commonConfigurePPGForManualMode()
USS_message_code commonConfigurePPGForManualMode (USS_SW_Library_configuration * config, USS_test_channel pPGChannel)
References commonPowerUpUSS(), commonPrepareForUSSPowerUp(), GENERIC_SAPH_KEY, GENERIC_SAPH_PGCTL, USS_message_code_no_error, USS_message_code_USS_ongoing_active_conversion_error, USS_test_channel_1, USS_updateHSPLLConfiguration(), and USS_updateSAPHConfiguration().
Referenced by USS_testPPGconfiguration().
commonValidateSAPHconfigruation()
USS_message_code commonValidateSAPHconfigruation (USS_SW_Library_configuration * config)
References _USS_Measurement_Configuration_::biasImpedance, _USS_Measurement_Configuration_::captureTimeOutCount, commonDetermineSiliconVersion(), commonDetermineVariant(), commonGetHSPLLFreqInHz(), E_HPER_STATE, E_LPER_STATE, _USS_Pulse_Single_Dual_Tone_Configuration_::F1DutyCycle, _USS_Pulse_Configuration_::F1Frequency, _USS_Pulse_Single_Dual_Tone_Configuration_::F2DutyCycle, _USS_Pulse_Configuration_::F2Frequency, GENERIC_SAPH_PGC, _USS_SW_Library_configuration_::measurementConfig, _USS_Measurement_Configuration_::muxChargePumpMode, _USS_Pulse_Single_Dual_Tone_Configuration_::numOfF1Cycles, _USS_Pulse_Single_Dual_Tone_Configuration_::numOfF2Cycles, _USS_Pulse_Configuration_::numOfStopPulses, _USS_Pulse_Additional_End_of_Sequence_Configuration_::numOfTrillcycles, _USS_Pulse_Multitone_Configuration_::numOfTrillcycles, _USS_Pulse_Multitone_Configuration_::origNumOfThrillCycles, _USS_Pulse_Multitone_Configuration_::pEOFSeqConfig, _USS_Pulse_Additional_End_of_Sequence_Configuration_::pEPulsHPerArray, _USS_Pulse_Multitone_Configuration_::pEPulsHPerArray, _USS_Pulse_Additional_End_of_Sequence_Configuration_::pEPulsLPerArray, _USS_Pulse_Multitone_Configuration_::pEPulsLPerArray, _USS_SW_Library_configuration_::pllConfiguration, _USS_HSPLL_Configuration_::pllOutputFreq, _USS_Pulse_Additional_End_of_Sequence_Configuration_::pNumOfEPulsArray, _USS_Pulse_Multitone_Configuration_::pNumOfEPulsArray, _USS_Pulse_Additional_End_of_Sequence_Configuration_::pNumOfXPulsArray, _USS_Pulse_Multitone_Configuration_::pNumOfXPulsArray, _USS_Pulse_Multitone_Configuration_::pRAMDMAConfigArray, _USS_Pulse_Multitone_Configuration_::pRAMPulseConfigArray, _USS_Pulse_Configuration_::pToneConfig, _USS_Measurement_Configuration_::pulseConfig, _USS_Pulse_Configuration_::pulseGenMode, _USS_Pulse_Multitone_Configuration_::pXPulsHPerArray, _USS_Pulse_Additional_End_of_Sequence_Configuration_::pXPulsLPerArray, _USS_Pulse_Multitone_Configuration_::pXPulsLPerArray, _USS_Measurement_Configuration_::restartCaptureCount, _USS_Measurement_Configuration_::startADCsamplingCount, _USS_Measurement_Configuration_::startPGAandINBiasCount, _USS_Measurement_Configuration_::startPPGCount, TOTAL_NUM_OF_STATES, _USS_Measurement_Configuration_::turnOnADCCount, _USS_Measurement_Configuration_::ulpBiasDelay, USS_HSPLL_output_clk_freq_68_MHz, USS_HSPLL_output_clk_freq_69_MHz, USS_HSPLL_output_clk_freq_70_MHz, USS_HSPLL_output_clk_freq_71_MHz, USS_HSPLL_output_clk_freq_72_MHz, USS_HSPLL_output_clk_freq_73_MHz, USS_HSPLL_output_clk_freq_74_MHz, USS_HSPLL_output_clk_freq_75_MHz, USS_HSPLL_output_clk_freq_76_MHz, USS_HSPLL_output_clk_freq_77_MHz, USS_HSPLL_output_clk_freq_78_MHz, USS_HSPLL_output_clk_freq_79_MHz, USS_HSPLL_output_clk_freq_80_MHz, USS_measurement_bias_impedance_1200_Ohms, USS_measurement_bias_impedance_200_Ohms, USS_measurement_bias_impedance_2800_Ohms, USS_measurement_bias_impedance_600_Ohms, USS_measurement_mux_charge_pump_always_off, USS_measurement_mux_charge_pump_always_on, USS_measurement_pulse_generation_mode_dual_tone, USS_measurement_pulse_generation_mode_multi_tone, USS_measurement_pulse_generation_mode_single_tone, USS_measurement_ULP_bias_delay_no_delay, USS_message_code_HSPLL_pllOutputFreq_inHz_error, USS_message_code_no_error, USS_message_code_SAPH_invalid_bias_impedance_error, USS_message_code_SAPH_invalid_pulse_configuration_error, USS_message_code_SAPH_invalid_rx_charge_pump_mode_error, USS_message_code_SAPH_numOfExcitationPulses_error, USS_message_code_SAPH_numOfStopPulses_error, USS_message_code_SAPH_pulseHighPhasePeriod_error, USS_message_code_SAPH_pulseLowPhasePeriod_error, USS_message_code_SAPH_time_captureTimeOutCount_error, USS_message_code_SAPH_time_restartCaptureCount_error, USS_message_code_SAPH_time_startADCsamplingCount_error, USS_message_code_SAPH_time_startPGAandINBiasCount_error, USS_message_code_SAPH_time_startPPGCount_error, USS_message_code_SAPH_time_turnOnADCCount_error, USS_SAPH_MAX_STOP_PULSES, USS_silicon_version_A, USS_silicon_version_variant_FR6047, X_HPER_STATE, and X_LPER_STATE.
Referenced by USS_updateSAPHConfiguration().
commonValidateSDHSconfigruation()
USS_message_code commonValidateSDHSconfigruation (USS_SW_Library_configuration * config)
References _USS_SW_Library_configuration_::captureConfig, _USS_Capture_Configuration_::enableWindowHiComp, _USS_Capture_Configuration_::enableWindowLoComp, _USS_Capture_Configuration_::maxCapture, _USS_SW_Library_configuration_::pllConfiguration, _USS_HSPLL_Configuration_::pllOutputFreq, _USS_Capture_Configuration_::sampleSize, USS_HSPLL_output_clk_freq_68_MHz, USS_message_code_HSPLL_pllXtalFreq_inHz_error, USS_message_code_no_error, USS_message_code_SDHS_max_size_error, USS_message_code_SDHS_sample_size_error, USS_message_code_SDHS_threshold_error, _USS_Capture_Configuration_::windowHighThreshold, and _USS_Capture_Configuration_::windowLowThreshold.
Referenced by USS_updateSDHSConfiguration().
commonSDHSRestoreSDHSDTCA()
void commonSDHSRestoreSDHSDTCA (USS_SW_Library_configuration * config) inline
References _USS_SW_Library_configuration_::algorithmsConfig, _USS_SW_Library_configuration_::captureConfig, _USS_Algorithms_User_Configuration_::filterLength, and _USS_Capture_Configuration_::pCapturesBuffer.
Referenced by USS_startLowPowerUltrasonicCapture(), USS_startUltrasonicMeasurement(), USS_testSDHSconversion(), USS_updateSDHSConfiguration(), and USS_verifyHSPLLFrequency().
commonSDHSConfigModOpt()
void commonSDHSConfigModOpt (USS_SW_Library_configuration * config) inline
References _USS_SW_Library_configuration_::pllConfiguration, _USS_HSPLL_Configuration_::pllOutputFreq, USS_HSPLL_output_clk_freq_71_MHz, USS_HSPLL_output_clk_freq_72_MHz, USS_HSPLL_output_clk_freq_73_MHz, USS_HSPLL_output_clk_freq_74_MHz, USS_HSPLL_output_clk_freq_75_MHz, USS_HSPLL_output_clk_freq_76_MHz, USS_HSPLL_output_clk_freq_77_MHz, USS_HSPLL_output_clk_freq_78_MHz, USS_HSPLL_output_clk_freq_79_MHz, and USS_HSPLL_output_clk_freq_80_MHz.
Referenced by USS_updateHSPLLConfiguration(), and USS_updateSDHSConfiguration().
commonTimerGenerateLowPowerDelay()
void commonTimerGenerateLowPowerDelay (USS_SW_Library_configuration * config, uint16_t delay, USS_low_power_mode_option lpmMode)
References commonClearCCFlagStart(), commonTimerConfigureDelay(), commonTimerDisableInterrupt(), commonTimerEnableInterrupt(), commonTimerStart(), commonTimerStop(), USS_TIMER_EXPIRED_INTERRUPT, and USSSWLIB_USS_interrupt_status.
Referenced by commonStabilizeOscillator(), commonTimerConfigureTimer(), USS_commonTriggerSingleCapture(), USS_generateLPMDelay(), and USS_stopUltrasonicMeasurement().
commonClearCCFlagStart()
void commonClearCCFlagStart (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay().
commonTimerConfigureDelay()
void commonTimerConfigureDelay (USS_SW_Library_configuration * config, uint16_t delay)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay().
commonTimerStart()
void commonTimerStart (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay(), and commonTimerPeriodMeasurementStart().
commonTimerStop()
void commonTimerStop (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay().
commonTimerEnableInterrupt()
void commonTimerEnableInterrupt (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay().
commonTimerDisableInterrupt()
void commonTimerDisableInterrupt (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerGenerateLowPowerDelay().
commonTimerPollInterruptFlag()
bool commonTimerPollInterruptFlag (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
commonTimerClear()
void commonTimerClear (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
commonTimerConfigureTimer()
bool commonTimerConfigureTimer (USS_SW_Library_configuration * config) inline
References commonTimerGenerateLowPowerDelay(), HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, _USS_System_Configuration_::timerBaseAddress, and USS_low_power_mode_option_low_power_mode_3.
commonTimerConfigurePeriodMeasurement()
void commonTimerConfigurePeriodMeasurement (USS_SW_Library_configuration * config, uint16_t delay1, uint16_t delay2)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by USS_verifyHSPLLFrequency().
commonTimerPeriodMeasurementClear()
void commonTimerPeriodMeasurementClear (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, _USS_System_Configuration_::timerBaseAddress, USS_TIMER_EXPIRED_EVENT1_INTERRUPT, USS_TIMER_EXPIRED_INTERRUPT, and USSSWLIB_USS_interrupt_status.
Referenced by commonTimerPeriodMeasurementStart(), and USS_verifyHSPLLFrequency().
commonTimerPeriodMeasurementEnableInterrupts()
void commonTimerPeriodMeasurementEnableInterrupts (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
Referenced by commonTimerPeriodMeasurementStart().
commonTimerPeriodMeasurementDisableInterrupts()
void commonTimerPeriodMeasurementDisableInterrupts (USS_SW_Library_configuration * config)
References HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, and _USS_System_Configuration_::timerBaseAddress.
commonTimerPeriodMeasurementStart()
void commonTimerPeriodMeasurementStart (USS_SW_Library_configuration * config)
References commonTimerPeriodMeasurementClear(), commonTimerPeriodMeasurementEnableInterrupts(), and commonTimerStart().
Referenced by USS_verifyHSPLLFrequency().
commonTimerPeriodMeasurementWaitEvent1()
void commonTimerPeriodMeasurementWaitEvent1 (USS_SW_Library_configuration * config, USS_low_power_mode_option lpmMode)
Referenced by USS_verifyHSPLLFrequency().
commonTimerPeriodMeasurementWaitEvent2()
void commonTimerPeriodMeasurementWaitEvent2 (USS_SW_Library_configuration * config, USS_low_power_mode_option lpmMode)
Referenced by USS_verifyHSPLLFrequency().
commonPowerUpUSS()
USS_message_code commonPowerUpUSS (USS_SW_Library_configuration * config)
References USS_message_code_no_error, and USS_message_code_UUPS_power_up_error.
Referenced by commonConfigurePPGForManualMode(), USS_startPPGToneGeneration(), USS_startUltrasonicMeasurement(), USS_testSDHSconversion(), and USS_verifyHSPLLFrequency().
commonPowerDownUSS()
USS_message_code commonPowerDownUSS (USS_SW_Library_configuration * config)
References commonPrepareForUSSPowerUp(), and USS_message_code_no_error.
Referenced by USS_stopPPGToneGeneration(), and USS_testPPGconfiguration().
commonIsconversionSuccessfull()
USS_message_code commonIsconversionSuccessfull (USS_SW_Library_configuration * config)
References _USS_SW_Library_configuration_::captureConfig, commonDisableCaptureInterrupts(), _USS_Capture_Configuration_::enableWindowHiComp, _USS_Capture_Configuration_::enableWindowLoComp, USS_HSPLL_PLL_UNLOCK_INTERRUPT, USS_message_code_ASQ_time_out, USS_message_code_data_error_abort, USS_message_code_error_conversion_stopped_by_debugger, USS_message_code_error_occurred, USS_message_code_HSPLL_pll_unlock_error, USS_message_code_invalid_conversion_data, USS_message_code_measurement_stopped, USS_message_code_no_error, USS_message_code_SDHS_window_high_threshold_reached, USS_message_code_SDHS_window_low_threshold_reached, USS_message_code_UUPS_power_up_time_out_error, USS_SAPH_DATA_ERR_ABORT_INTERRUPT, USS_SAPH_PING_DN_INTERRUPT, USS_SAPH_SEQ_ACQ_DN_INTERRUPT, USS_SAPH_SEQUENCE_STOPPED, USS_SAPH_TMF_TM_OUT_INTERRUPT, USS_SDHS_ACQDONE_INTERRUPT, USS_SDHS_WINHI_INTERRUPT, USS_SDHS_WINLO_INTERRUPT, USS_UUPS_PWR_UP_TM_OUT_INTERRUPT, USS_UUPS_STOPPED_BY_DEBUGGER, and USSSWLIB_USS_interrupt_status.
Referenced by USS_commonTriggerSingleCapture(), USS_startUltrasonicMeasurement(), and USS_testSDHSconversion().
commonDecodeSDHSDTCDAoffset()
uint16_t commonDecodeSDHSDTCDAoffset (USS_SW_Library_configuration * config)
commonWaitForconversion()
void commonWaitForconversion (USS_capture_power_mode_option mode)
References commonUpdateUSSULPbiasDelay(), USS_capture_power_mode_active, USS_HSPLL_PLL_UNLOCK_INTERRUPT, USS_SAPH_SEQ_ACQ_DN_INTERRUPT, USS_SAPH_SEQUENCE_STOPPED, USS_SDHS_ACQDONE_INTERRUPT, USS_UUPS_PWR_UP_TM_OUT_INTERRUPT, USS_UUPS_STOPPED_BY_DEBUGGER, and USSSWLIB_USS_interrupt_status.
Referenced by USS_commonTriggerSingleCapture(), USS_startUltrasonicMeasurement(), and USS_testSDHSconversion().
commonPrepareForUSSPowerUp()
USS_message_code commonPrepareForUSSPowerUp (USS_SW_Library_configuration * config)
References commonStabilizeOscillator(), USS_message_code_no_error, and USS_message_code_USS_ongoing_active_conversion_error.
Referenced by commonConfigurePPGForManualMode(), commonPowerDownUSS(), USS_startPPGToneGeneration(), USS_startUltrasonicMeasurement(), USS_testSDHSconversion(), and USS_verifyHSPLLFrequency().
commonUpdateUSSULPbiasDelay()
USS_message_code commonUpdateUSSULPbiasDelay (USS_SW_Library_configuration * config)
References commonDetermineSiliconVersion(), commonDetermineVariant(), GENERIC_SAPH_KEY, GENERIC_SAPH_MCNF, GENERIC_SAPH_TACTL, LBHDEL_0, LBHDEL_1, LBHDEL_2, LBHDEL_3, LPBE, _USS_SW_Library_configuration_::measurementConfig, _USS_Measurement_Configuration_::ulpBiasDelay, USS_measurement_ULP_bias_delay_100_usec, USS_measurement_ULP_bias_delay_200_usec, USS_measurement_ULP_bias_delay_300_usec, USS_message_code_no_error, USS_silicon_version_A, USS_silicon_version_not_supported, USS_silicon_version_variant_FR6043, and USS_silicon_version_variant_FR6047.
Referenced by commonWaitForconversion(), and USS_updateSAPHConfiguration().
commonDetermineSiliconVersion()
USS_silicon_version commonDetermineSiliconVersion (void)
References DEVICE_HW_ID, USS_silicon_version_A, USS_silicon_version_B, and USS_silicon_version_not_supported.
Referenced by commonUpdateUSSULPbiasDelay(), commonValidateSAPHconfigruation(), USS_resetUSSModule(), and USS_updateSAPHConfiguration().
commonDetermineVariant()
USS_silicon_variant commonDetermineVariant (void)
References DEVICE_ID, USS_silicon_version_variant_FR6043, USS_silicon_version_variant_FR6047, and USS_silicon_version_variant_not_supported.
Referenced by commonUpdateUSSULPbiasDelay(), commonValidateSAPHconfigruation(), USS_resetUSSModule(), and USS_updateSAPHConfiguration().
Variable Documentation
gUSSGainLookUp
const float gUSSGainLookUp[AGC_GAIN_TABLE_SIZE]
Referenced by USS_calibrateSignalGain(), and USS_findAGCIndex().
© Copyright 1995-2019, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale