MSP430UltrasonicLibrary: Applicationdebug_api
Applicationdebug_api
Functions
USS_message_code USS_testPPGconfiguration (USS_SW_Library_configuration *config, USS_test_channel PPGChannel)
The following API will output current PPG configuration.
PPG configuration is controlled via the following USS_Measurement_Configuration parameter:
USS_message_code USS_testSDHSconversion (USS_SW_Library_configuration *config, USS_test_channel SDHSChannel, USS_capture_power_mode_option mode)
The following trigger manual SDHS conversion with current SDHS configuration. SDHS configuration is controlled via the USS_Measurement_Configuration struct and .
The API will perform the following operations:
USS_message_code USS_startPPGToneGeneration (USS_SW_Library_configuration *config, USS_test_channel PPGChannel)
The following API will the tone generation output in the SAPH module.
Tone generation is controlled via the following USS_Measurement_Configuration parameter:
USS_message_code USS_stopPPGToneGeneration (USS_SW_Library_configuration *config)
The following API will stop the tone generation output in the SAPH module.
int16_t * USS_getUPSPtr (USS_SW_Library_configuration *config)
The following API allows to obtain the address were UPS capture starts. IMPORTANT: USS_configureUltrasonicMeasurement API must be call in the application first before using this API.
int16_t * USS_getDNSPtr (USS_SW_Library_configuration *config)
The following API allows to obtain the address were DNS capture starts. IMPORTANT: USS_configureUltrasonicMeasurement API must be call in the application first before using this API.
Detailed Description
Function Documentation
USS_testPPGconfiguration()
USS_message_code USS_testPPGconfiguration (USS_SW_Library_configuration * config, USS_test_channel PPGChannel)
The following API will output current PPG configuration.
PPG configuration is controlled via the following USS_Measurement_Configuration parameter:
pulsePolarity
pulseLowPhasePeriod
pulseHighPhasePeriod
isPPGPrescaler
numOfExcitationPulses
numOfStopPulses
The user can select the USS channel to test the PPG via the "pPGChannel" input parameter.
Parameters
[in] config is a pointer to the USS SW Library user configuration.
[in] PPGChannel The following are valid options:
USS_test_channel_0
USS_test_channel_1
Returns
USS_message_code
References commonConfigurePPGForManualMode(), commonPowerDownUSS(), commonTurnOffHSPLLXTAL(), GENERIC_SAPH_KEY, GENERIC_SAPH_PPGTRIG, USS_message_code_no_error, USS_updateSAPHConfiguration(), and USS_updateUUPSConfiguration().
USS_testSDHSconversion()
USS_message_code USS_testSDHSconversion (USS_SW_Library_configuration * config, USS_test_channel SDHSChannel, USS_capture_power_mode_option mode)
The following trigger manual SDHS conversion with current SDHS configuration. SDHS configuration is controlled via the USS_Measurement_Configuration struct and .
The API will perform the following operations:
Verify if USS state is READY
If USS is not READY state (e.g. OFF or STANDBY) it will set USS to READY state following recommended USS Power Up sequence.
Triggers manual USS Capture
Wait in user selected power mode (USS_capture_power_mode_option) until acquisition sequence is done or any of the following errors occurs:
Data Overflow
Over Input Level
Verifies that SDHS conversion has not been interrupted
Parameters
[in] config is a pointer to the USS SW Library user configuration.
[in] SDHSChannel The following are valid options:
USS_test_channel_0
USS_test_channel_1
[in] mode Specifies the capture mode, valid modes are (active or LMP0)
Returns
USS_message_code
References commonClearUSSInterrupts(), commonEnableManualSDHSTriggerInterrupts(), commonIsconversionSuccessfull(), commonPowerUpUSS(), commonPrepareForUSSPowerUp(), commonSDHSRestoreSDHSDTCA(), commonWaitForconversion(), GENERIC_SAPH_BCTL, GENERIC_SAPH_ICTL0, GENERIC_SAPH_KEY, HARDWAREWREG16, _USS_SW_Library_configuration_::systemConfig, _USS_System_Configuration_::timerBaseAddress, USS_message_code_no_error, USS_updateHSPLLConfiguration(), and USS_updateSDHSConfiguration().
USS_startPPGToneGeneration()
USS_message_code USS_startPPGToneGeneration (USS_SW_Library_configuration * config, USS_test_channel PPGChannel)
The following API will the tone generation output in the SAPH module.
Tone generation is controlled via the following USS_Measurement_Configuration parameter:
pulsePolarity
pulseLowPhasePeriod
pulseHighPhasePeriod
isPPGPrescaler
The user can select the USS channel to test the PPG via the "pPGChannel" input parameter.
Parameters
[in] config is a pointer to the USS SW Library user configuration.
[in] PPGChannel The following are valid options:
USS_test_channel_0
USS_test_channel_1
Returns
USS_message_code
References commonConfigurePPGDutyCyle(), commonPowerUpUSS(), commonPrepareForUSSPowerUp(), GENERIC_SAPH_KEY, GENERIC_SAPH_PGCTL, _USS_SW_Library_configuration_::measurementConfig, _USS_Measurement_Configuration_::pulseConfig, _USS_Pulse_Configuration_::pulseGenMode, USS_message_code_no_error, USS_test_channel_1, and USS_updateHSPLLConfiguration().
USS_stopPPGToneGeneration()
USS_message_code USS_stopPPGToneGeneration (USS_SW_Library_configuration * config)
The following API will stop the tone generation output in the SAPH module.
Parameters
[in] config is a pointer to the USS SW Library user configuration.
Returns
USS_message_code
References commonPowerDownUSS(), commonTurnOffHSPLLXTAL(), GENERIC_SAPH_KEY, GENERIC_SAPH_PGCTL, USS_message_code_no_error, USS_updateSAPHConfiguration(), and USS_updateUUPSConfiguration().
USS_getUPSPtr()
int16_t* USS_getUPSPtr (USS_SW_Library_configuration * config)
The following API allows to obtain the address were UPS capture starts. IMPORTANT: USS_configureUltrasonicMeasurement API must be call in the application first before using this API.
Returns
address to first UPS capture
Referenced by USS_calibrateSignalGain(), and USS_estimateDCoffset().
USS_getDNSPtr()
int16_t* USS_getDNSPtr (USS_SW_Library_configuration * config)
The following API allows to obtain the address were DNS capture starts. IMPORTANT: USS_configureUltrasonicMeasurement API must be call in the application first before using this API.
Returns
address to first DNSS capture
Referenced by USS_calibrateSignalGain(), and USS_estimateDCoffset().
© Copyright 1995-2019, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale