var jsonObjASM = [
	{"SourcePreview" : "msp430F66xx_adc12_01.asm",          "Description" : "ADC12, Sample A0, Set P1.0 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430F66xx_adc12_02.asm",          "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "msp430F66xx_adc12_05.asm",          "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "",                                  "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "",                                  "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "",                                  "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "msp430F66xx_compB_01.asm",          "Description" : "LPM4.5, Backup RAM"},
	{"SourcePreview" : "msp430F66xx_compB_02.asm",          "Description" : "COMPB output Toggle in LPM4; "},
	{"SourcePreview" : "msp430F66xx_compB_03.asm",          "Description" : "COMPB output Toggle from LPM4; input channel CB1; "},
	{"SourcePreview" : "msp430F66xx_compB_04.asm",          "Description" : "COMPB interrupt capability; "},
	{"SourcePreview" : "msp430f66xx_crc16_01.asm",          "Description" : "COMPB Toggle from LPM4; Ultra low power mode; "},
	{"SourcePreview" : "msp430f66xx_crc16_02.asm",          "Description" : "CRC16, Compare CRC output with software-based algorithm"},
	{"SourcePreview" : "msp430F66xx_dac12_01.asm",          "Description" : "CRC16, fed by DMA, compare w/ software algorithm"},
	{"SourcePreview" : "",                                  "Description" : "DAC12_0, Output 1.5V on DAC0"},
	{"SourcePreview" : "msp430F66xx_dac12_03.asm",          "Description" : "DAC12_1, Output 0.75V on DAC1"},
	{"SourcePreview" : "msp430F66xx_dma_01.asm",            "Description" : "DAC12_0, Output Voltage Ramp on DAC0"},
	{"SourcePreview" : "",                                  "Description" : "DMA0, Repeated Block to-from RAM, Software Trigger"},
	{"SourcePreview" : "",                                  "Description" : "Single-Byte Flash In-System Programming, Copy SegC to SegD"},
	{"SourcePreview" : "msp430f66xx_LPM35_RTC.asm",         "Description" : "Flash In-System Programming w/ Long-Word write at 0x1800"},
	{"SourcePreview" : "msp430F66xx_LPM3_01.asm",           "Description" : "Enters LPM3 with ACLK = LFXT1, REF0 disabled, VUSB LDO and SLDO disabled, SVS disabled"},
	{"SourcePreview" : "msp430F66xx_LPM3_03.asm",           "Description" : "Enters LPM3 with ACLK =VLO, REF0 disabled, VUSB LDO and SLDO disabled, SVS default state"},
	{"SourcePreview" : "msp430f66xx_LPM45_BAKMEM.asm",      "Description" : "16x16 Unsigned Multiply"},
	{"SourcePreview" : "msp430F66xx_MPY_1.asm",             "Description" : "32x32 Signed Multiply"},
	{"SourcePreview" : "msp430F66xx_MPY_10.asm",            "Description" : "32x32 Signed Multiply Accumalate"},
	{"SourcePreview" : "",                                  "Description" : "RTC_B in real time clock mode"},
	{"SourcePreview" : "msp430f66xx_rtc_01.asm",            "Description" : "RTC_B, LPM3.5, & alarm"},
	{"SourcePreview" : "msp430F66xx_ta1_01.asm",            "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430F66xx_ta1_03.asm",            "Description" : "Timer1_A3, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, Toggle P1.7/TA1.0, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430F66xx_tb_01.asm",             "Description" : "Timer_B, Toggle P1.0, CCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer_B, Toggle P1.0, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer_B, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer_B, Toggle P1.0, CCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "",                                  "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "msp430F66xx_UCS_5.asm",             "Description" : "VLO sources ACLK"},
	{"SourcePreview" : "",                                  "Description" : "XT1 sources ACLK"},
	{"SourcePreview" : "",                                  "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430F66xx_UCS_8.asm",             "Description" : "XT2 sources MCLK & SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "USCI_B0 I2C Master TX single bytes to MSP430 Slave"},
	{"SourcePreview" : "",                                  "Description" : "USCI_B0 I2C Slave RX single bytes from MSP430 Master"},
	{"SourcePreview" : "msp430F66xx_wdt_01.asm",            "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430F66xx_wdt_04.asm",            "Description" : "WDT+ Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "",                                  "Description" : "Reset on Invalid Address fetch, Toggle P1.0"}
];

