var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430C09x",
		"Filter" : "MSP430C09\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x09x_1",                         "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430x09x_api_loader_functions",      "Description" : "Demonstration of calling various API functions in ROM"},
	{"SourcePreview" : "msp430x09x_apool_adc_01",              "Description" : "APOOL_ADC, conversion without Error Compensation, Sample A0"},
	{"SourcePreview" : "msp430x09x_apool_adc_02",              "Description" : "APOOL_ADC, conversion with Overdrive Compensation, Sample A0"},
	{"SourcePreview" : "msp430x09x_apool_adc_03",              "Description" : "APOOL_ADC, conversion with Offset Compensation, Sample A0"},
	{"SourcePreview" : "msp430x09x_apool_adc_04",              "Description" : "APOOL_ADC, Vcc Monitoring"},
	{"SourcePreview" : "msp430x09x_apool_adc_05",              "Description" : "APOOL_ADC, Timer_A0 Triggered"},
	{"SourcePreview" : "msp430x09x_apool_adc_06",              "Description" : "APOOL_ADC, Sampled Temperature and Convert to oC "},
	{"SourcePreview" : "msp430x09x_apool_adc_07",              "Description" : "APOOL_ADC, Sample Multiple ADC Channels"},
	{"SourcePreview" : "msp430x09x_apool_comp_01",             "Description" : "APOOL_COMPARATOR, Comparator in Compensated Mode, Compare signals on A0 and A2 "},
	{"SourcePreview" : "msp430x09x_apool_comp_02",             "Description" : "APOOL_COMPARATOR, Comparator in Non Compensated Mode, Compare signals on A0 and A2 "},
	{"SourcePreview" : "msp430x09x_apool_comp_03",             "Description" : "APOOL_COMPARATOR, Comparator in Compensated Mode,A0 compared with internal reference"},
	{"SourcePreview" : "msp430x09x_apool_dac_01",              "Description" : "APOOL_DAC, Output Analog Signal with write to APINT; "},
	{"SourcePreview" : "msp430x09x_apool_dac_02",              "Description" : "APOOL_DAC, Output Triangle Wave using APINT with Timer Interrupt; "},
	{"SourcePreview" : "msp430x09x_apool_dac_03",              "Description" : "APOOL_DAC, Output Triangle Wave using APFRACT_H with Timer Interrupt;"},
	{"SourcePreview" : "msp430x09x_ccs_clkin",                 "Description" : "External Clock source for ACLK, MCLK, and SMCLK "},
	{"SourcePreview" : "msp430x09x_ccs_hfosc",                 "Description" : "HF Clock source for ACLK(1MHz), MCLK(1MHz), and SMCLK(1MHz) "},
	{"SourcePreview" : "msp430x09x_ccs_hfosc_01",              "Description" : "HF Clock source for ACLK(~62.5kHz), MCLK(~250kHz), and SMCLK(~1MHz) "},
	{"SourcePreview" : "msp430x09x_ccs_hfosc_02",              "Description" : "HF Clock source for ACLK(~125kHz), MCLK(~62.5kHz), and SMCLK(~32kHz)"},
	{"SourcePreview" : "msp430x09x_ccs_hfosc_03",              "Description" : "HF Clock source for ACLK(~32kHz), MCLK(~125kHz), and SMCLK(~62.5kHz)"},
	{"SourcePreview" : "msp430x09x_ccs_lfosc",                 "Description" : "LF Clock source for ACLK(~17.9kHz), MCLK(~17.9kHz), and SMCLK (~17.9kHz) "},
	{"SourcePreview" : "msp430x09x_ccs_lfosc_01",              "Description" : "LF Clock source for ACLK(~9kHz), MCLK(~2.2kHz), and SMCLK(~1kHz)"},
	{"SourcePreview" : "msp430x09x_ccs_lfosc_02",              "Description" : "LF Clock source for ACLK(~4.5 kHz), MCLK(~17.9kHz), and SMCLK(~9kHz)"},
	{"SourcePreview" : "msp430x09x_ccs_lfosc_03",              "Description" : "LF Clock source for ACLK(~17.9kHz), MCLK(~2.2kHz), and SMCLK (~4.5kHz)"},
	{"SourcePreview" : "msp430x09x_lpm3",                      "Description" : "LPM3, WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x09x_p1_01",                     "Description" : "Software Poll P1.3, Set P1.0 if P1.3 = 1"},
	{"SourcePreview" : "msp430x09x_p1_02",                     "Description" : "Software Port Interrupt Service on P1.3 from LPM4 which Toggles P1.0 "},
	{"SourcePreview" : "msp430x09x_p1_03",                     "Description" : "Software Port Interrupt Service on P1.3 from LPM4 with internal Pull up"},
	{"SourcePreview" : "msp430x09x_sys_01",                    "Description" : "Toggle P1.0 using system NMI ISR: VMA"},
	{"SourcePreview" : "msp430x09x_ta_01",                     "Description" : "Timer_A, Toggle P1.0, CCR0 Cont. Mode ISR, LFCLK/VLO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_02",                     "Description" : "Timer_A, Toggle P1.0, CCR0 Up Mode ISR, LFCLK/VLO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_03",                     "Description" : "Timer_A, Toggle P1.0, Overflow ISR, HFCLK/DCO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_04",                     "Description" : "Timer_A, Toggle P1.0, Overflow ISR, CLKIN SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_06",                     "Description" : "Timer_A, Toggle P1.0, TACCR1 Cont. Mode ISR, HFCLK/DCO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_07",                     "Description" : "Timer_A, Toggle P1.5-6, Cont. Mode ISR, HFCLK/DCO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_08",                     "Description" : "Timer_A, Toggle P1.5-6, Cont. Mode ISR, CLKIN SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_16",                     "Description" : "Timer_A, PWM TA1.1-2, Up Mode, HFCLK/DCO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_17",                     "Description" : "TimerA, PWM TA1.1-2, Up Mode, CLKIN SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_18",                     "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, CLKIN ACLK"},
	{"SourcePreview" : "msp430x09x_ta_19",                     "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, HFCLK/DCO SMCLK"},
	{"SourcePreview" : "msp430x09x_ta_20",                     "Description" : "Timer1_A3, PWM TA1.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x09x_ta_21",                     "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, CLKIN ACLK"},
	{"SourcePreview" : "msp430x09x_wdt_01",                    "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, LF-OSC ACLK"},
	{"SourcePreview" : "msp430x09x_wdt_02",                    "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, HF-OSC SMCLK"},
	{"SourcePreview" : "msp430x09x_wdt_04",                    "Description" : "WDT, Reset on Invalid Address fetch, Toggle P1.0"}
];

