var jsonObjASM = [
	{"SourcePreview" : "msp430fr413x_1.asm",                    "Description" : "Toggle P1.0 using software"},
	{"SourcePreview" : "msp430fr413x_adc10_01.asm",             "Description" : "ADC, Sample A1, AVcc Ref, Set LED if A1 > 0.5*AVcc"},
	{"SourcePreview" : "msp430fr413x_adc10_02.asm",             "Description" : "ADC, Sample A1, internal 1.5V Ref, Set P1.0 if A1 > 0.5V"},
	{"SourcePreview" : "msp430fr413x_adc10_10.asm",             "Description" : "ADC, Sample A2/A1/A0, internal 1.5V Ref."},
	{"SourcePreview" : "msp430fr413x_adc10_11.asm",             "Description" : "ADC, Sample A1, internal 1.5V Ref, TA0.1 Trig, Set P1.0 if A1>0.5V"},
	{"SourcePreview" : "msp430fr413x_adc10_21.asm",             "Description" : "ADC, Window Comparator, 1.5V ref, Timer trigger, DCO"},
	{"SourcePreview" : "msp430fr413x_CRC.asm",                  "Description" : "CRC16, Compare CRC output with software-based algorithm"},
	{"SourcePreview" : "msp430fr413x_CS_01.asm",                "Description" : "Configure MCLK for 8MHz sourced from DCO."},
	{"SourcePreview" : "msp430fr413x_CS_02.asm",                "Description" : "Configure MCLK for 8MHz and XT1 sourcing ACLK and FLLREF"},
	{"SourcePreview" : "msp430fr413x_CS_03.asm",                "Description" : "Configure MCLK for 16MHz operation, and REFO sourcing FLLREF and ACLK"},
	{"SourcePreview" : "msp430fr413x_CS_05.asm",                "Description" : "Configure MCLK for 16MHz operation, and XT1 sourcing FLLREF and ACLK"},
	{"SourcePreview" : "msp430fr413x_euscia0_uart_01.asm",      "Description" : ""},
	{"SourcePreview" : "msp430fr413x_euscia0_uart_03.asm",      "Description" : ""},
	{"SourcePreview" : "msp430fr413x_framwrite.asm",            "Description" : "Long word writes to FRAM"},
	{"SourcePreview" : "msp430fr413x_LPM3_01.asm",              "Description" : "Enters LPM3 with ACLK = XT1CLK = 32768Hz."},
	{"SourcePreview" : "msp430fr413x_P1_01.asm",                "Description" : "Software Poll P1.3, Set P1.0 if P1.3 = 1"},
	{"SourcePreview" : "msp430fr413x_P1_03.asm",                "Description" : "Software Port Interrupt Service on P1.3 from LPM3"},
	{"SourcePreview" : "msp430fr413x_ta0_01.asm",               "Description" : "Timer0_A3, Toggle P1.0, CCR0 Count Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_ta0_02.asm",               "Description" : "Timer0_A3, Toggle P1.0, CCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_ta0_04.asm",               "Description" : "Timer0_A3, Toggle P1.0, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr413x_ta0_16.asm",               "Description" : "Timer0_A3, PWM TA0.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_ta0_17.asm",               "Description" : "Timer0_A3, PWM TA0.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr413x_ta0_20.asm",               "Description" : "Timer0_A3, PWM TA0.1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr413x_ta0_22.asm",               "Description" : "Timer_A, Ultra-Low Pwr Pulse Accumulator"},
	{"SourcePreview" : "msp430fr413x_ta0_capture.asm",          "Description" : "Timer0_A3 Capture of ACLK"},
	{"SourcePreview" : "msp430fr413x_ta1_05.asm",               "Description" : "Timer1_A3, Toggle P1.0, CCR0 Cont Mode ISR, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr413x_ta1_06.asm",               "Description" : "Timer1_A3, Toggle P1.0, CCR0 UP Mode ISR, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr413x_ta1_16.asm",               "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_ta1_17.asm",               "Description" : "Timer1_A3, PWM TA1.1-2, Up Mode, 32KHz ACLK"},
	{"SourcePreview" : "msp430fr413x_uscia0_spi_09.asm",        "Description" : "eUSCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr413x_uscia0_spi_10.asm",        "Description" : "eUSCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr413x_uscia0_spi_11.asm",        "Description" : "eUSCI_A0, SPI 4-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430fr413x_uscia0_spi_12.asm",        "Description" : "eUSCI_A0, SPI 4-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430fr413x_WDT_01.asm",               "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_WDT_02.asm",               "Description" : "WDT, Toggle P1.0, Interval Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430fr413x_WDT_04.asm",               "Description" : "WDT,  Failsafe Clock, WDT mode, DCO SMCLK"},
	{"SourcePreview" : "msp430fr413x_WDT_05.asm",               "Description" : "WDT,  Reset on Invalid Address fetch, Toggle P1.0"},
	{"SourcePreview" : "msp430fr413x_WDT_06.asm",               "Description" : "WDT,  Failsafe Clock, WDT mode, 32kHz ACLK"}
];

