SMBus Library for MSP430G2xx3 Devices: Application API layer
Application API layer
Data Structures
union SMBus_Ctrl
SMBus control register.
struct SMBus_Phy
Physical and Data Link Layer object.
struct SMBus_Nwk
Definition of SMBus Network structure.
union SMBus_Status
SMBus Status Register.
struct SMBus
Main SMBus object.
Macros
#define SMB_PEC_SUPPORTED (1)
Define to support Packet Error Checking (PEC)
#define SMB_MANUAL_ACK_ENABLE (0)
Define to enable Manual ACK workaround.
#define SMB_CRC8_USE_LOOKUP_TABLE (1)
#define SMB_MAX_PAYLOAD_SIZE (32)
Maximum payload as specified by SMBus Spec.
#define SMB_MAX_PACKET_SIZE (SMB_MAX_PAYLOAD_SIZE + 3)
Max packet size = Payload+PEC+CMD+Len.
#define RESPONSE_NTR 0x00
Default response when there's nothing to send.
#define SMBUS_RET_OK (1)
Return value when successful.
#define SMBUS_RET_ERROR (-1)
Return value when an error ocurred.
Enumerations
enum SMBus_Stop {
SMBus_Stop_No = 0, SMBus_Stop_Immediate, SMBus_Stop_Addr, SMBus_Stop_PreRead,
SMBus_Stop_Sent
}
List of stop codes used within the NWK and PHY layers.
enum SMBus_NwkState {
SMBus_NwkState_Idle = 0, SMBus_NwkState_RX, SMBus_NwkState_TX, SMBus_NwkState_TXQuickCMD,
SMBus_NwkState_TX_Resp, SMBus_NwkState_TX_Block, SMBus_NwkState_RX_Block, SMBus_NwkState_Ending,
SMBus_NwkState_Error
}
SMBus network layer states.
enum SMBus_ErrorCode { SMBus_ErrorCode_NoError = 0, SMBus_ErrorCode_Packet, SMBus_ErrorCode_Cmd }
List of error codes used by the application to indicate an error to the library.
enum SMBus_State {
SMBus_State_OK = 0, SMBus_State_DataSizeError, SMBus_State_PECError, SMBus_State_TimeOutError,
SMBus_State_Slave_FirstByte, SMBus_State_Slave_ByteReceived, SMBus_State_Slave_QCMD, SMBus_State_Slave_CmdComplete,
SMBus_State_Slave_Error, SMBus_State_Slave_NotReady, SMBus_State_Slave_NTR, SMBus_State_Master_ArbLost,
SMBus_State_Master_NACK, SMBus_State_Master_Error, SMBus_State_Unknown
}
SMBus state sent to application layer.
Functions
void SMBus_processDone (SMBus *smbus)
Clears the current state of SMBus.
uint8_t SMBus_getRxPayloadAvailable (SMBus *smbus)
Returns the number of received bytes from last transaction.
SMBus_State SMBus_getState (SMBus *smbus)
Returns the state of the SMBus module.
void SMBus_enablePEC (SMBus *smbus)
Enables PEC support.
void SMBus_disablePEC (SMBus *smbus)
Disables PEC support.
void SMBus_slaveInit (SMBus *smbus, uint16_t i2cAddr)
Initialize the SMBus interface as a slave.
void SMBus_slaveEnableInt (SMBus *smbus)
Enables the I2C interrupts for a slave.
SMBus_State SMBus_slaveProcessInt (SMBus *smbus)
I2C Interrupt Service routine for a slave.
void SMBus_masterReset (SMBus *smbus)
Force reset to SMBus master interface.
SMBus_State SMBus_slaveProcessTimeoutInt (SMBus *smbus)
Timer interrupt service routine for slave application.
void SMBus_slaveSetAddress (SMBus *smbus, uint8_t slaveAddr)
Set the slave's own I2C address.
void SMBus_slaveSetRxBuffer (SMBus *smbus, uint8_t *data, uint8_t size)
Initialize the reception buffer for slave.
void SMBus_slaveSetTxBuffer (SMBus *smbus, uint8_t *data, uint8_t size)
Initialize the transmission buffer for slave.
void SMBus_slaveReportError (SMBus *smbus, SMBus_ErrorCode errorCode)
Reports an error to SMBus driver from the slave.
uint8_t SMBus_slaveGetCommand (SMBus *smbus)
Return the current command (Rxbuffer[0]) received by the slave.
uint8_t SMBus_slaveClearStatusReg (SMBus *smbus, uint8_t val)
Clear the slave's status register.
uint8_t SMBus_slaveWriteCtrlReg (SMBus *smbus, uint8_t val)
Write a value to the slave's control register.
void SMBus_masterInit (SMBus *smbus, uint16_t i2cAddr, uint32_t busClk)
Initialize the SMBus Interface for a master.
void SMBus_masterEnableInt (SMBus *smbus)
Enables the I2C interrupts for a master.
SMBus_State SMBus_masterProcessInt (SMBus *smbus)
I2C Interrupt Service routine for a master.
SMBus_State SMBus_masterProcessTimeoutInt (SMBus *smbus)
Timer interrupt service routine for a master.
int8_t SMBus_masterProcessCall (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *txData, uint8_t *rxData)
Sends a process call to a slave.
int8_t SMBus_masterProcessCallBlock (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *txData, uint8_t txSize, uint8_t *rxData)
Sends a block write-block read process call.
int8_t SMBus_masterSendByte (SMBus *smbus, uint8_t targetAddr, uint8_t txData)
Sends byte to the slave.
int8_t SMBus_masterReceiveByte (SMBus *smbus, uint8_t targetAddr, uint8_t *rxData)
Receive a byte from the slave.
int8_t SMBus_masterReadBlock (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *rxData)
Receive a block of data from the slave.
int8_t SMBus_masterWriteBlock (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *txData, uint8_t txSize)
Transmit a block of data to the slave.
int8_t SMBus_masterReadByteWord (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *rxData, uint8_t rxSize)
Send a command requesting a byte or word of data from the slave.
int8_t SMBus_masterWriteByteWord (SMBus *smbus, uint8_t targetAddr, uint8_t command, uint8_t *txData, uint8_t txSize)
Send a command transmitting a byte or word of data from the slave.
int8_t SMBus_masterQuickCommand (SMBus *smbus, uint8_t targetAddr, bool write)
Send a SMBus "quick command".
int8_t SMBus_masterWaitUntilDone (SMBus *smbus, int32_t timeout)
Wait until the previous SMBus command is executed.
Detailed Description
Macro Definition Documentation
#define SMB_CRC8_USE_LOOKUP_TABLE (1)
Define method used to calculate CRC8:
SMB_CRC8_USE_LOOKUP_TABLE == 1 - Use a 256B lookup table (faster but takes more memory)
SMB_CRC8_USE_LOOKUP_TABLE == 0 - Calculate CRC8 manually (slower but takes less memory)
#define SMB_MANUAL_ACK_ENABLE (0)
Define to enable Manual ACK workaround.
The MSP403 eUSCI doesn't support tesing a received byte and NACK/ACK immediately. This workaround uses DMA to stretch SCL low immediately after a byte is received. The DMA ISR is attended and the application then decides if it needs to ACK or NACK the byte This capability is not supported on devices that do not have DMA (e.g. MSP430G2xxx.
Enumeration Type Documentation
enum SMBus_ErrorCode
List of error codes used by the application to indicate an error to the library.
Enumerator
SMBus_ErrorCode_Packet
No error detected.
SMBus_ErrorCode_Cmd
Incorrect packet was received.
Command is not supported
enum SMBus_NwkState
SMBus network layer states.
Enumerator
SMBus_NwkState_RX
Network is idle and waiting for new packet.
SMBus_NwkState_TX
Network is receiving a packet.
SMBus_NwkState_TXQuickCMD
Network is transmitting after receive byte.
SMBus_NwkState_TX_Resp
Network is sending Quick Command.
SMBus_NwkState_TX_Block
Network is transmitting a response after restart.
SMBus_NwkState_RX_Block
Network is transmitting a block.
SMBus_NwkState_Ending
Network is receiving a block.
SMBus_NwkState_Error
Network is finishing transfer.
Network error detected
enum SMBus_State
SMBus state sent to application layer.
Enumerator
SMBus_State_DataSizeError
Nothing special to report.
SMBus_State_PECError
Incorrect packet size.
SMBus_State_TimeOutError
PEC Error detected.
SMBus_State_Slave_FirstByte
Timeout Error.
SMBus_State_Slave_ByteReceived
1st byte (cmd) received
SMBus_State_Slave_QCMD
Slave received a byte (2-n)
SMBus_State_Slave_CmdComplete
Quick Command detected.
SMBus_State_Slave_Error
Complete packet received by slave.
SMBus_State_Slave_NotReady
SMBus Slave Error.
SMBus_State_Slave_NTR
SMBus Buffers haven't been initialized.
SMBus_State_Master_ArbLost
No Interrupt flags detected.
SMBus_State_Master_NACK
Arbitration Lost.
SMBus_State_Master_Error
Unexpected NACKed.
SMBus_State_Unknown
SMBus Master error.
enum SMBus_Stop
List of stop codes used within the NWK and PHY layers.
Enumerator
SMBus_Stop_Immediate
No Stop send.
SMBus_Stop_Addr
Stop is send immediately with Start.
SMBus_Stop_PreRead
Stop is send after Start.
SMBus_Stop_Sent
Stop sent before reading next byte.
Function Documentation
void SMBus_disablePEC (SMBus * smbus)
Disables PEC support.
Parameters
smbus Pointer to SMBus structure
Returns
None
References SMBus_Ctrl::bits, and SMBus::ctrl.
void SMBus_enablePEC (SMBus * smbus)
Enables PEC support.
Parameters
smbus Pointer to SMBus structure
Returns
None
References SMBus_Ctrl::bits, and SMBus::ctrl.
uint8_t SMBus_getRxPayloadAvailable (SMBus * smbus)
Returns the number of received bytes from last transaction.
Parameters
smbus Pointer to SMBus structure
Returns
Number of bytes in the RX buffer. PEC byte is not included.
References SMBus_NWK_getRxPayloadSize().
SMBus_State SMBus_getState (SMBus * smbus)
Returns the state of the SMBus module.
Parameters
smbus Pointer to SMBus structure
Returns
State of the SMBus module
References SMBus::state.
void SMBus_masterEnableInt (SMBus * smbus)
Enables the I2C interrupts for a master.
This function enables the eUSCI Start,Stop, RX,TX, Timeout interrupts. SMBus_masterInit() must be called before this function. If SMB_MANUAL_ACK_ENABLE is enabled, it enables DMA to handle the RX.
Parameters
smbus Pointer to SMBus structure
Returns
none
References SMBus_PHY_masterEnableInt().
Referenced by SMBus_PHY_masterEnable().
void SMBus_masterInit (SMBus * smbus, uint16_t i2cAddr, uint32_t busClk)
Initialize the SMBus Interface for a master.
Initializes the NWK and PHY layers
Parameters
smbus Pointer to SMBus structure
i2cAddr Base address of I2C module. For MSP430G2xxx devices, this parameter is ignored.
busClk SMCLK Frequency
References SMBus_Ctrl::bits, SMBus::ctrl, SMBus_Nwk::currentAddr, SMBus_Ctrl::master, SMBus::nwk, SMBus_Nwk::pec, SMBus_Nwk::recByteTxPtr, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxIndex, SMBus_Nwk::rxLen, SMBus_Nwk::rxSize, SMBus_PHY_masterInit(), SMBus::state, SMBus::status, SMBus_Nwk::txBuffPtr, SMBus_Nwk::txIndex, SMBus_Nwk::txLen, SMBus_Nwk::txSize, SMBus_Ctrl::u8byte, and SMBus_Status::u8byte.
int8_t SMBus_masterProcessCall (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * txData, uint8_t * rxData)
Sends a process call to a slave.
Send process call to the slave. A command byte and 2 bytes of TX data are required. Two bytes of data will be returned by the slave in rxData.
 SMBus Process Call command protocol
 Process Call:
      1         7         1    1         8        1       8           1          8         1
    ------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte Low | A | Data Byte High | A | ...
    ------------------------------------------------------------------------------------------
      1         7          1    1         8         1       8           1    1
    ----------------------------------------------------------------------------
    | Sr | Slave Address | Rd | A | Data Byte Low | A | Data Byte High | A | P |
    ----------------------------------------------------------------------------
 Process Call with PEC:
      1         7         1    1         8        1       8           1          8         1
    ------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte Low | A | Data Byte High | A | ...
    ------------------------------------------------------------------------------------------
      1         7          1    1         8         1       8            1    8    1   1
    --------------------------------------------------------------------------------------
    | Sr | Slave Address | Rd | A | Data Byte Low | A | Data Byte High | A | PEC | A | P |
    --------------------------------------------------------------------------------------
 where:
     S = Start bit
     Sr = Reapeated Start bit
     Wr = Write bit (0)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
txData TX data buffer
rxData RX data buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX, SMBUS_RET_ERROR, SMBUS_RET_OK, SMBus_Nwk::txBuffPtr, and SMBus_Nwk::txLen.
int8_t SMBus_masterProcessCallBlock (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * txData, uint8_t txSize, uint8_t * rxData)
Sends a block write-block read process call.
Send block write-block read process call to the slave. A command byte, length and tx data byte array are required. Ensure that rxData is large enough to hold the data received from the slave.
 SMBus Block write-block read process call protocol
 Block write-block read process call:
      1         7         1    1         8        1         8          1       8         1
    ----------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Byte Count = M | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------------------------
           8        1                8        1
    -------------------       -------------------
    | Data Byte 2 | A |  ...  | Data Byte M | A | ...
    -------------------       -------------------
       1        7           1   1         8          1       8         1
    ----------------------------------------------------------------------
    | Sr | Slave Address | Rd | A | Byte Count = N | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------
           8        1                8        1   1
    -------------------       -----------------------
    | Data Byte 2 | A |  ...  | Data Byte N | A | P |
    -------------------       -----------------------
 Block write-block read process call with PEC:
      1         7         1    1         8        1         8          1       8         1
    ----------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Byte Count = M | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------------------------
           8        1                8        1
    -------------------       -------------------
    | Data Byte 2 | A |  ...  | Data Byte M | A | ...
    -------------------       -------------------
       1        7           1   1         8          1       8         1
    ----------------------------------------------------------------------
    | Sr | Slave Address | Rd | A | Byte Count = N | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------
           8        1                8        1    8    1   1
    -------------------       ---------------------------------
    | Data Byte 2 | A |  ...  | Data Byte N | A | PEC | A | P |
    -------------------       ---------------------------------
 where:
     S = Start bit
     Sr = Reapeated Start bit
     Wr = Write bit (0)
     Rd = Read bit (1)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
txData TX data buffer
txSize Size of the txData buffer
rxData RX data buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxLen, SMB_MAX_PAYLOAD_SIZE, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX_Block, SMBUS_RET_ERROR, SMBUS_RET_OK, SMBus_Nwk::txBuffPtr, and SMBus_Nwk::txLen.
SMBus_State SMBus_masterProcessInt (SMBus * smbus)
I2C Interrupt Service routine for a master.
Handles the interrupts for SMBus passing information to NWK layer Should be called by application when USCI interrupt is detected
Parameters
smbus Pointer to SMBus structure
Returns
Processing State (SMBus_State)
References SMBus_PHY_masterProcessInt().
SMBus_State SMBus_masterProcessTimeoutInt (SMBus * smbus)
Timer interrupt service routine for a master.
Handles the interrupts for SMBus tiemout processing for USCI devices. Should be called by application when Timer interrupt is detected
Parameters
smbus Pointer to SMBus structure
Returns
Processing State (SMBus_State):
References SMBus_PHY_masterProcessTimeoutInt().
int8_t SMBus_masterQuickCommand (SMBus * smbus, uint8_t targetAddr, bool write)
Send a SMBus "quick command".
A "quick command" is only a trigger. There is no data sent or received.
 SMBus Quick Commmand Protocol:
      1         7           1     1   1
    -------------------------------------
    | S | Slave Address | Rd/Wr | A | P |
    -------------------------------------
 where:
     S = Start bit
     Rd/Wr = Read or Write bit
     Slave Adddress = SMBus address for slave
     A = Acknowledge from slave
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
write true if this is a write command, false if this is a read command
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus::nwk, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TXQuickCMD, SMBUS_RET_ERROR, SMBUS_RET_OK, and SMBus_Nwk::txLen.
int8_t SMBus_masterReadBlock (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * rxData)
Receive a block of data from the slave.
Send block data receive call to the slave. A command byte, length and rx data byte array are required. Ensure that rxData is large enough to hold the data received from the slave.
 SMBus Block Read command protocol
 Block Read:
      1         7         1    1         8        1   1         8          1    1
    -------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Sr | Slave Address | Rd | A | ...
    -------------------------------------------------------------------------------
              8        1        8        1        8        1                8        1   1
    ----------------------------------------------------------------------------------------
    | Byte Count = N | A | Data Byte 1 | A | Data Byte 2 | A |  ...  | Data Byte N | A | P |
    ----------------------------------------------------------------------------------------
 Block Read with PEC:
      1         7         1    1         8        1   1         8          1    1
    -------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Sr | Slave Address | Rd | A | ...
    -------------------------------------------------------------------------------
              8        1        8        1        8        1                8        1
    ------------------------------------------------------------------------------------
    | Byte Count = N | A | Data Byte 1 | A | Data Byte 2 | A |  ...  | Data Byte N | A |...
    ------------------------------------------------------------------------------------
       8    1   1
    ---------------
    | PEC | A | P |
    ---------------
 where:
     S = Start bit
     Sr = Reapeated Start bit
     Wr = Write bit (0)
     Rd = Read bit (1)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
rxData RX data buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX_Block, SMBUS_RET_ERROR, SMBUS_RET_OK, and SMBus_Nwk::txLen.
int8_t SMBus_masterReadByteWord (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * rxData, uint8_t rxSize)
Send a command requesting a byte or word of data from the slave.
 SMBus Read ByteWord command protocol
 Read Byte:
      1         7         1    1         8        1       8           1    1       8       1   1
    ----------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | S | Slave Address | Rd | A | Data Byte | A | P |
    ----------------------------------------------------------------------------------------------
 Read Byte with PEC:
      1         7         1    1         8        1       8           1    1       8       1   1
    ----------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | S | Slave Address | Rd | A | Data Byte | A | P | ...
    ----------------------------------------------------------------------------------------------
     8    1   1
    ---------------
    | PEC | A | P |
    ---------------
 Read Word:
      1         7         1    1         8        1       8           1    1       8           1   1
    --------------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | S | Slave Address | Rd | A | Data Byte Low | A | P | ...
    --------------------------------------------------------------------------------------------------
             8         1   1
    --------------------------
    | Data Byte High | A | P |
    --------------------------
 Read Word with PEC:
      1         7         1    1         8        1       8           1    1       8           1   1
    --------------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | S | Slave Address | Rd | A | Data Byte Low | A | P | ...
    --------------------------------------------------------------------------------------------------
             8         1   1    8    1   1
    ----------------------------------------
    | Data Byte High | A | P | PEC | A | P |
    ----------------------------------------
 where:
     S = Start bit
     Wr = Read bit (0)
     Rd = Read bit (1)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
rxData RX data buffer
rxSize Must be 1 or 2 bytes
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX, SMBUS_RET_ERROR, SMBUS_RET_OK, and SMBus_Nwk::txLen.
int8_t SMBus_masterReceiveByte (SMBus * smbus, uint8_t targetAddr, uint8_t * rxData)
Receive a byte from the slave.
 SMBus Receive Byte command protocol
      1         7         1    1       8       1   1
    --------------------------------------------------
    | S | Slave Address | Rd | A | Data Byte | A | P |
    --------------------------------------------------
 With PEC:
      1         7         1    1       8       1    8    1   1
    ------------------------------------------------------------
    | S | Slave Address | Rd | A | Data Byte | A | PEC | A | P |
    ------------------------------------------------------------
 where:
     S = Start bit
     Rd = Read bit (1)
     Slave Adddress = SMBus address for slave
     Data Byte = data received from slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
rxData RX data buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus::nwk, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxLen, SMBus_NWK_startRxTransfer(), SMBus_NwkState_RX, SMBUS_RET_ERROR, SMBUS_RET_OK, and SMBus_Nwk::txLen.
void SMBus_masterReset (SMBus * smbus)
Force reset to SMBus master interface.
Resets the network and PHY layers
Parameters
smbus Pointer to SMBus structure
Returns
None
References SMBus_NWK_masterReset().
int8_t SMBus_masterSendByte (SMBus * smbus, uint8_t targetAddr, uint8_t txData)
Sends byte to the slave.
 SMBus Send Byte command protocol
      1         7         1    1        8       1   1
    ---------------------------------------------------
    | S | Slave Address | Wr | A |  Data Byte | A | P |
    ---------------------------------------------------
 Send Byte with PEC:
      1         7         1    1       8       1    8    1   1
    ------------------------------------------------------------
    | S | Slave Address | Wr | A | Data Byte | A | PEC | A | P |
    ------------------------------------------------------------
 where:
     S = Start bit
     Wr = Write bit (0)
     Slave Adddress = SMBus address for slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
txData TX data buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX, SMBUS_RET_ERROR, SMBUS_RET_OK, and SMBus_Nwk::txLen.
int8_t SMBus_masterWaitUntilDone (SMBus * smbus, int32_t timeout)
Wait until the previous SMBus command is executed.
Parameters
smbus Pointer to SMBus structure
timeout Software timeout
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus::nwk, SMBUS_RET_ERROR, and SMBUS_RET_OK.
int8_t SMBus_masterWriteBlock (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * txData, uint8_t txSize)
Transmit a block of data to the slave.
Send block of data to the slave. A command byte, length and tx data byte array are required.
 SMBus Block Write command protocol
 Block Write:
      1         7         1    1         8        1         8          1          8      1
    ----------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Byte Count = N | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------------------------
            8       1                 8       1   1
    --------------------      -----------------------
    | Data Byte 2 | A |  ...  | Data Byte N | A | P |
    --------------------      -----------------------
 Block Write with PEC:
      1         7         1    1         8        1         8          1          8      1
    ----------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Byte Count = N | A | Data Byte 1 | A | ...
    ----------------------------------------------------------------------------------------
            8       1                 8       1    8    1   1
    --------------------      ---------------------------------
    | Data Byte 2 | A |  ...  | Data Byte N | A | PEC | A | P |
    --------------------      ---------------------------------
 where:
     S = Start bit
     Wr = Write bit (0)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
txData TX data buffer
txSize Size of the txData buffer
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxLen, SMB_MAX_PAYLOAD_SIZE, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX_Block, SMBUS_RET_ERROR, SMBUS_RET_OK, SMBus_Nwk::txBuffPtr, and SMBus_Nwk::txLen.
int8_t SMBus_masterWriteByteWord (SMBus * smbus, uint8_t targetAddr, uint8_t command, uint8_t * txData, uint8_t txSize)
Send a command transmitting a byte or word of data from the slave.
 SMBus Write ByteWord command protocol
 Write Byte:
      1         7         1    1         8        1       8       1   1
    ---------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte | A | P |
    ---------------------------------------------------------------------
 Write Byte with PEC:
      1         7         1    1         8        1       8       1    8    1   1
    -------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte | A | PEC | A | P |
    -------------------------------------------------------------------------------
 Write Word:
      1         7         1    1         8        1       8           1          8         1   1
    ----------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte Low | A | Data Byte High | A | P |
    ----------------------------------------------------------------------------------------------
 Write Word with PEC:
      1         7         1    1         8        1       8           1          8         1    8    1   1
    --------------------------------------------------------------------------------------------------------
    | S | Slave Address | Wr | A | Command Code | A | Data Byte Low | A | Data Byte High | A | PEC | A | P |
    --------------------------------------------------------------------------------------------------------
 where:
     S = Start bit
     Wr = Write bit (0)
     Slave Adddress = SMBus address for slave
     Command Code = Command byte sent to slave
     Data Byte = data sent to slave
     A = Acknowledge from slave
     PEC = Optional Packet Error Code
     P = Stop bit
Parameters
smbus Pointer to SMBus structure
targetAddr Slave address
command Command byte for slave
txData TX data buffer
txSize Must be 1 or 2 bytes
Returns
SMBUS_RET_ERROR, or SMBUS_RET_OK
References SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus::nwk, SMBus_Nwk::rxLen, SMBus_NWK_startTxTransfer(), SMBus_NwkState_TX, SMBUS_RET_ERROR, SMBUS_RET_OK, SMBus_Nwk::txBuffPtr, and SMBus_Nwk::txLen.
void SMBus_processDone (SMBus * smbus)
Clears the current state of SMBus.
Must be called by application in order to clear the state machine when a byte/packet was processed
Parameters
smbus Pointer to SMBus structure
Returns
None
References SMBus::state.
uint8_t SMBus_slaveClearStatusReg (SMBus * smbus, uint8_t val)
Clear the slave's status register.
Parameters
smbus Pointer to SMBus structure
val Bits cleared from status register (1=X, 0=clear)
Returns
Value of Status register after clearing flags
References SMBus::status, and SMBus_Status::u8byte.
void SMBus_slaveEnableInt (SMBus * smbus)
Enables the I2C interrupts for a slave.
This function enables the eUSCI Start,Stop, RX,TX, Timeout interrupts If SMB_MANUAL_ACK_ENABLE is enabled, it enables DMA to handle the RX SMBus_slaveInit() must be called before this function
Parameters
smbus Pointer to SMBus structure
Returns
None
References SMBus_PHY_slaveEnableInt().
Referenced by SMBus_PHY_slaveEnable().
uint8_t SMBus_slaveGetCommand (SMBus * smbus)
Return the current command (Rxbuffer[0]) received by the slave.
Parameters
smbus Pointer to SMBus structure
Returns
Current command byte
References SMBus_Nwk::currentCmd, and SMBus::nwk.
void SMBus_slaveInit (SMBus * smbus, uint16_t i2cAddr)
Initialize the SMBus interface as a slave.
Initializes the NWK and PHY layers.
Parameters
smbus Pointer to SMBus structure
i2cAddr Base address of I2C module. For MSP430G2xxx devices, this parameter is ignored.
Returns
None
References SMBus_Ctrl::bits, SMBus::ctrl, SMBus_Nwk::currentAddr, SMBus_Nwk::currentCmd, SMBus_Ctrl::master, SMBus::nwk, SMBus_Nwk::pec, SMBus_Nwk::recByteTxPtr, SMBus_Nwk::rxBuffPtr, SMBus_Nwk::rxIndex, SMBus_Nwk::rxLen, SMBus_Nwk::rxSize, SMBus_PHY_slaveInit(), SMBus::state, SMBus::status, SMBus_Nwk::txBuffPtr, SMBus_Nwk::txIndex, SMBus_Nwk::txLen, SMBus_Nwk::txSize, SMBus_Ctrl::u8byte, and SMBus_Status::u8byte.
SMBus_State SMBus_slaveProcessInt (SMBus * smbus)
I2C Interrupt Service routine for a slave.
Handles the interrupts for SMBus passing information to NWK layer Should be called by application when USCI/DMA interrupt is detected Note that this routine also checks the DMA due to the SW ACK workaround if SMB_MANUAL_ACK_ENABLE is defined.
Parameters
smbus Pointer to SMBus structure
Returns
Processing State (SMBus_State)
SMBus_State_Slave_NotReady - Packet is not ready
SMBus_State_Slave_FirstByte - First byte received (application can use it to validate the command)
SMBus_State_Slave_ByteReceived - Byte 2+ received (application can use it to validate each byte)
SMBus_State_Slave_QCMD - Quick command received
SMBus_State_Slave_CmdComplete - Packet complete and if PEC enabled, validated.
References SMBus_PHY_slaveProcessInt(), SMBus_State_Slave_NTR, and SMBus::state.
SMBus_State SMBus_slaveProcessTimeoutInt (SMBus * smbus)
Timer interrupt service routine for slave application.
Handles the interrupts for SMBus tiemout processing for USCI devices. Should be called by application when Timer interrupt is detected
Parameters
smbus Pointer to SMBus structure
Returns
Processing State (SMBus_State):
SMBus_State_TimeOutError - Timeout ocurred, SMBUS has been restarted
References SMBus_PHY_slaveProcessTimeoutInt().
void SMBus_slaveReportError (SMBus * smbus, SMBus_ErrorCode errorCode)
Reports an error to SMBus driver from the slave.
Used to signal an error when incorrect command/data is detected by the slave
Parameters
smbus Pointer to SMBus structure
errorCode SMBus_ErrorCode
Returns
None
References SMBus_Status::bits, SMBus_Status::cmdErr, SMBus::nwk, SMBus_Status::packErr, SMBus_ErrorCode_Cmd, SMBus_ErrorCode_Packet, SMBus_NwkState_Error, and SMBus::status.
void SMBus_slaveSetAddress (SMBus * smbus, uint8_t slaveAddr)
Set the slave's own I2C address.
Parameters
smbus Pointer to SMBus structure
slaveAddr Slave I2C address
Returns
None
References SMBus_Ctrl::bits, SMBus::ctrl, SMBus::ownSlaveAddr, SMBus_Ctrl::phyEn, and SMBus_PHY_enable().
void SMBus_slaveSetRxBuffer (SMBus * smbus, uint8_t * data, uint8_t size)
Initialize the reception buffer for slave.
Parameters
smbus Pointer to SMBus structure
data Pointer to Application RX buffer
size Maximum size of buffer
Returns
None
References SMBus::nwk, SMBus_Nwk::rxBuffPtr, and SMBus_Nwk::rxSize.
void SMBus_slaveSetTxBuffer (SMBus * smbus, uint8_t * data, uint8_t size)
Initialize the transmission buffer for slave.
Parameters
smbus Pointer to SMBus structure
data Pointer to Application TX buffer
size Maximum size of buffer
Returns
None
References SMBus::nwk, SMBus_Nwk::txBuffPtr, and SMBus_Nwk::txSize.
uint8_t SMBus_slaveWriteCtrlReg (SMBus * smbus, uint8_t val)
Write a value to the slave's control register.
Parameters
smbus Pointer to SMBus structure
val Value being written to the Control register
Returns
Value of Control register after write
References SMBus::ctrl, SMBus_Ctrl::u8byte, and SMBus_Ctrl::writeableBits.
Copyright 2015, Texas Instruments Incorporated