var jsonInfo = [
	{
		"MCU"    : "MSP430",
		"Device" : "MSP430F461x",
		"Filter" : "MSP430F461\\d"
	}
];

var jsonObjC = [
	{"SourcePreview" : "msp430x46x_1.c",                               "Description" : "Software Toggle P1.0"},
	{"SourcePreview" : "msp430x46x_adc12_01.c",                        "Description" : "ADC12, Sample A0, Set P5.1 if A0 > 0.5*AVcc"},
	{"SourcePreview" : "msp430x46x_adc12_02.c",                        "Description" : "ADC12, Using the Internal Reference"},
	{"SourcePreview" : "msp430x46x_adc12_03.c",                        "Description" : "ADC12, Sample A10 Temp, Set P5.1 if Temp ++ ~2C"},
	{"SourcePreview" : "msp430x46x_adc12_04.c",                        "Description" : "ADC12, Extend Sampling Period with SHT Bits"},
	{"SourcePreview" : "msp430x46x_adc12_05.c",                        "Description" : "ADC12, Using an External Reference"},
	{"SourcePreview" : "msp430x46x_adc12_06.c",                        "Description" : "ADC12, Repeated Sequence of Conversions"},
	{"SourcePreview" : "msp430x46x_adc12_07.c",                        "Description" : "ADC12, Repeated Single Channel Conversions"},
	{"SourcePreview" : "msp430x46x_adc12_08.c",                        "Description" : "ADC12, Using 10 External Channels for Conversion"},
	{"SourcePreview" : "msp430x46x_adc12_09.c",                        "Description" : "ADC12, Sequence of Conversions (non-repeated)"},
	{"SourcePreview" : "msp430x46x_adc12_10.c",                        "Description" : "ADC12, Sample A10 Temp and Convert to oC and oF"},
	{"SourcePreview" : "msp430x46x_bt_01.c",                           "Description" : "Basic Timer, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_clks_02.c",                         "Description" : "FLL+, Output 32kHz Xtal + HF Xtal + Internal DCO"},
	{"SourcePreview" : "msp430x46x_compA_01.c",                        "Description" : "Comparator A, Poll input CA0, result in P5.1"},
	{"SourcePreview" : "msp430x46x_compA_02.c",                        "Description" : "Comparator A, Poll input CA0, CA exchange, result in P5.1"},
	{"SourcePreview" : "msp430x46x_compA_04.c",                        "Description" : "Comparator A, Poll input CA0, result in P5.1"},
	{"SourcePreview" : "msp430x46x_compA_05.c",                        "Description" : "Comparator A, Poll input CA0, interrupt triggered"},
	{"SourcePreview" : "msp430x46x_fll_01.c",                          "Description" : "FLL+, Runs Internal DCO at 2.45MHz"},
	{"SourcePreview" : "msp430x46x_fll_02.c",                          "Description" : "FLL+, Runs Internal DCO at 8MHz"},
	{"SourcePreview" : "msp430x46x_hfxt2.c",                           "Description" : "FLL+, MCLK Configured to Operate from XT2 HF XTAL"},
	{"SourcePreview" : "msp430x46x_lpm3.c",                            "Description" : "Basic Clock, LPM3 Using WDT ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_OF_LFXT1_nmi.c",                    "Description" : "LFXT1 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x46x_OF_XT2.c",                          "Description" : "XT2 Oscillator Fault Detection"},
	{"SourcePreview" : "msp430x46x_P1_01.c",                           "Description" : "Software Poll P1.4, Set P5.1 if P1.4 = 1"},
	{"SourcePreview" : "msp430x46x_P1_02.c",                           "Description" : "Software Port Interrupt on P1.4 from LPM4"},
	{"SourcePreview" : "msp430x46x_P1_05.c",                           "Description" : "Write a byte to Port 1"},
	{"SourcePreview" : "msp430x46x_P7_05.c",                           "Description" : "Write a byte to Port 7"},
	{"SourcePreview" : "msp430x46x_P8_05.c",                           "Description" : "Write a byte to Port 8"},
	{"SourcePreview" : "msp430x46x_PA_05.c",                           "Description" : "Write a word to Port A"},
	{"SourcePreview" : "msp430x46x_PB_05.c",                           "Description" : "Write a word to Port B"},
	{"SourcePreview" : "msp430x46x_rtc_01.c",                          "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_rtc_02.c",                          "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK;and send Time via UART"},
	{"SourcePreview" : "msp430x46x_rtc_03.c",                          "Description" : "Real Time Clock, Toggle P5.1 Inside ISR, 32kHz ACLK;send Time via UART and preserve across RESET"},
	{"SourcePreview" : "msp430x46x_ta_01.c",                           "Description" : "Timer_A, Toggle P5.1, TACCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_ta_02.c",                           "Description" : "Timer_A, Toggle P5.1, TACCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_ta_03.c",                           "Description" : "Timer_A, Toggle P5.1, Overflow ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_ta_04.c",                           "Description" : "Timer_A, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_ta_05.c",                           "Description" : "Timer_A, Toggle P5.1, TACCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_ta_08.c",                           "Description" : "Timer_A, Toggle P1.0,P1.2 & P2.0 Cont. Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_ta_11.c",                           "Description" : "Timer_A, Toggle P1.0/TA0, Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_ta_13.c",                           "Description" : "Timer_A, Toggle P1.0/TA0, Up/Down Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_ta_17.c",                           "Description" : "Timer_A, PWM TA1-2 Up Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_ta_19.c",                           "Description" : "Timer_A, PWM TA1-2, Up/Down Mode, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_tb_01.c",                           "Description" : "Timer_B, Toggle P5.1, TBCCR0 Cont. Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_tb_02.c",                           "Description" : "Timer_B, Toggle P5.1, TBCCR0 Up Mode ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_tb_04.c",                           "Description" : "Timer_B, Toggle P5.1, Overflow ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_tb_05.c",                           "Description" : "Timer_B, Toggle P5.1, TBCCR0 Up Mode ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_tb_10.c",                           "Description" : "Timer_B, PWM TB1-6, Up Mode, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_usart1_19200.c",                    "Description" : "USART1, Ultra-Low Pwr UART 19200 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_usart1_spi0_09.c",                  "Description" : "USART1, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x46x_usart1_spi0_10.c",                  "Description" : "USART1, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x46x_usart1_spi1_01.c",                  "Description" : "USART1, SPI Interface to TLC549 8-Bit ADC"},
	{"SourcePreview" : "msp430x46x_usart1_uart_115k.c",                "Description" : "USART1, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_usart1_uart_2400.c",                "Description" : "USART1, Ultra-Low Pwr UART 2400 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_usart1_uart_9600.c",                "Description" : "USART1, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_uscia0b0_uart_spi_01.c",            "Description" : "USCI_A0 UART TX single byte and USCI_B0 SPI Master TX single byte to MSP430 Slave"},
	{"SourcePreview" : "msp430x46x_uscia0b0_uart_spi_02.c",            "Description" : "USCI_A0 UART RX single byte and USCI_B0 SPI Slave RX single byte from MSP430 Master"},
	{"SourcePreview" : "msp430x46x_uscia0_duplex_9600.c",              "Description" : "USCI_A0, UART 9600 Full-Duplex Transceiver, 32K ACLK"},
	{"SourcePreview" : "msp430x46x_uscia0_irda_01.c",                  "Description" : "USCI_A0 IrDA External Loopback Test, 4MHz SMCLK"},
	{"SourcePreview" : "msp430x46x_uscia0_irda_02.c",                  "Description" : "USCI_A0 IrDA Monitor, 4MHz SMCLK"},
	{"SourcePreview" : "msp430x46x_uscia0_spi_09.c",                   "Description" : "USCI_A0, SPI 3-Wire Master Incremented Data"},
	{"SourcePreview" : "msp430x46x_uscia0_spi_10.c",                   "Description" : "USCI_A0, SPI 3-Wire Slave Data Echo"},
	{"SourcePreview" : "msp430x46x_uscia0_uart_115k.c",                "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK"},
	{"SourcePreview" : "msp430x46x_uscia0_uart_115k_lpm.c",            "Description" : "USCI_A0, 115200 UART Echo ISR, DCO SMCLK, LPM3"},
	{"SourcePreview" : "msp430x46x_uscia0_uart_9600.c",                "Description" : "USCI_A0, Ultra-Low Pwr UART 9600 Echo ISR, 32kHz ACLK"},
	{"SourcePreview" : "msp430x46x_uscia0_uart_uscia0b0_i2c_1.c",      "Description" : "USCI_A0 UART TX single byte and USCI_B0 I2C Master TX single byte to MSP430 Slave"},
	{"SourcePreview" : "msp430x46x_uscia0_uart_uscia0b0_i2c_2.c",      "Description" : "USCI_A0 UART RX single byte and USCI_B0 I2C Slave RX single byte from MSP430 Master"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_02.c",                   "Description" : "USCI_B0 I2C Master Interface to PCF8574, Read/Write"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_03.c",                   "Description" : "USCI_B0 I2C Master Interface to DAC8571, Write"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_08.c",                   "Description" : "USCI_B0 I2C Master TX multiple bytes to MSP430 Slave"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_09.c",                   "Description" : "USCI_B0 I2C Slave RX multiple bytes from MSP430 Master"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_10.c",                   "Description" : "USCI_B0 I2C Master RX multiple bytes from MSP430 Slave"},
	{"SourcePreview" : "msp430x46x_uscib0_i2c_11.c",                   "Description" : "USCI_B0 I2C Slave TX multiple bytes to MSP430 Master"},
	{"SourcePreview" : "msp430x46x_uscib0_spi_01.c",                   "Description" : "USCI_B0, SPI Interface to TLC549 8-Bit ADC"}
];

